### ISSUE TITLE
when use email and password in config , get error: No module named 'revChatGPT'

### ISSUE THREAD

**Issue by djerryz** [fuergaosi233/wechat-chatgpt#100]
## Error Desc
here is the error look like :
```python
Start GPT Bot Config is:[object Object]
uncaughtException Error: Command failed with exit code 1: sh -c poetry run python3 src/generate_session.py config_email config_pass
Traceback (most recent call last):
  File "/app/src/generate_session.py", line 23, in <module>
    from revChatGPT.revChatGPT import Chatbot
ModuleNotFoundError: No module named 'revChatGPT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/src/generate_session.py", line 25, in <module>
    raise RuntimeError("Could import revChatGPT. Please install it first.You can run `poetry install` to install it.")
RuntimeError: Could import revChatGPT. Please install it first.You can run `poetry install` to install it.
Creating virtualenv chatbot-twitter-9TtSrW0h-py3.11 in /root/.cache/pypoetry/virtualenvs
    at makeError (file:///app/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///app/node_modules/execa/index.js:119:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ChatGPTPoole.getSessionToken (file:///app/src/chatgpt.ts:35:42)
    at async file:///app/src/chatgpt.ts:59:33
    at async Promise.all (index 0)
    at async ChatGPTPoole.startPools (file:///app/src/chatgpt.ts:55:26)
    at async ChatGPTBot.startGPTBot (file:///app/src/chatgpt.ts:142:5)
    at async WechatyImpl.<anonymous> (file:///app/src/main.ts:21:5) {
  shortMessage: 'Command failed with exit code 1: sh -c poetry run python3 src/generate_session.py config_email config_pass,
  command: 'sh -c poetry run python3 src/generate_session.py config_email config_pass,
  escapedCommand: 'sh -c "poetry run python3 src/generate_session.py config_email config_pass,
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: 'Creating virtualenv chatbot-twitter-9TtSrW0h-py3.11 in /root/.cache/pypoetry/virtualenvs',
  stderr: 'Traceback (most recent call last):\n' +
    '  File "/app/src/generate_session.py", line 23, in <module>\n' +
    '    from revChatGPT.revChatGPT import Chatbot\n' +
    "ModuleNotFoundError: No module named 'revChatGPT'\n" +
    '\n' +
    'During handling of the above exception, another exception occurred:\n' +
    '\n' +
    'Traceback (most recent call last):\n' +
    '  File "/app/src/generate_session.py", line 25, in <module>\n' +
    '    raise RuntimeError("Could import revChatGPT. Please install it first.You can run `poetry install` to install it.")\n' +
    'RuntimeError: Could import revChatGPT. Please install it first.You can run `poetry install` to install it.',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

if continue use the bot and get this:
```
🎯 Triggered ChatGPT: 1+1等于
TypeError: Cannot read properties of undefined (reading 'chatGpt')
    at ChatGPTPoole.getConversation (file:///app/src/chatgpt.ts:91:34)
    at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:101:35)
    at ChatGPTBot.getGPTMessage (file:///app/src/chatgpt.ts:162:35)
    at ChatGPTBot.onPrivateMessage (file:///app/src/chatgpt.ts:217:35)
    at ChatGPTBot.onMessage (file:///app/src/chatgpt.ts:243:27)
    at WechatyImpl.<anonymous> (file:///app/src/main.ts:30:24)
    at WechatyImpl.emit (node:events:513:28)
    at WechatyImpl.emit (node:domain:489:12)
    at WechatyImpl.emit (file:///app/node_modules/wechaty/src/wechaty-mixins/gerror-mixin.ts:44:22)
    at PuppetWechat4u.<anonymous> (file:///app/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:281:22)

```

## Analysis
```bash
docker exec -it wechat-chatgpt-container /bin/bash

cd /app/

poetry run python3 src/generate_session.py myeamil mypassword
//  Get the same error as above

// but exec
poetry install
// and then exec
poetry run python3 src/generate_session.py myeamil mypassword
// everything is fine

// and we do the same things 'Step 9/11 : RUN poetry install && rm -rf ~/.cache/' which in Dockerfile
// and we get error again
// so the problem is operation 'rm -rf ~/.cache/'
```

## Solution
remove command line 'rm -rf ~/.cache/'
here is my PR: https://github.com/fuergaosi233/wechat-chatgpt/pull/101

**Comment by djerryz** [comment]
merge PR
