### ISSUE TITLE
revChatGPT版本太低导致用户名密码的登陆方式失败

### ISSUE THREAD

**Issue by djerryz** [fuergaosi233/wechat-chatgpt#104]
## Error Desc
```
Traceback (most recent call last):
  File "/app/src/generate_session.py", line 29, in <module>
    print(login(email, password))
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/generate_session.py", line 7, in login
    chatbot = Chatbot(
              ^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 59, in __init__
    self.refresh_session()
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 307, in refresh_session
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 304, in refresh_session
    self.login(self.config["email"], self.config["password"])
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 361, in login
    raise Exception("Error logging in")
Exception: Error logging in
['src/generate_session.py', 'config_email', 'config_pass']
    at makeError (file:///app/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///app/node_modules/execa/index.js:119:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ChatGPTPoole.getSessionToken (file:///app/src/chatgpt.ts:35:42)
    at async file:///app/src/chatgpt.ts:59:33
    at async Promise.all (index 0)
    at async ChatGPTPoole.startPools (file:///app/src/chatgpt.ts:55:26)
    at async ChatGPTBot.startGPTBot (file:///app/src/chatgpt.ts:142:5)
    at async WechatyImpl.<anonymous> (file:///app/src/main.ts:21:5) {
```

## Solution
更新pyproject.toml下依赖的版本，至少为0.0.33.5, 因为个人测试发现0.0.33.4都还存在报错，只有刚刚发布的0.0.33.5版本可以正常登录拿到session_token
```
revChatGPT = "^0.0.33.5"
```

here is my pr: https://github.com/fuergaosi233/wechat-chatgpt/pull/106

**Comment by fuergaosi233** [comment]
Thank you very much. I have updated it.
