### ISSUE TITLE
ChatGPTAPI error 403 

### ISSUE THREAD

**Issue by deadjoker** [fuergaosi233/wechat-chatgpt#109]
我是用google账号登陆的，我在chatgpt上试了下，直接用gmail没法登陆。config.yaml里只配置了token，运行报403错误
```
Error: ChatGPTAPI error 403
    at fetchSSE (file:///app/node_modules/chatgpt/src/fetch-sse.ts:13:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
不知道是我config配置的问题么
```
cat config.yaml
chatGPTAccountPool:
  - email: ''
    password: ''
    session_token: 'xxxx'
chatPrivateTiggerKeyword: "/c "
```

**Comment by OliverGrace** [comment]
把emai和password两个key去掉

**Comment by deadjoker** [comment]
> 把emai和password两个key去掉

去掉这个可以用，但第二次再问就报无法刷新token的错
```
🎯 Hit GPT Enabled User: a
Error: ChatGPT failed to refresh auth token. Error: 403 Forbidden
    at ChatGPTAPI.refreshAccessToken (file:///app/node_modules/chatgpt/src/chatgpt-api.ts:273:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ChatGPTAPI.sendMessage (file:///app/node_modules/chatgpt/src/chatgpt-api.ts:114:25)
    at async ChatGPTBot.getGPTMessage (file:///app/src/chatgpt.ts:105:14)
    at async ChatGPTBot.onMessage (file:///app/src/chatgpt.ts:137:24)
    at async WechatyImpl.<anonymous> (file:///app/src/main.ts:30:7)
Message: Message#Unknown[🗣Contact<b>]
```

**Comment by deadjoker** [comment]
还有就是`chatPrivateTiggerKeyword: "/c "`这个配置，在可以使用时，没有用‘/c ’开头的也会触发，这个是应该怎么配置一下
