### ISSUE TITLE
OpenAIAuth.py  line 219, in part_five Captcha detected

### ISSUE THREAD

**Issue by aimmon** [fuergaosi233/wechat-chatgpt#121]
uncaughtException Error: Command failed with exit code 1: sh -c poetry run python3 src/generate_session.py 用户名 密码
Traceback (most recent call last):
  File "/openai/wechat/wechat-chatgpt/src/generate_session.py", line 50, in <module>
    print(login(args.email, args.password))
  File "/openai/wechat/wechat-chatgpt/src/generate_session.py", line 19, in login
    chatbot = Chatbot(
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-_h5YiblG-py3.10/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 62, in __init__
    self.refresh_session()
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-_h5YiblG-py3.10/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 296, in refresh_session
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-_h5YiblG-py3.10/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 293, in refresh_session
    self.login(self.config["email"], self.config["password"])
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-_h5YiblG-py3.10/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 326, in login
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-_h5YiblG-py3.10/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 319, in login
    auth.begin()
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-_h5YiblG-py3.10/lib/python3.10/site-packages/OpenAIAuth/OpenAIAuth.py", line 83, in begin
    self.part_two()
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-_h5YiblG-py3.10/lib/python3.10/site-packages/OpenAIAuth/OpenAIAuth.py", line 112, in part_two
    self.part_three(token=csrf_token)
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-_h5YiblG-py3.10/lib/python3.10/site-packages/OpenAIAuth/OpenAIAuth.py", line 147, in part_three
    self.part_four(url=url)
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-_h5YiblG-py3.10/lib/python3.10/site-packages/OpenAIAuth/OpenAIAuth.py", line 181, in part_four
    self.part_five(state=state)
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-_h5YiblG-py3.10/lib/python3.10/site-packages/OpenAIAuth/OpenAIAuth.py", line 219, in part_five
    raise ValueError("Captcha detected")
ValueError: Captcha detected
Namespace(email='邮箱', password='密码')
    at makeError (file:///openai/wechat/wechat-chatgpt/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///openai/wechat/wechat-chatgpt/node_modules/execa/index.js:119:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ChatGPTPoole.getSessionToken (file:///openai/wechat/wechat-chatgpt/src/chatgpt.ts:56:42)
    at async file:///openai/wechat/wechat-chatgpt/src/chatgpt.ts:80:33
    at async Promise.all (index 0)
    at async ChatGPTPoole.startPools (file:///openai/wechat/wechat-chatgpt/src/chatgpt.ts:76:26)
    at async ChatGPTBot.startGPTBot (file:///openai/wechat/wechat-chatgpt/src/chatgpt.ts:163:5)
    at async WechatyImpl.<anonymous> (file:///openai/wechat/wechat-chatgpt/src/main.ts:21:5) {
  shortMessage: 'Command failed with exit code 1: sh -c poetry run python3 src/generate_session.py 邮箱 密码',
  command: 'sh -c poetry run python3 src/generate_session.py 邮箱 密码',
  escapedCommand: 'sh -c "poetry run python3 src/generate_session.py 邮箱 密码"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: "Namespace(email='邮箱', password='邮箱')",
  stderr: 'Traceback (most recent call last):\n' +
    '  File "/openai/wechat/wechat-chatgpt/src/generate_session.py", line 50, in <module>\n' +
    '    print(login(args.email, args.password))\n' +
    '  File "/openai/wechat/wechat-chatgpt/src/generate_session.py", line 19, in login\n' +
    '    chatbot = Chatbot(\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-_h5YiblG-py3.10/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 62, in __init__\n' +
    '    self.refresh_session()\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-_h5YiblG-py3.10/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 296, in refresh_session\n' +
    '    raise exc\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-_h5YiblG-py3.10/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 293, in refresh_session\n' +
    '    self.login(self.config["email"], self.config["password"])\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-_h5YiblG-py3.10/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 326, in login\n' +
    '    raise exc\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-_h5YiblG-py3.10/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 319, in login\n' +
    '    auth.begin()\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-_h5YiblG-py3.10/lib/python3.10/site-packages/OpenAIAuth/OpenAIAuth.py", line 83, in begin\n' +
    '    self.part_two()\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-_h5YiblG-py3.10/lib/python3.10/site-packages/OpenAIAuth/OpenAIAuth.py", line 112, in part_two\n' +
    '    self.part_three(token=csrf_token)\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-_h5YiblG-py3.10/lib/python3.10/site-packages/OpenAIAuth/OpenAIAuth.py", line 147, in part_three\n' +
    '    self.part_four(url=url)\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-_h5YiblG-py3.10/lib/python3.10/site-packages/OpenAIAuth/OpenAIAuth.py", line 181, in part_four\n' +
    '    self.part_five(state=state)\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-_h5YiblG-py3.10/lib/python3.10/site-packages/OpenAIAuth/OpenAIAuth.py", line 219, in part_five\n' +
    '    raise ValueError("Captcha detected")\n' +
    'ValueError: Captcha detected',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false

**Comment by fuergaosi233** [comment]
Your ip is checked by the CAPTCHA. Use the Session Token instead.
