### ISSUE TITLE
Loging OpenAI Error: AttributeError: 'OpenAIAuth' object has no attribute 'session_token'"

### ISSUE THREAD

**Issue by lushenle** [fuergaosi233/wechat-chatgpt#125]
## Environment

- Docker version: 20.10.21
- Image tage: 0.0.3-alpha

## Error msg

```
Namespace(email='xxx@gmail.com', password='my_openai_passwd')
Logging in...
    at makeError (file:///app/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///app/node_modules/execa/index.js:119:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ChatGPTPoole.getSessionToken (file:///app/src/chatgpt.ts:58:42)
    at async file:///app/src/chatgpt.ts:140:33
    at async Promise.all (index 0)
    at async ChatGPTPoole.startPools (file:///app/src/chatgpt.ts:136:26)
    at async ChatGPTBot.startGPTBot (file:///app/src/chatgpt.ts:233:5)
    at async WechatyImpl.<anonymous> (file:///app/src/main.ts:23:7) {
  shortMessage: 'Command failed with exit code 1: sh -c poetry run python3 src/generate_session.py xxx@gmail.com my_openai_passwd',
  command: 'sh -c poetry run python3 src/generate_session.py xxx@gmail.com my_openai_passwd',
  escapedCommand: 'sh -c "poetry run python3 src/generate_session.py xxx@gmail.com my_openai_passwd"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: "Namespace(email='xxx@gmail.com', password='my_openai_passwd')\n" +
    'Logging in...',
  stderr: 'Traceback (most recent call last):\n' +
    '  File "/app/src/generate_session.py", line 50, in <module>\n' +
    '    print(login(args.email, args.password))\n' +
    '          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n' +
    '  File "/app/src/generate_session.py", line 27, in login\n' +
    '    chatbot.login(\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 171, in login\n' +
    "    self.config['session_token'] = auth.session_token\n" +
    '                                   ^^^^^^^^^^^^^^^^^^\n' +
    "AttributeError: 'OpenAIAuth' object has no attribute 'session_token'",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**Comment by RealTong** [comment]
Seems to be the same problem as #123
