### ISSUE TITLE
Error: ⚠️ No chatgpt item in pool

### ISSUE THREAD

**Issue by onenov** [fuergaosi233/wechat-chatgpt#126]
🎯 Triggered ChatGPT: hello
Error: ⚠️ No chatgpt item in pool
    at ChatGPTPoole.getConversation (file:///app/src/chatgpt.ts:176:13)
    at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:188:35)
    at ChatGPTBot.getGPTMessage (file:///app/src/chatgpt.ts:253:35)
    at ChatGPTBot.onPrivateMessage (file:///app/src/chatgpt.ts:308:35)
    at ChatGPTBot.onMessage (file:///app/src/chatgpt.ts:334:27)
    at WechatyImpl.<anonymous> (file:///app/src/main.ts:32:26)
    at WechatyImpl.emit (node:events:513:28)
    at WechatyImpl.emit (node:domain:489:12)
    at WechatyImpl.emit (file:///app/node_modules/wechaty/src/wechaty-mixins/gerror-mixin.ts:44:22)
    at PuppetWechat4u.<anonymous> (file:///app/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:281:22)

**Comment by OliverGrace** [comment]
Try again

**Comment by currencytong** [comment]
make sure your config.yaml has the right format (indentation, space)
the right format
![image](https://user-images.githubusercontent.com/72449596/206821941-5db29eda-8326-40eb-97d8-4e3711ccc84a.png)

**Comment by molydaner** [comment]
chatGPTAccountPool:
  - session_token:
 这两行代码在输入到config文件时不要使用CTRL＋V，要用鼠标右键 粘贴就解决了chatGPTAccountPool:
 do not use CTRL+V use mouse right botton + copy
