### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by cypggs** [fuergaosi233/wechat-chatgpt#14]
wechat-chatgpt git:(main) ✗ npm run dev

> wechat-chatgpt@1.0.0 dev
> nodemon --exec node --loader ts-node/esm src/main.ts

[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/**/*
[nodemon] watching extensions: ts
[nodemon] starting `node --loader ts-node/esm src/main.ts`
(node:24192) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
uncaughtException Error [ERR_FR_TOO_MANY_REDIRECTS]: Maximum number of redirects exceeded
    at Function.AxiosError.from (/Users/case/wechat-chatgpt/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (/Users/case/wechat-chatgpt/node_modules/axios/lib/adapters/http.js:518:25)
    at RedirectableRequest.emit (node:events:525:35)
    at RedirectableRequest.emit (node:domain:489:12)
    at RedirectableRequest._processResponse (/Users/case/wechat-chatgpt/node_modules/follow-redirects/index.js:371:10)
    at ClientRequest.RedirectableRequest._onNativeResponse (/Users/case/wechat-chatgpt/node_modules/follow-redirects/index.js:62:10)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:513:28)
    at ClientRequest.emit (node:domain:489:12)
    at HTTPParser.parserOnIncomingClient (node:_http_client:674:27) {
  code: 2,
  details: 'Error [ERR_FR_TOO_MANY_REDIRECTS]: Maximum number of redirects exceeded\n' +
    '    at Function.AxiosError.from (/Users/case/wechat-chatgpt/node_modules/axios/lib/core/AxiosError.js:89:14)\n' +
    '    at RedirectableRequest.handleRequestError (/Users/case/wechat-chatgpt/node_modules/axios/lib/adapters/http.js:518:25)\n' +
    '    at RedirectableRequest.emit (node:events:525:35)\n' +
    '    at RedirectableRequest.emit (node:domain:489:12)\n' +
    '    at RedirectableRequest._processResponse (/Users/case/wechat-chatgpt/node_modules/follow-redirects/index.js:371:10)\n' +
    '    at ClientRequest.RedirectableRequest._onNativeResponse (/Users/case/wechat-chatgpt/node_modules/follow-redirects/index.js:62:10)\n' +
    '    at Object.onceWrapper (node:events:628:26)\n' +
    '    at ClientRequest.emit (node:events:513:28)\n' +
    '    at ClientRequest.emit (node:domain:489:12)\n' +
    '    at HTTPParser.parserOnIncomingClient (node:_http_client:674:27)'

**Comment by fuergaosi233** [comment]
Please try using Docker to start
