### ISSUE TITLE
docker部署0.0.3版本，登录后报错

### ISSUE THREAD

**Issue by Winspain** [fuergaosi233/wechat-chatgpt#161]
```bash
Start GPT Bot Config is:{"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":""}
uncaughtException TypeError: Cannot read properties of undefined (reading 'filter')
    at ChatGPTPoole.startPools (file:///app/src/chatgpt.ts:133:55)
    at ChatGPTBot.startGPTBot (file:///app/src/chatgpt.ts:233:28)
    at WechatyImpl.<anonymous> (file:///app/src/main.ts:23:24)
    at WechatyImpl.emit (node:events:513:28)
    at WechatyImpl.emit (node:domain:489:12)
    at WechatyImpl.emit (file:///app/node_modules/wechaty/src/wechaty-mixins/gerror-mixin.ts:44:22)
    at PuppetWechat4u.<anonymous> (file:///app/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:246:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by RealTong** [comment]
> ```shell
> User Contact<Code Master> logged in
> Start GPT Bot Config is:{"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":""}
> uncaughtException TypeError: Cannot read properties of undefined (reading 'filter')
>     at ChatGPTPoole.startPools (file:///app/src/chatgpt.ts:133:55)
>     at ChatGPTBot.startGPTBot (file:///app/src/chatgpt.ts:233:28)
>     at WechatyImpl.<anonymous> (file:///app/src/main.ts:23:24)
>     at WechatyImpl.emit (node:events:513:28)
>     at WechatyImpl.emit (node:domain:489:12)
>     at WechatyImpl.emit (file:///app/node_modules/wechaty/src/wechaty-mixins/gerror-mixin.ts:44:22)
>     at PuppetWechat4u.<anonymous> (file:///app/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:246:22)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> Message: Message#Unknown[🗣Contact<Code Master>]
> ```

这是因为你没有配置config.yaml

你可以在运行docker run命令的时候加上`-v /path/config.yaml:/app/config.yaml`映射config.yaml 或者之后使用docker cp 命令

**Comment by Winspain** [comment]
配置了config.yaml且docker命令按照readme中一模一样
昨天0.0.2的版本，正常使用
今天更新到0.0.3的版本，各种配置一样，但出现了这个问题
