### ISSUE TITLE
本地使用idea启动报：uncaughtException 

### ISSUE THREAD

**Issue by baymax55** [fuergaosi233/wechat-chatgpt#179]
python 和node环境已安装

Traceback (most recent call last):\r\n File "<frozen runpy>", line 198, in _run_module_as_main\r\n File "<frozen runpy>", line 88, in _run_code\r\n File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Scripts\poetry.exe\__main__.py", line 4, in <module>\r\nModuleNotFoundError: No module named **'poetry.console'**
![image](https://user-images.githubusercontent.com/35788491/206840635-fbffbee4-08ce-44ed-bcd8-7e6a4d1e134a.png)

**Comment by RealTong** [comment]
I don't think you have your account and password configured

Please add config.yaml to the project root directory

**Comment by baymax55** [comment]
> I don't think you have your account and password configured
> 
> Please add config.yaml to the project root directory

i did it,use session_token
![image](https://user-images.githubusercontent.com/35788491/206842131-981babdb-2d88-485e-8903-6b7795405bcf.png)
![image](https://user-images.githubusercontent.com/35788491/206842142-1b34f24d-2ceb-45ff-8f5b-782cec5c2546.png)

**Comment by RealTong** [comment]
If you use session_tokan, delete the email and password

**Comment by baymax55** [comment]
> f you use session_tokan, delete the email and password

not work.

`Command failed with exit code 1: powershell /c poetry run python3 src/generate_session.py laminux29@qq.com p1234567 Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Scripts\poetry.exe\__main__.py", line 4, in <module> ModuleNotFoundError: No module named 'poetry.console' at makeError (file:///E:/code/github/wechat-chatgpt/node_modules/execa/lib/error.js:59:11) at handlePromise (file:///E:/code/github/wechat-chatgpt/node_modules/execa/index.js:119:26) at processTicksAndRejections (node:internal/process/task_queues:95:5) at async ChatGPTPoole.getSessionToken (file:///E:/code/github/wechat-chatgpt/src/chatgpt.ts:58:42) at async file:///E:/code/github/wechat-chatgpt/src/chatgpt.ts:140:33 at async Promise.all (index 0) at async ChatGPTPoole.startPools (file:///E:/code/github/wechat-chatgpt/src/chatgpt.ts:136:26) at async ChatGPTBot.startGPTBot (file:///E:/code/github/wechat-chatgpt/src/chatgpt.ts:233:5) at async WechatyImpl.<anonymous> (file:///E:/code/github/wechat-chatgpt/src/main.ts:23:7)`


the problem is:No module named 'poetry.console' 

but i can not solve it.

i tried it,not work [[ModuleNotFoundError: No module named 'poetry.console'](https://stackoverflow.com/questions/67813396/modulenotfounderror-no-module-named-poetry-console)](https://stackoverflow.com/questions/67813396/modulenotfounderror-no-module-named-poetry-console)

**Comment by baymax55** [comment]
After using the built-in python 3.9 profile it's ok

**Comment by baymax55** [comment]
use session_token is fine, but when I use email and password login, it still does not work. because use python to generate session

**Comment by RealTong** [comment]
Have you tried reinstalling poetry? 

https://github.com/python-poetry/poetry/issues/5986

**Comment by baymax55** [comment]
when I just start the python script,it still does not work 

![image](https://user-images.githubusercontent.com/35788491/206898025-19379528-5af1-4c5e-9f1a-e7ce8dbf2824.png)


`
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\lib\site-packages\OpenAIAuth\OpenAIAuth.py", line 332, in part_seven
    self.part_eight(old_state=state, new_state=new_state)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\lib\site-packages\OpenAIAuth\OpenAIAuth.py", line 386, in part_eight
    raise Exception("Auth0 did not issue an access token")
Exception: Auth0 did not issue an access token

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\lib\site-packages\revChatGPT\revChatGPT.py", line 329, in refresh_session
    raise exc
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\lib\site-packages\revChatGPT\revChatGPT.py", line 326, in refresh_session
    self.login(self.config["email"], self.config["password"])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\lib\site-packages\revChatGPT\revChatGPT.py", line 362, in login
    raise exc
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\lib\site-packages\revChatGPT\revChatGPT.py", line 355, in login
    auth.begin()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\lib\site-packages\OpenAIAuth\OpenAIAuth.py", line 88, in begin
    self.part_two()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\lib\site-packages\OpenAIAuth\OpenAIAuth.py", line 117, in part_two
    self.part_three(token=csrf_token)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\lib\site-packages\OpenAIAuth\OpenAIAuth.py", line 152, in part_three
    self.part_four(url=url)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\lib\site-packages\OpenAIAuth\OpenAIAuth.py", line 186, in part_four
    self.part_five(state=state)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\lib\site-packages\OpenAIAuth\OpenAIAuth.py", line 244, in part_five
    self.part_six(state=state, captcha=captcha_code)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\lib\site-packages\OpenAIAuth\OpenAIAuth.py", line 287, in part_six
    self.part_seven(state=state)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\lib\site-packages\OpenAIAuth\OpenAIAuth.py", line 337, in part_seven
    raise Exception("State not found") from exc
Exception: State not found
python-BaseException

Process finished with exit code 1


`

**Comment by RealTong** [comment]
This is a normal situation

**Comment by RealTong** [comment]
> 

你应该使用命令调用, 而非修改代码中的字段
`poetry run python3 src/generate_session.py YOU_EMAIL YOU_PASSWORD`
或者
`poetry run python src/generate_session.py YOU_EMAIL YOU_PASSWORD`
