### ISSUE TITLE
使用 deploy on railway 部署，出现错误

### ISSUE THREAD

**Issue by gray-pigeons** [fuergaosi233/wechat-chatgpt#185]
使用 deploy on railway 部署，
微信登录之后提示：
ChatGPTPools: 1
🤖️ Start GPT Bot Success, ready to handle message!
但是发送消息却没有反应，提示如下错误信息：
Error: ⚠️ No chatgpt item in pool
at ChatGPTPoole.getConversation (file:///app/src/chatgpt.ts:176:13)
at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:188:35)
at ChatGPTBot.getGPTMessage (file:///app/src/chatgpt.ts:253:35)
at ChatGPTBot.onPrivateMessage (file:///app/src/chatgpt.ts:308:35)
at ChatGPTBot.onMessage (file:///app/src/chatgpt.ts:334:27)
at WechatyImpl.<anonymous> (file:///app/src/main.ts:32:26)
at WechatyImpl.emit (node:events:513:28)
at WechatyImpl.emit (node:domain:489:12)
at WechatyImpl.emit (file:///app/node_modules/wechaty/src/wechaty-mixins/gerror-mixin.ts:44:22)
at PuppetWechat4u.<anonymous> (file:///app/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:281:22)

**Comment by inannan423** [comment]
redeploy 一般能解决这个问题，或者再检查一下账号密码或 token 是否填写正确。

**Comment by bbhxwl** [comment]
> 使用 deploy on railway 部署， 微信登录之后提示： ChatGPTPools: 1 🤖️ Start GPT Bot Success, ready to handle message! 但是发送消息却没有反应，提示如下错误信息： Error: ⚠️ No chatgpt item in pool at ChatGPTPoole.getConversation (file:///app/src/chatgpt.ts:176:13) at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:188:35) at ChatGPTBot.getGPTMessage (file:///app/src/chatgpt.ts:253:35) at ChatGPTBot.onPrivateMessage (file:///app/src/chatgpt.ts:308:35) at ChatGPTBot.onMessage (file:///app/src/chatgpt.ts:334:27) at WechatyImpl. (file:///app/src/main.ts:32:26) at WechatyImpl.emit (node:events:513:28) at WechatyImpl.emit (node:domain:489:12) at WechatyImpl.emit (file:///app/node_modules/wechaty/src/wechaty-mixins/gerror-mixin.ts:44:22) at PuppetWechat4u. (file:///app/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:281:22)

我也同样的问题，正常了三四句话以后就这样了。

**Comment by fuergaosi233** [comment]
This means that there are no working OpenAI Account in the pool.

**Comment by butchoosed** [comment]
你的railway是怎么配置的？
