### ISSUE TITLE
Error on Platform Arm64 AArch64 Processor : Cortex-A53 * 4

### ISSUE THREAD

**Issue by mikehu2016** [fuergaosi233/wechat-chatgpt#186]
OSError: /root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/tls_client/dependencies/tls-client-amd64.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/src/generate_session.py", line 47, in <module>
    raise RuntimeError("Could import revChatGPT. Please install it first. You can run `poetry install` to install it.")
RuntimeError: Could import revChatGPT. Please install it first. You can run `poetry install` to install it.
    at makeError (file:///app/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///app/node_modules/execa/index.js:119:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ChatGPTPoole.getSessionToken (file:///app/src/chatgpt.ts:58:42)
    at async file:///app/src/chatgpt.ts:140:33
    at async Promise.all (index 2)
    at async ChatGPTPoole.startPools (file:///app/src/chatgpt.ts:136:26)
    at async ChatGPTBot.startGPTBot (file:///app/src/chatgpt.ts:233:5)
    at async WechatyImpl.<anonymous> (file:///app/src/main.ts:23:7) {
  shortMessage: 'Command failed with exit code 1: sh -c poetry run python3 src/generate_session.py xxmask@qq.com maskpassword',
  command: 'sh -c poetry run python3 src/generate_session.py maskaccoun@qq.com maskpassword',
  escapedCommand: 'sh -c "poetry run python3 src/generate_session.py maskaccoun@qq.com maskpassword"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'Traceback (most recent call last):\n' +
    '  File "/app/src/generate_session.py", line 45, in <module>\n' +
    '    from revChatGPT.revChatGPT import Chatbot\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 9, in <module>\n' +
    '    from OpenAIAuth.OpenAIAuth import OpenAIAuth, Debugger\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py", line 5, in <module>\n' +
    '    import tls_client\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/tls_client/__init__.py", line 15, in <module>\n' +
    '    from .sessions import Session\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/tls_client/sessions.py",

**Comment by fuergaosi233** [comment]
Are you using Docker for deployment?

**Comment by paything** [comment]
<img width="780" alt="image" src="https://user-images.githubusercontent.com/12410783/206859511-074d69bd-f4b2-4999-a6fb-f8e4a70e5066.png">
same problem

<img width="907" alt="image" src="https://user-images.githubusercontent.com/12410783/206859534-4dc421f6-63ee-4b7d-b06f-12d40b2eeb62.png">
maybe you can compatible arm64

**Comment by mikehu2016** [comment]
@fuergaosi233 yes, have used docker to deploy this image on Openwrt. 

架构	AArch64 Processor : Cortex-A53 * 4
固件版本	OpenWrt R22.11.18 (2022-11-18 21:03:24 by flippy) / LuCI Master (git-22.316.26068-65f106a)
内核版本	5.15.79-flippy-78+o
本地时间	Sat Dec 10 18:43:06 2022

**Comment by JingxinLee** [comment]
Same issue
