### ISSUE TITLE
uncaughtException GError: query must provide at least one key. current query is empty.

### ISSUE THREAD

**Issue by dockercore** [fuergaosi233/wechat-chatgpt#189]
uncaughtException GError: query must provide at least one key. current query is empty.
at PuppetWechat4u.contactQueryFilterFactory (file:///app/node_modules/wechaty-puppet/src/mixins/contact-mixin.ts:211:15)
at PuppetWechat4u.contactSearch (file:///app/node_modules/wechaty-puppet/src/mixins/contact-mixin.ts:136:65)
at runNextTicks (node:internal/process/task_queues:61:5)
at processImmediate (node:internal/timers:437:9)
at async Function.findAll (file:///app/node_modules/wechaty/src/user-modules/contact.ts:176:39)
at async Function.find (file:///app/node_modules/wechaty/src/user-modules/contact.ts:123:25)
at async PuppetWechat4u.<anonymous> (file:///app/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:345:33) {
code: 2,
details: 'Error: query must provide at least one key. current query is empty.\n' +
'    at PuppetWechat4u.contactQueryFilterFactory (file:///app/node_modules/wechaty-puppet/src/mixins/contact-mixin.ts:211:15)\n' +
'    at PuppetWechat4u.contactSearch (file:///app/node_modules/wechaty-puppet/src/mixins/contact-mixin.ts:136:65)\n' +
'    at runNextTicks (node:internal/process/task_queues:61:5)\n' +
'    at processImmediate (node:internal/timers:437:9)\n' +
'    at async Function.findAll (file:///app/node_modules/wechaty/src/user-modules/contact.ts:176:39)\n' +
'    at async Function.find (file:///app/node_modules/wechaty/src/user-modules/contact.ts:123:25)\n' +
'    at async PuppetWechat4u.<anonymous> (file:///app/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:345:33)'
}

**Comment by fuergaosi233** [comment]
Don't worry about that. That's Wechaty's problem.
