### ISSUE TITLE
help！！

### ISSUE THREAD

**Issue by paything** [fuergaosi233/wechat-chatgpt#195]
uncaughtException Error: Command failed with exit code 1: sh -c poetry run python3 src/generate_session.py 账号 密码
Traceback (most recent call last):
  File "/app/src/generate_session.py", line 45, in <module>
    from revChatGPT.revChatGPT import Chatbot
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 4, in <module>
    import tls_client
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/tls_client/__init__.py", line 15, in <module>
    from .sessions import Session
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/tls_client/sessions.py", line 1, in <module>
    from .cffi import request
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/tls_client/cffi.py", line 15, in <module>
    library = ctypes.cdll.LoadLibrary(f'{root_dir}/dependencies/tls-client{file_ext}')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ctypes/__init__.py", line 454, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/tls_client/dependencies/tls-client-amd64.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/src/generate_session.py", line 47, in <module>
    raise RuntimeError("Could import revChatGPT. Please install it first. You can run `poetry install` to install it.")
RuntimeError: Could import revChatGPT. Please install it first. You can run `poetry install` to install it.
    at makeError (file:///app/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///app/node_modules/execa/index.js:119:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ChatGPTPoole.getSessionToken (file:///app/src/chatgpt.ts:58:42)
    at async file:///app/src/chatgpt.ts:140:33
    at async Promise.all (index 0)
    at async ChatGPTPoole.startPools (file:///app/src/chatgpt.ts:136:26)
    at async ChatGPTBot.startGPTBot (file:///app/src/chatgpt.ts:233:5)
    at async WechatyImpl.<anonymous> (file:///app/src/main.ts:23:7) {
  shortMessage: 'Command failed with exit code 1: sh -c poetry run python3 src/generate_session.py 不给看',
  command: 'sh -c poetry run python3 src/generate_session.py 不给看',
  escapedCommand: 'sh -c "poetry run python3 src/generate_session.py 不给看"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'Traceback (most recent call last):\n' +
    '  File "/app/src/generate_session.py", line 45, in <module>\n' +
    '    from revChatGPT.revChatGPT import Chatbot\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 4, in <module>\n' +
    '    import tls_client\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/tls_client/__init__.py", line 15, in <module>\n' +
    '    from .sessions import Session\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/tls_client/sessions.py", line 1, in <module>\n' +
    '    from .cffi import request\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/tls_client/cffi.py", line 15, in <module>\n' +
    "    library = ctypes.cdll.LoadLibrary(f'{root_dir}/dependencies/tls-client{file_ext}')\n" +
    '              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n' +
    '  File "/usr/local/lib/python3.11/ctypes/__init__.py", line 454, in LoadLibrary\n' +
    '    return self._dlltype(name)\n' +
    '           ^^^^^^^^^^^^^^^^^^^\n' +
    '  File "/usr/local/lib/python3.11/ctypes/__init__.py", line 376, in __init__\n' +
    '    self._handle = _dlopen(self._name, mode)\n' +
    '                   ^^^^^^^^^^^^^^^^^^^^^^^^^\n' +
    'OSError: /root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/tls_client/dependencies/tls-client-amd64.so: cannot open shared object file: No such file or directory\n' +
    '\n' +
    'During handling of the above exception, another exception occurred:\n' +
    '\n' +
    'Traceback (most recent call last):\n' +
    '  File "/app/src/generate_session.py", line 47, in <module>\n' +
    '    raise RuntimeError("Could import revChatGPT. Please install it first. You can run `poetry install` to install it.")\n' +
    'RuntimeError: Could import revChatGPT. Please install it first. You can run `poetry install` to install it.',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

**Comment by RealTong** [comment]
「Could import revChatGPT. Please install it first. You can run `poetry install` to install it.」

**Comment by fuergaosi233** [comment]
Use Docker pls.
