### ISSUE TITLE
发了没几个有新的错误了呢

### ISSUE THREAD

**Issue by bbhxwl** [fuergaosi233/wechat-chatgpt#202]
Error: ⚠️ No chatgpt item in pool
    at ChatGPTPoole.getConversation (file:///app/src/chatgpt.ts:176:13)
    at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:188:35)
    at ChatGPTBot.getGPTMessage (file:///app/src/chatgpt.ts:253:35)
    at ChatGPTBot.onPrivateMessage (file:///app/src/chatgpt.ts:308:35)
    at ChatGPTBot.onMessage (file:///app/src/chatgpt.ts:334:27)
    at WechatyImpl.<anonymous> (file:///app/src/main.ts:32:26)
    at WechatyImpl.emit (node:events:513:28)
    at WechatyImpl.emit (node:domain:489:12)
    at WechatyImpl.emit (file:///app/node_modules/wechaty/src/wechaty-mixins/gerror-mixin.ts:44:22)
    at PuppetWechat4u.<anonymous> (file:///app/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:281:22)

**Comment by inannan423** [comment]
redeploy 一般能解决这个问题，或者再检查一下账号密码或 token 是否填写正确。请再详细描述出现的场景、搭建的环境。

**Comment by bbhxwl** [comment]
> redeploy 一般能解决这个问题，或者再检查一下账号密码或 token 是否填写正确。请再详细描述出现的场景、搭建的环境。

重新运行也这样了，现在是百分百出了。
🎯 Triggered ChatGPT: @斌斌智能 测试
Error: ⚠️ No chatgpt item in pool
    at ChatGPTPoole.getConversation (file:///app/src/chatgpt.ts:176:13)
    at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:188:35)
    at ChatGPTBot.getGPTMessage (file:///app/src/chatgpt.ts:253:35)
    at ChatGPTBot.onGroupMessage (file:///app/src/chatgpt.ts:318:35)
    at ChatGPTBot.onMessage (file:///app/src/chatgpt.ts:336:27)
    at WechatyImpl.<anonymous> (file:///app/src/main.ts:32:26)
    at WechatyImpl.emit (node:events:513:28)
    at WechatyImpl.emit (node:domain:489:12)
    at WechatyImpl.emit (file:///app/node_modules/wechaty/src/wechaty-mixins/gerror-mixin.ts:44:22)
    at PuppetWechat4u.<anonymous> (file:///app/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:281:22)

**Comment by inannan423** [comment]
有没有尝试过用 token 呢？

**Comment by 36ICE** [comment]
使用token可以用，我看了下代码，是OpenAI 的逆向工程 ChatGPT使用账号密码获取Token出现了问题

**Comment by inannan423** [comment]
> 
赞 可以提个 pr

**Comment by 36ICE** [comment]
Auto reply: * chuan dong has received your email and will reply to you as soon as possible. Thank you ~

**Comment by bbhxwl** [comment]
> 使用token可以用，我看了下代码，是OpenAI 的逆向工程 ChatGPT使用账号密码获取Token出现了问题

是不写账号密码空着，写session就行了么。不知道token是什么格式。

**Comment by inannan423** [comment]
是的，不写账号和密码，空着，可以看看文档里获取 token 的过程，token 是一个长字符串。
