### ISSUE TITLE
npm install && poetry install出了一大堆问题

### ISSUE THREAD

**Issue by TIMESTICKING** [fuergaosi233/wechat-chatgpt#206]
```
root@iZd394yzimg4n7Z:/media/wechat-chatgpt# npm install
loadDep:yaml → 304        ▐ ╢██████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:yaml → get        ▀ ╢██████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm ERR! Linux 4.15.0-48-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
npm ERR! Linux 4.15.0-48-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
npm ERR! Linux 4.15.0-48-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
npm ERR! Linux 4.15.0-48-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
npm ERR! Linux 4.15.0-48-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /media/wechat-chatgpt/npm-debug.log
```
npm-debug.log 长这样
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree
19 silly fetchNamedPackageData chatgpt
20 silly mapToRegistry name chatgpt
21 silly mapToRegistry using default registry
22 silly mapToRegistry registry https://registry.npmjs.org/
23 silly mapToRegistry uri https://registry.npmjs.org/chatgpt
24 silly fetchNamedPackageData dotenv
25 silly mapToRegistry name dotenv
26 silly mapToRegistry using default registry
27 silly mapToRegistry registry https://registry.npmjs.org/
28 silly mapToRegistry uri https://registry.npmjs.org/dotenv
29 silly fetchNamedPackageData execa
30 silly mapToRegistry name execa
31 silly mapToRegistry using default registry
32 silly mapToRegistry registry https://registry.npmjs.org/
33 silly mapToRegistry uri https://registry.npmjs.org/execa
34 silly fetchNamedPackageData qrcode
35 silly mapToRegistry name qrcode
36 silly mapToRegistry using default registry
37 silly mapToRegistry registry https://registry.npmjs.org/
38 silly mapToRegistry uri https://registry.npmjs.org/qrcode
39 silly fetchNamedPackageData uuid
40 silly mapToRegistry name uuid
41 silly mapToRegistry using default registry
42 silly mapToRegistry registry https://registry.npmjs.org/
43 silly mapToRegistry uri https://registry.npmjs.org/uuid
44 silly fetchNamedPackageData wechaty
45 silly mapToRegistry name wechaty
46 silly mapToRegistry using default registry
47 silly mapToRegistry registry https://registry.npmjs.org/
48 silly mapToRegistry uri https://registry.npmjs.org/wechaty
49 silly fetchNamedPackageData wechaty-puppet-wechat
50 silly mapToRegistry name wechaty-puppet-wechat
51 silly mapToRegistry using default registry
52 silly mapToRegistry registry https://registry.npmjs.org/
53 silly mapToRegistry uri https://registry.npmjs.org/wechaty-puppet-wechat
54 silly fetchNamedPackageData yaml
55 silly mapToRegistry name yaml
56 silly mapToRegistry using default registry
57 silly mapToRegistry registry https://registry.npmjs.org/
58 silly mapToRegistry uri https://registry.npmjs.org/yaml
59 verbose request uri https://registry.npmjs.org/chatgpt
60 verbose request no auth needed
61 info attempt registry request try #1 at 9:58:53 PM
62 verbose request id 9506ded978ef800d
63 verbose etag W/"e77d78465827b454a2ad302527f20da5"
64 verbose lastModified Thu, 08 Dec 2022 09:08:45 GMT
65 http request GET https://registry.npmjs.org/chatgpt
66 verbose request uri https://registry.npmjs.org/dotenv
67 verbose request no auth needed
68 info attempt registry request try #1 at 9:58:53 PM
69 verbose etag W/"75fcf7b500e492deb917633cdd9b4a92"
70 verbose lastModified Sun, 13 Nov 2022 06:08:12 GMT
71 http request GET https://registry.npmjs.org/dotenv
72 verbose request uri https://registry.npmjs.org/execa
73 verbose request no auth needed
74 info attempt registry request try #1 at 9:58:53 PM
75 verbose etag W/"59405a76a06d26a1938114a2d22d7935"
76 verbose lastModified Tue, 22 Nov 2022 08:46:28 GMT
77 http request GET https://registry.npmjs.org/execa
78 verbose request uri https://registry.npmjs.org/qrcode
79 verbose request no auth needed
80 info attempt registry request try #1 at 9:58:53 PM
81 verbose etag W/"23541bfd13e34d04e95816caf9178e4e"
82 verbose lastModified Wed, 13 Jul 2022 21:23:33 GMT
83 http request GET https://registry.npmjs.org/qrcode
84 verbose request uri https://registry.npmjs.org/uuid
85 verbose request no auth needed
86 info attempt registry request try #1 at 9:58:53 PM
87 verbose etag W/"51944bd05278f8d4198295003d8201d3"
88 verbose lastModified Sun, 11 Sep 2022 03:37:13 GMT
89 http request GET https://registry.npmjs.org/uuid
90 verbose request uri https://registry.npmjs.org/wechaty-puppet-wechat
91 verbose request no auth needed
92 info attempt registry request try #1 at 9:58:53 PM
93 verbose etag W/"27afe6308709c0c87dfd6402e71dd9ca"
94 verbose lastModified Thu, 14 Jul 2022 03:47:46 GMT
95 http request GET https://registry.npmjs.org/wechaty-puppet-wechat
96 verbose request uri https://registry.npmjs.org/yaml
97 verbose request no auth needed
98 info attempt registry request try #1 at 9:58:53 PM
99 verbose etag W/"35a08aad1927221684e39b59865883ca"
100 verbose lastModified Wed, 05 Oct 2022 07:32:19 GMT
101 http request GET https://registry.npmjs.org/yaml
102 verbose request uri https://registry.npmjs.org/wechaty
103 verbose request no auth needed
104 info attempt registry request try #1 at 9:58:53 PM
105 verbose etag W/"daf115eb23b1987739e6c6109e0c17a5"
106 verbose lastModified Wed, 29 Jun 2022 00:45:21 GMT
107 http request GET https://registry.npmjs.org/wechaty
108 http 304 https://registry.npmjs.org/uuid
109 verbose headers { date: 'Sat, 10 Dec 2022 13:58:54 GMT',
109 verbose headers   connection: 'keep-alive',
109 verbose headers   'cf-ray': '77767f7edb0e9e59-SJC',
109 verbose headers   age: '43',
109 verbose headers   'cache-control': 'public, max-age=300',
109 verbose headers   etag: '"51944bd05278f8d4198295003d8201d3"',
109 verbose headers   'last-modified': 'Sun, 11 Sep 2022 03:37:13 GMT',
109 verbose headers   vary: 'Accept-Encoding',
109 verbose headers   'cf-cache-status': 'HIT',
109 verbose headers   'x-amz-replication-status': 'PENDING',
109 verbose headers   server: 'cloudflare' }
110 silly get cb [ 304,
110 silly get   { date: 'Sat, 10 Dec 2022 13:58:54 GMT',
110 silly get     connection: 'keep-alive',
110 silly get     'cf-ray': '77767f7edb0e9e59-SJC',
110 silly get     age: '43',
110 silly get     'cache-control': 'public, max-age=300',
110 silly get     etag: '"51944bd05278f8d4198295003d8201d3"',
110 silly get     'last-modified': 'Sun, 11 Sep 2022 03:37:13 GMT',
110 silly get     vary: 'Accept-Encoding',
110 silly get     'cf-cache-status': 'HIT',
110 silly get     'x-amz-replication-status': 'PENDING',
110 silly get     server: 'cloudflare' } ]
111 verbose etag https://registry.npmjs.org/uuid from cache
112 verbose get saving uuid to /root/.npm/registry.npmjs.org/uuid/.cache.json
113 silly resolveWithNewModule uuid@9.0.0 checking installable status
114 silly cache add args [ 'uuid@^9.0.0', null ]
115 verbose cache add spec uuid@^9.0.0
116 silly cache add parsed spec Result {
116 silly cache add   raw: 'uuid@^9.0.0',
116 silly cache add   scope: null,
116 silly cache add   name: 'uuid',
116 silly cache add   rawSpec: '^9.0.0',
116 silly cache add   spec: '>=9.0.0 <10.0.0',
116 silly cache add   type: 'range' }
117 silly addNamed uuid@>=9.0.0 <10.0.0
118 verbose addNamed ">=9.0.0 <10.0.0" is a valid semver range for uuid
119 silly addNameRange { name: 'uuid', range: '>=9.0.0 <10.0.0', hasData: false }
120 silly mapToRegistry name uuid
121 silly mapToRegistry using default registry
122 silly mapToRegistry registry https://registry.npmjs.org/
123 silly mapToRegistry uri https://registry.npmjs.org/uuid
124 verbose addNameRange registry:https://registry.npmjs.org/uuid not in flight; fetching
125 http 304 https://registry.npmjs.org/qrcode
126 verbose headers { date: 'Sat, 10 Dec 2022 13:58:54 GMT',
126 verbose headers   connection: 'keep-alive',
126 verbose headers   'cf-ray': '77767f7e3d57cec1-SJC',
126 verbose headers   'cache-control': 'public, max-age=300',
126 verbose headers   etag: '"23541bfd13e34d04e95816caf9178e4e"',
126 verbose headers   'last-modified': 'Wed, 13 Jul 2022 21:23:33 GMT',
126 verbose headers   vary: 'Accept-Encoding',
126 verbose headers   'cf-cache-status': 'REVALIDATED',
126 verbose headers   'x-amz-replication-status': 'COMPLETED',
126 verbose headers   server: 'cloudflare' }
127 silly get cb [ 304,
127 silly get   { date: 'Sat, 10 Dec 2022 13:58:54 GMT',
127 silly get     connection: 'keep-alive',
127 silly get     'cf-ray': '77767f7e3d57cec1-SJC',
127 silly get     'cache-control': 'public, max-age=300',
127 silly get     etag: '"23541bfd13e34d04e95816caf9178e4e"',
127 silly get     'last-modified': 'Wed, 13 Jul 2022 21:23:33 GMT',
127 silly get     vary: 'Accept-Encoding',
127 silly get     'cf-cache-status': 'REVALIDATED',
127 silly get     'x-amz-replication-status': 'COMPLETED',
127 silly get     server: 'cloudflare' } ]
128 verbose etag https://registry.npmjs.org/qrcode from cache
129 verbose get saving qrcode to /root/.npm/registry.npmjs.org/qrcode/.cache.json
130 verbose get https://registry.npmjs.org/uuid not expired, no request
131 silly addNameRange number 2 { name: 'uuid', range: '>=9.0.0 <10.0.0', hasData: true }
132 silly addNameRange versions [ 'uuid',
132 silly addNameRange   [ '0.0.1',
132 silly addNameRange     '0.0.2',
132 silly addNameRange     '1.4.0',
132 silly addNameRange     '1.4.1',
132 silly addNameRange     '1.4.2',
132 silly addNameRange     '2.0.0',
132 silly addNameRange     '2.0.1',
132 silly addNameRange     '2.0.2',
132 silly addNameRange     '2.0.3',
132 silly addNameRange     '3.0.0',
132 silly addNameRange     '3.0.1',
132 silly addNameRange     '3.1.0',
132 silly addNameRange     '3.2.0',
132 silly addNameRange     '3.2.1',
132 silly addNameRange     '3.3.0',
132 silly addNameRange     '3.3.2',
132 silly addNameRange     '3.3.3',
132 silly addNameRange     '3.4.0',
132 silly addNameRange     '7.0.0-beta.0',
132 silly addNameRange     '7.0.0',
132 silly addNameRange     '7.0.1',
132 silly addNameRange     '7.0.2-beta.0',
132 silly addNameRange     '7.0.2',
132 silly addNameRange     '7.0.3',
132 silly addNameRange     '8.0.0-beta.0',
132 silly addNameRange     '8.0.0',
132 silly addNameRange     '8.1.0',
132 silly addNameRange     '8.2.0-beta.0',
132 silly addNameRange     '8.2.0',
132 silly addNameRange     '8.3.0-beta.0',
132 silly addNameRange     '8.3.0',
132 silly addNameRange     '8.3.1',
132 silly addNameRange     '8.3.2-beta.0',
132 silly addNameRange     '8.3.2',
132 silly addNameRange     '9.0.0-beta.0',
132 silly addNameRange     '9.0.0' ] ]
133 silly addNamed uuid@9.0.0
134 verbose addNamed "9.0.0" is a plain semver version for uuid
135 silly resolveWithNewModule qrcode@1.5.1 checking installable status
136 silly cache add args [ 'qrcode@^1.5.1', null ]
137 verbose cache add spec qrcode@^1.5.1
138 silly cache add parsed spec Result {
138 silly cache add   raw: 'qrcode@^1.5.1',
138 silly cache add   scope: null,
138 silly cache add   name: 'qrcode',
138 silly cache add   rawSpec: '^1.5.1',
138 silly cache add   spec: '>=1.5.1 <2.0.0',
138 silly cache add   type: 'range' }
139 silly addNamed qrcode@>=1.5.1 <2.0.0
140 verbose addNamed ">=1.5.1 <2.0.0" is a valid semver range for qrcode
141 silly addNameRange { name: 'qrcode', range: '>=1.5.1 <2.0.0', hasData: false }
142 silly mapToRegistry name qrcode
143 silly mapToRegistry using default registry
144 silly mapToRegistry registry https://registry.npmjs.org/
145 silly mapToRegistry uri https://registry.npmjs.org/qrcode
146 verbose addNameRange registry:https://registry.npmjs.org/qrcode not in flight; fetching
147 silly cache afterAdd uuid@9.0.0
148 verbose afterAdd /root/.npm/uuid/9.0.0/package/package.json not in flight; writing
149 verbose get https://registry.npmjs.org/qrcode not expired, no request
150 silly addNameRange number 2 { name: 'qrcode', range: '>=1.5.1 <2.0.0', hasData: true }
151 silly addNameRange versions [ 'qrcode',
151 silly addNameRange   [ '0.0.1',
151 silly addNameRange     '0.0.2',
151 silly addNameRange     '0.0.3',
151 silly addNameRange     '0.1.0',
151 silly addNameRange     '0.1.1',
151 silly addNameRange     '0.2.2',
151 silly addNameRange     '0.2.3',
151 silly addNameRange     '0.2.4',
151 silly addNameRange     '0.2.5',
151 silly addNameRange     '0.2.6',
151 silly addNameRange     '0.2.7',
151 silly addNameRange     '0.2.8',
151 silly addNameRange     '0.2.9',
151 silly addNameRange     '0.2.10',
151 silly addNameRange     '0.2.11',
151 silly addNameRange     '0.2.12',
151 silly addNameRange     '0.3.0',
151 silly addNameRange     '0.3.1',
151 silly addNameRange     '0.4.0',
151 silly addNameRange     '0.4.1',
151 silly addNameRange     '0.4.2',
151 silly addNameRange     '0.4.4',
151 silly addNameRange     '0.5.0',
151 silly addNameRange     '0.6.0',
151 silly addNameRange     '0.7.0',
151 silly addNameRange     '0.7.1',
151 silly addNameRange     '0.8.0',
151 silly addNameRange     '0.8.1',
151 silly addNameRange     '0.8.2',
151 silly addNameRange     '0.9.0',
151 silly addNameRange     '1.0.0',
151 silly addNameRange     '1.0.1',
151 silly addNameRange     '1.1.0',
151 silly addNameRange     '1.2.0',
151 silly addNameRange     '1.2.2',
151 silly addNameRange     '1.3.0',
151 silly addNameRange     '1.3.1',
151 silly addNameRange     '1.3.2',
151 silly addNameRange     '1.3.3',
151 silly addNameRange     '1.3.4',
151 silly addNameRange     '1.4.0',
151 silly addNameRange     '1.4.1',
151 silly addNameRange     '1.4.2',
151 silly addNameRange     '1.4.3',
151 silly addNameRange     '1.4.4',
151 silly addNameRange     '1.5.0',
151 silly addNameRange     '1.5.1' ] ]
152 silly addNamed qrcode@1.5.1
153 verbose addNamed "1.5.1" is a plain semver version for qrcode
154 verbose afterAdd /root/.npm/uuid/9.0.0/package/package.json written
155 silly cache afterAdd qrcode@1.5.1
156 verbose afterAdd /root/.npm/qrcode/1.5.1/package/package.json not in flight; writing
157 verbose afterAdd /root/.npm/qrcode/1.5.1/package/package.json written
158 http 304 https://registry.npmjs.org/dotenv
159 verbose headers { date: 'Sat, 10 Dec 2022 13:58:54 GMT',
159 verbose headers   connection: 'keep-alive',
159 verbose headers   'cf-ray': '77767f7eedaf9e56-SJC',
159 verbose headers   'cache-control': 'public, max-age=300',
159 verbose headers   etag: '"75fcf7b500e492deb917633cdd9b4a92"',
159 verbose headers   'last-modified': 'Sun, 13 Nov 2022 06:08:12 GMT',
159 verbose headers   vary: 'Accept-Encoding',
159 verbose headers   'cf-cache-status': 'REVALIDATED',
159 verbose headers   'x-amz-replication-status': 'COMPLETED',
159 verbose headers   server: 'cloudflare' }
160 silly get cb [ 304,
160 silly get   { date: 'Sat, 10 Dec 2022 13:58:54 GMT',
160 silly get     connection: 'keep-alive',
160 silly get     'cf-ray': '77767f7eedaf9e56-SJC',
160 silly get     'cache-control': 'public, max-age=300',
160 silly get     etag: '"75fcf7b500e492deb917633cdd9b4a92"',
160 silly get     'last-modified': 'Sun, 13 Nov 2022 06:08:12 GMT',
160 silly get     vary: 'Accept-Encoding',
160 silly get     'cf-cache-status': 'REVALIDATED',
160 silly get     'x-amz-replication-status': 'COMPLETED',
160 silly get     server: 'cloudflare' } ]
161 verbose etag https://registry.npmjs.org/dotenv from cache
162 verbose get saving dotenv to /root/.npm/registry.npmjs.org/dotenv/.cache.json
163 http 304 https://registry.npmjs.org/chatgpt
164 verbose headers { date: 'Sat, 10 Dec 2022 13:58:54 GMT',
164 verbose headers   connection: 'keep-alive',
164 verbose headers   'cf-ray': '77767f7ee983fade-SJC',
164 verbose headers   'cache-control': 'public, max-age=300',
164 verbose headers   etag: '"e77d78465827b454a2ad302527f20da5"',
164 verbose headers   'last-modified': 'Thu, 08 Dec 2022 09:08:45 GMT',
164 verbose headers   vary: 'Accept-Encoding',
164 verbose headers   'cf-cache-status': 'REVALIDATED',
164 verbose headers   'x-amz-replication-status': 'COMPLETED',
164 verbose headers   server: 'cloudflare' }
165 silly get cb [ 304,
165 silly get   { date: 'Sat, 10 Dec 2022 13:58:54 GMT',
165 silly get     connection: 'keep-alive',
165 silly get     'cf-ray': '77767f7ee983fade-SJC',
165 silly get     'cache-control': 'public, max-age=300',
165 silly get     etag: '"e77d78465827b454a2ad302527f20da5"',
165 silly get     'last-modified': 'Thu, 08 Dec 2022 09:08:45 GMT',
165 silly get     vary: 'Accept-Encoding',
165 silly get     'cf-cache-status': 'REVALIDATED',
165 silly get     'x-amz-replication-status': 'COMPLETED',
165 silly get     server: 'cloudflare' } ]
166 verbose etag https://registry.npmjs.org/chatgpt from cache
167 verbose get saving chatgpt to /root/.npm/registry.npmjs.org/chatgpt/.cache.json
168 silly resolveWithNewModule dotenv@16.0.3 checking installable status
169 silly cache add args [ 'dotenv@^16.0.3', null ]
170 verbose cache add spec dotenv@^16.0.3
171 silly cache add parsed spec Result {
171 silly cache add   raw: 'dotenv@^16.0.3',
171 silly cache add   scope: null,
171 silly cache add   name: 'dotenv',
171 silly cache add   rawSpec: '^16.0.3',
171 silly cache add   spec: '>=16.0.3 <17.0.0',
171 silly cache add   type: 'range' }
172 silly addNamed dotenv@>=16.0.3 <17.0.0
173 verbose addNamed ">=16.0.3 <17.0.0" is a valid semver range for dotenv
174 silly addNameRange { name: 'dotenv', range: '>=16.0.3 <17.0.0', hasData: false }
175 silly mapToRegistry name dotenv
176 silly mapToRegistry using default registry
177 silly mapToRegistry registry https://registry.npmjs.org/
178 silly mapToRegistry uri https://registry.npmjs.org/dotenv
179 verbose addNameRange registry:https://registry.npmjs.org/dotenv not in flight; fetching
180 verbose stack Error: Missing required argument #1
180 verbose stack     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
180 verbose stack     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
180 verbose stack     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
180 verbose stack     at /usr/share/npm/lib/install/deps.js:457:7
180 verbose stack     at /usr/share/npm/node_modules/iferr/index.js:13:50
180 verbose stack     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
180 verbose stack     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
180 verbose stack     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
180 verbose stack     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
180 verbose stack     at /usr/share/npm/node_modules/iferr/index.js:13:50
181 verbose cwd /media/wechat-chatgpt
182 error Linux 4.15.0-48-generic
183 error argv "/usr/bin/node" "/usr/bin/npm" "install"
184 error node v8.10.0
185 error npm  v3.5.2
186 error code EMISSINGARG
187 error typeerror Error: Missing required argument #1
187 error typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
187 error typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
187 error typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
187 error typeerror     at /usr/share/npm/lib/install/deps.js:457:7
187 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
187 error typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
187 error typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
187 error typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
187 error typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
187 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
188 error typeerror This is an error with npm itself. Please report this error at:
188 error typeerror     <http://github.com/npm/npm/issues>
189 verbose exit [ 1, true ]
```

**Comment by fuergaosi233** [comment]
Use docker pls
