### ISSUE TITLE
Error: ⚠️ No chatgpt item in pool

### ISSUE THREAD

**Issue by YuXinFan** [fuergaosi233/wechat-chatgpt#210]
```
User Contact<WeChatBot> logged in
Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"fxxxxn"},{"password":"xxxxxxxx"},{"session_token":"session_token"}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":""}
ChatGPTPools: `1`
🤖️ Start GPT Bot Success, ready to handle message!
Message: Message#Text[🗣Contact<我>]     你好
🎯 Triggered ChatGPT: 你好
Error: ⚠️ No chatgpt item in pool
    at ChatGPTPoole.getConversation (file:///app/src/chatgpt.ts:176:13)
    at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:188:35)
    at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:197:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ChatGPTBot.getGPTMessage (file:///app/src/chatgpt.ts:253:12)
    at async ChatGPTBot.onPrivateMessage (file:///app/src/chatgpt.ts:308:24)
    at async ChatGPTBot.onMessage (file:///app/src/chatgpt.ts:334:16)
    at async WechatyImpl.<anonymous> (file:///app/src/main.ts:32:9)
```

**Comment by inannan423** [comment]
上面显示登陆成功，这个问题貌似不会影响使用。如果影响使用，redeploy 一般能解决这个问题，或者再检查一下账号密码或 token 是否填写正确。

**Comment by kun4399** [comment]
是不是配置文件没有按照格式写对

**Comment by koffuxu** [comment]
刚开始能正常使用，用着用着就不行了。提示这个错误

**Comment by lanyucomputer** [comment]
Error: ⚠️ No chatgpt item in pool
    at ChatGPTPoole.getConversation (file:///app/src/chatgpt.ts:176:13)
    at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:188:35)
    at ChatGPTBot.getGPTMessage (file:///app/src/chatgpt.ts:253:35)
    at ChatGPTBot.onPrivateMessage (file:///app/src/chatgpt.ts:308:35)
    at ChatGPTBot.onMessage (file:///app/src/chatgpt.ts:334:27)
    at WechatyImpl.<anonymous> (file:///app/src/main.ts:32:26)
    at WechatyImpl.emit (node:events:513:28)
    at WechatyImpl.emit (node:domain:489:12)
    at WechatyImpl.emit (file:///app/node_modules/wechaty/src/wechaty-mixins/gerror-mixin.ts:44:22)
    at PuppetWechat4u.<anonymous> (file:///app/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:281:22)

**Comment by Svision** [comment]
🎯 Triggered ChatGPT: hello
Error: ⚠️ No chatgpt item in pool
at ChatGPTPoole.getConversation (file:///app/src/chatgpt.ts:196:13)
at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:215:35)
at ChatGPTBot.getGPTMessage (file:///app/src/chatgpt.ts:280:35)
at ChatGPTBot.onPrivateMessage (file:///app/src/chatgpt.ts:335:35)
at ChatGPTBot.onMessage (file:///app/src/chatgpt.ts:361:27)
at WechatyImpl.<anonymous> (file:///app/src/main.ts:32:26)
at WechatyImpl.emit (node:events:513:28)
at WechatyImpl.emit (node:domain:489:12)
at WechatyImpl.emit (file:///app/node_modules/wechaty/src/wechaty-mixins/gerror-mixin.ts:44:22)
at PuppetWechat4u.<anonymous> (file:///app/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:281:22)

**Comment by kongyong16** [comment]
我也是同样的问题，上午还好用，中午就出现了一样的问题
Message: Message#Text[🗣Contact<H. Wang>]       Eva，你好
🎯 Triggered ChatGPT: Eva，你好
Error: ⚠️ No chatgpt item in pool
    at ChatGPTPoole.getConversation (file:///app/src/chatgpt.ts:176:13)

**Comment by kongyong16** [comment]
我今天也遇到到了这个问题。我使用Nas里的docker运行GPT。我重新更换为非国内节点，重启docker容器，恢复使用。

**Comment by yaje0008** [comment]
我也遇到了这个问题，用的是Railway.app环境部署。由于没有加chatPrivateTiggerKeyword参数造成的，加上去就可以了

**Comment by cgddgc** [comment]
这个是因为多次登录了，所以登录的时候有验证码了，换成token没问题，可以下次再用账号密码登录

**Comment by inannan423** [comment]
经测试，token 可能会过期，然后出现上述报错，这时需要刷新 chatGPT 官网，重新获得 token 填入配置文件然后 redeploy 。

**Comment by YuXinFan** [comment]
加上token可以解决

**Comment by hackhy2020** [comment]
分享下我的看法。。我用的是token但是会有时间限制，到时间需要你登陆chatgpt官网再获取，然后去服务器更新一下最新的。
我暂时没使用账号密码登录。
注意事项，当你使用微信小号登录的时候。登陆了不能退出，要挂在手机后台。安卓可以多开微信不用担心。

**Comment by qwweerdf** [comment]
> 这个是因为多次登录了，所以登录的时候有验证码了，换成token没问题，可以下次再用账号密码登录

用token还是出错

**Comment by linkboy2007** [comment]
用token还是出错

**Comment by cgddgc** [comment]
> 用token还是出错

用token是不是没有删除账号和密码，如果不是的话可以再看下往前的提示，都有具体原因的

**Comment by goxofy** [comment]
这个24小时基本就没法搞。。。

**Comment by linkboy2007** [comment]
> > 用token还是出错
> 
> 用token是不是没有删除账号和密码，如果不是的话可以再看下往前的提示，都有具体原因的

用的railway的配置，删除了账号密码。一样说pool里面没有。 


你现在什么方式，怎么部署的。

**Comment by goxofy** [comment]
一直提示，不管如何更新token

**Comment by Lukangkang123** [comment]
我无论是用账号密码，还是用更新后的token，都是报这个错。用了一天还好好着呢，突然就不行了

**Comment by hfhfn** [comment]
> 我无论是用账号密码，还是用更新后的token，都是报这个错。用了一天还好好着呢，突然就不行了

同样的问题,用了一天好好的,就再也不行了

**Comment by siXence** [comment]
这个问题有人解决了吗

**Comment by Lukangkang123** [comment]
> 

我看了下，我感觉是token不对，因为每次刷新token都不一样。而且用一个错的token,它也这么报错

**Comment by protectione055** [comment]
现在在浏览器每次刷新都要验证是不是人类，token以后应该用不了了

**Comment by jpfree** [comment]
一样的问题。。。都是对的

**Comment by Crabor** [comment]
2022.12.12日这个问题貌似又重复出现了，昨晚还好好的。应该是session不得行了

**Comment by fuergaosi233** [comment]
Antibot has been added to OpenAI.  😅
I need to find out how to bypass Antibot.

**Comment by xiongjiamu** [comment]
> Antibot has been added to OpenAI. 😅 I need to find out how to bypass Antibot.

https://github.com/transitive-bullshit/chatgpt-api#update-december-11-2022 is this helpful?

**Comment by Lukangkang123** [comment]
> > Antibot has been added to OpenAI. 😅 I need to find out how to bypass Antibot.
> 
> https://github.com/transitive-bullshit/chatgpt-api#update-december-11-2022 is this helpful?

"Cloudflare cf_clearance tokens expire after 2 hours, so right now you'll **have to manually log in and extract it by hand every so often**"

**Comment by fuergaosi233** [comment]
https://github.com/fuergaosi233/wechat-chatgpt/pull/313

**Comment by coderyiyang** [comment]
> Antibot has been added to OpenAI. 😅 I need to find out how to bypass Antibot.

openai chatgpt has API key, does this make any sense?

**Comment by YuXinFan** [comment]
openai加了反机器人验证，凉了，大家散了吧

**Comment by r90tpass** [comment]
如果是验证码的话 ，github有个裤子叫ddddddorc的验证码绕过。可以使用

**Comment by Svip9** [comment]
No chatgpt item in pool  有解决方案了吗？

**Comment by jiamsu** [comment]
所以这个问题无解吗？

**Comment by lightumcc** [comment]
我刚刚仍然遇到了这个问题，换了很多地方的vps都没用

**Comment by Lukangkang123** [comment]
> 所以这个问题无解吗？

可以用官方提供的API,不过效果可能会差点且是付费的。

**Comment by RealTong** [comment]
> 如果是验证码的话 ，github有个裤子叫ddddddorc的验证码绕过。可以使用
Hi,你好👋，可以给个repo地址吗。在google github 搜索之后没有找到呀
