### ISSUE TITLE
您好，请问win10本机部署，拉取镜像后启动时报这个错是什么原因？

### ISSUE THREAD

**Issue by szhclear** [fuergaosi233/wechat-chatgpt#213]
2022-12-10 23:10:01 npm ERR! path /app
2022-12-10 23:10:01 npm ERR! command failed
2022-12-10 23:10:01 npm ERR! signal SIGTERM
2022-12-10 23:10:01 npm ERR! command sh -c -- nodemon --exec node --watch config.yaml --loader ts-node/esm src/main.ts
2022-12-10 23:10:01 
2022-12-10 23:10:01 npm ERR! A complete log of this run can be found in:
2022-12-10 23:10:01 npm ERR!     /root/.npm/_logs/2022-12-10T15_04_44_306Z-debug-0.log
2022-12-10 23:10:02 
2022-12-10 23:10:02 > wechat-chatgpt@1.0.0 dev
2022-12-10 23:10:02 > nodemon --exec node --watch config.yaml --loader ts-node/esm src/main.ts
2022-12-10 23:10:02 
2022-12-10 23:10:02 [nodemon] 2.0.20
2022-12-10 23:10:02 [nodemon] to restart at any time, enter `rs`
2022-12-10 23:10:02 [nodemon] watching path(s): config.yaml
2022-12-10 23:10:02 [nodemon] watching extensions: ts
2022-12-10 23:10:02 [nodemon] starting `node --loader ts-node/esm src/main.ts`
2022-12-10 23:10:02 (node:32) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
2022-12-10 23:10:02 (Use `node --trace-warnings ...` to show where the warning was created)
2022-12-10 23:10:15 uncaughtException GError: getaddrinfo EAI_AGAIN login.wx.qq.com
2022-12-10 23:10:15     at Function.AxiosError.from (/app/node_modules/axios/lib/core/AxiosError.js:89:14)
2022-12-10 23:10:15     at RedirectableRequest.handleRequestError (/app/node_modules/axios/lib/adapters/http.js:518:25)
2022-12-10 23:10:15     at RedirectableRequest.emit (node:events:525:35)
2022-12-10 23:10:15     at RedirectableRequest.emit (node:domain:489:12)
2022-12-10 23:10:15     at ClientRequest.eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:14:24)
2022-12-10 23:10:15     at ClientRequest.emit (node:events:513:28)
2022-12-10 23:10:15     at ClientRequest.emit (node:domain:489:12)
2022-12-10 23:10:15     at TLSSocket.socketErrorListener (node:_http_client:494:9)
2022-12-10 23:10:15     at TLSSocket.emit (node:events:513:28)
2022-12-10 23:10:15     at TLSSocket.emit (node:domain:489:12) {
2022-12-10 23:10:15   code: 2,
2022-12-10 23:10:15   details: 'Error: getaddrinfo EAI_AGAIN login.wx.qq.com\n' +
2022-12-10 23:10:15     '    at Function.AxiosError.from (/app/node_modules/axios/lib/core/AxiosError.js:89:14)\n' +
2022-12-10 23:10:15     '    at RedirectableRequest.handleRequestError (/app/node_modules/axios/lib/adapters/http.js:518:25)\n' +
2022-12-10 23:10:15     '    at RedirectableRequest.emit (node:events:525:35)\n' +
2022-12-10 23:10:15     '    at RedirectableRequest.emit (node:domain:489:12)\n' +
2022-12-10 23:10:15     '    at ClientRequest.eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:14:24)\n' +
2022-12-10 23:10:15     '    at ClientRequest.emit (node:events:513:28)\n' +
2022-12-10 23:10:15     '    at ClientRequest.emit (node:domain:489:12)\n' +
2022-12-10 23:10:15     '    at TLSSocket.socketErrorListener (node:_http_client:494:9)\n' +
2022-12-10 23:10:15     '    at TLSSocket.emit (node:events:513:28)\n' +
2022-12-10 23:10:15     '    at TLSSocket.emit (node:domain:489:12)'
2022-12-10 23:10:15 }

**Comment by fuergaosi233** [comment]
Please check your DNS configuration. 🤔

**Comment by fuergaosi233** [comment]
https://github.com/fuergaosi233/wechat-chatgpt/issues/180
