### ISSUE TITLE
error.response.headers['set-cookie'] 开始报这个错误

### ISSUE THREAD

**Issue by basying** [fuergaosi233/wechat-chatgpt#222]
爆出error.response.headers['set-cookie'] 
但后面有启动 GPT Bot Success，准备处理消息！
却无法返回消息

**Comment by hua-hua666** [comment]
同样是这个问题

**Comment by hua-hua666** [comment]
登陆之后同样是报这个问题
但我这边收到消息后报这个错
Error: ⚠️ No chatgpt item in pool
at ChatGPTPoole.getConversation (file:///app/src/chatgpt.ts:196:13)
at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:215:35)
at ChatGPTBot.getGPTMessage (file:///app/src/chatgpt.ts:280:35)
at ChatGPTBot.onPrivateMessage (file:///app/src/chatgpt.ts:335:35)
at ChatGPTBot.onMessage (file:///app/src/chatgpt.ts:361:27)
at WechatyImpl.<anonymous> (file:///app/src/main.ts:32:26)
at WechatyImpl.emit (node:events:513:28)
at WechatyImpl.emit (node:domain:489:12)
at WechatyImpl.emit (file:///app/node_modules/wechaty/src/wechaty-mixins/gerror-mixin.ts:44:22)
at PuppetWechat4u.<anonymous> (file:///app/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:281:22)

**Comment by basying** [comment]
> 



> 经过测试这个报错不影响使用
> 我将账号密码登录换成token登录后可以正常使用
> error.response.headers['set-cookie'] 报错还在
> 但是Error: ⚠️ No chatgpt item in pool
> 报错消失了，功能也可以正常使用

我账号密码登录的，但是没⚠️ No chatgpt item in pool这个错，不能正常使用，没有回复

**Comment by Carlingwang** [comment]
同一个错误两个账号池，一个token一个账号，error.response.headers['set-cookie'] 报错,Error: ⚠️ No chatgpt item in pool也在。

**Comment by Carlingwang** [comment]
ge

> 同一个错误两个账号池，一个token一个账号，error.response.headers['set-cookie'] 报错,Error: ⚠️ No chatgpt item in pool也在。

更换token也不行

**Comment by wanna1114** [comment]
> 

我也是这个样子请问解决的了吗
