### ISSUE TITLE
连接后过段时间断开连接

### ISSUE THREAD

**Issue by ekkoamb** [fuergaosi233/wechat-chatgpt#231]
uncaughtException GError: getaddrinfo EAI_AGAIN webpush.wx.qq.com
2022-12-11 12:10:54     at Function.AxiosError.from (/app/node_modules/axios/lib/core/AxiosError.js:89:14)
2022-12-11 12:10:54     at RedirectableRequest.handleRequestError (/app/node_modules/axios/lib/adapters/http.js:518:25)
2022-12-11 12:10:54     at RedirectableRequest.emit (node:events:525:35)
2022-12-11 12:10:54     at RedirectableRequest.emit (node:domain:489:12)
2022-12-11 12:10:54     at ClientRequest.eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:14:24)
2022-12-11 12:10:54     at ClientRequest.emit (node:events:513:28)
2022-12-11 12:10:54     at ClientRequest.emit (node:domain:489:12)
2022-12-11 12:10:54     at TLSSocket.socketErrorListener (node:_http_client:494:9)
2022-12-11 12:10:54     at TLSSocket.emit (node:events:513:28)
2022-12-11 12:10:54     at TLSSocket.emit (node:domain:489:12) {
2022-12-11 12:10:54   code: 2,
2022-12-11 12:10:54   details: 'Error: getaddrinfo EAI_AGAIN webpush.wx.qq.com\n' +
2022-12-11 12:10:54     '    at Function.AxiosError.from (/app/node_modules/axios/lib/core/AxiosError.js:89:14)\n' +
2022-12-11 12:10:54     '    at RedirectableRequest.handleRequestError (/app/node_modules/axios/lib/adapters/http.js:518:25)\n' +
2022-12-11 12:10:54     '    at RedirectableRequest.emit (node:events:525:35)\n' +
2022-12-11 12:10:54     '    at RedirectableRequest.emit (node:domain:489:12)\n' +
2022-12-11 12:10:54     '    at ClientRequest.eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:14:24)\n' +
2022-12-11 12:10:54     '    at ClientRequest.emit (node:events:513:28)\n' +
2022-12-11 12:10:54     '    at ClientRequest.emit (node:domain:489:12)\n' +
2022-12-11 12:10:54     '    at TLSSocket.socketErrorListener (node:_http_client:494:9)\n' +
2022-12-11 12:10:54     '    at TLSSocket.emit (node:events:513:28)\n' +
2022-12-11 12:10:54     '    at TLSSocket.emit (node:domain:489:12)'
2022-12-11 12:10:54 }
2022-12-11 12:11:44 04:11:44 WARN PuppetWatchdogAgent start() reset() reason: {"data":"syncCheck()","timeoutMilliseconds":60000}
2022-12-11 12:11:44 uncaughtException GError: WatchdogAgent reset: lastFood: "{"data":"syncCheck()","timeoutMilliseconds":60000}"
2022-12-11 12:11:44     at Watchdog.reset (file:///app/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)
2022-12-11 12:11:44     at Watchdog.emit (node:events:513:28)
2022-12-11 12:11:44     at Watchdog.emit (node:domain:489:12)
2022-12-11 12:11:44     at Timeout._onTimeout (file:///app/node_modules/watchdog/src/watchdog.ts:115:12)
2022-12-11 12:11:44     at listOnTimeout (node:internal/timers:559:17)
2022-12-11 12:11:44     at processTimers (node:internal/timers:502:7) {
2022-12-11 12:11:44   code: 2,
2022-12-11 12:11:44   details: 'Error: WatchdogAgent reset: lastFood: "{"data":"syncCheck()","timeoutMilliseconds":60000}"\n' +
2022-12-11 12:11:44     '    at Watchdog.reset (file:///app/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)\n' +
2022-12-11 12:11:44     '    at Watchdog.emit (node:events:513:28)\n' +
2022-12-11 12:11:44     '    at Watchdog.emit (node:domain:489:12)\n' +
2022-12-11 12:11:44     '    at Timeout._onTimeout (file:///app/node_modules/watchdog/src/watchdog.ts:115:12)\n' +
2022-12-11 12:11:44     '    at listOnTimeout (node:internal/timers:559:17)\n' +
2022-12-11 12:11:44     '    at processTimers (node:internal/timers:502:7)'

**Comment by lingkai995** [comment]
我也遇到这个问题了～

**Comment by ekkoamb** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by youzeliang** [comment]
我用其他的也遇到过类似的问题。http body里返回EOF，然后不清楚是我改了  req.close = true （非此项目） 还是刚好我尝试的时候就好了。等下次遇到的时候再说吧

**Comment by che77a38** [comment]
同样有该问题

**Comment by ekkoamb** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
