### ISSUE TITLE
uncaughtException TypeError: config.chatGPTAccountPool.filter is not a function

### ISSUE THREAD

**Issue by TIMESTICKING** [fuergaosi233/wechat-chatgpt#239]
刚启动就报了这个错，我用的是session token。服务器阿里云的未翻墙。
```
uncaughtException TypeError: config.chatGPTAccountPool.filter is not a function
    at ChatGPTPoole.startPools (file:///app/src/chatgpt.ts:133:55)
    at ChatGPTBot.startGPTBot (file:///app/src/chatgpt.ts:233:28)
    at WechatyImpl.<anonymous> (file:///app/src/main.ts:23:24)
    at WechatyImpl.emit (node:events:513:28)
    at WechatyImpl.emit (node:domain:489:12)
    at WechatyImpl.emit (file:///app/node_modules/wechaty/src/wechaty-mixins/gerror-mixin.ts:44:22)
    at PuppetWechat4u.<anonymous> (file:///app/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:246:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
收到一条消息后报这个错
```
Error: ⚠️ No chatgpt item in pool
    at ChatGPTPoole.getConversation (file:///app/src/chatgpt.ts:176:13)
    at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:188:35)
    at ChatGPTBot.getGPTMessage (file:///app/src/chatgpt.ts:253:35)
    at ChatGPTBot.onPrivateMessage (file:///app/src/chatgpt.ts:308:35)
    at ChatGPTBot.onMessage (file:///app/src/chatgpt.ts:334:27)
    at WechatyImpl.<anonymous> (file:///app/src/main.ts:32:26)
    at WechatyImpl.emit (node:events:513:28)
    at WechatyImpl.emit (node:domain:489:12)
    at WechatyImpl.emit (file:///app/node_modules/wechaty/src/wechaty-mixins/gerror-mixin.ts:44:22)
    at PuppetWechat4u.<anonymous> (file:///app/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:281:22)
```

**Comment by forsert** [comment]
我也遇到这个问题 请问你解决了吗

**Comment by TIMESTICKING** [comment]
我现在已经配置了clash了（不在docker内），服务器能curl到google，重启了docker服务和container，依然报错

**Comment by doulongfei** [comment]
同样的问题，早docker中跑的

**Comment by mydaoyuan** [comment]
同样的问题，配置了clash，后来怎么解决的

**Comment by TIMESTICKING** [comment]
> 同样的问题，配置了clash，后来怎么解决的

重新拷贝了session token。
勾选url decoded，然后重启了docker就好了。。。

**Comment by doulongfei** [comment]
勾选url decoded,这个在哪里勾选
&nbsp;


豆陇飞
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月11日(星期天) 晚上9:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fuergaosi233/wechat-chatgpt] uncaughtException TypeError: config.chatGPTAccountPool.filter is not a function (Issue #239)





  
同样的问题，配置了clash，后来怎么解决的
  
重新拷贝了session token。
 勾选url decoded，然后重启了docker就好了。。。
