### ISSUE TITLE
Error: ⚠️ No chatgpt item in pool

### ISSUE THREAD

**Issue by Josecep** [fuergaosi233/wechat-chatgpt#240]
Message: Message#Text[🗣Contact<doru>@👥Room<资料>]      @Josecep hi
🎯 Triggered ChatGPT: @Josecep hi
Error: ⚠️ No chatgpt item in pool
    at ChatGPTPoole.getConversation (file:///app/src/chatgpt.ts:176:13)
    at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:188:35)
    at ChatGPTBot.getGPTMessage (file:///app/src/chatgpt.ts:253:35)
    at ChatGPTBot.onGroupMessage (file:///app/src/chatgpt.ts:318:35)
    at ChatGPTBot.onMessage (file:///app/src/chatgpt.ts:336:27)
    at WechatyImpl.<anonymous> (file:///app/src/main.ts:32:26)
    at WechatyImpl.emit (node:events:513:28)
    at WechatyImpl.emit (node:domain:489:12)
    at WechatyImpl.emit (file:///app/node_modules/wechaty/src/wechaty-mixins/gerror-mixin.ts:44:22)
    at PuppetWechat4u.<anonymous> (file:///app/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:281:22)

**Comment by yaje0008** [comment]
我也遇到了这个问题，用的是Railway.app环境部署。由于没有加chatPrivateTiggerKeyword参数造成的，加上去就可以了

**Comment by HisMax** [comment]
已经有了相同的Issue了 [Error: ⚠️ No chatgpt item in pool](https://github.com/fuergaosi233/wechat-chatgpt/issues/238)

Already have the same Issue.

**Comment by huangzuomin** [comment]
重新登陆下openai，然后复制新的token，我用这个方法解决了

**Comment by RealTong** [comment]
Currently there are multiple identical Issues https://github.com/fuergaosi233/wechat-chatgpt/issues/210, I need to close the extra issues to ensure efficient information flow.

Thank you for your support, when we find a solution available, I will reopen it
