### ISSUE TITLE
运行过程中的报错，重启容器后正常，请问下这个是什么错误

### ISSUE THREAD

**Issue by Nkomol** [fuergaosi233/wechat-chatgpt#269]
uncaughtException GError: getaddrinfo EAI_AGAIN webpush.wx.qq.com
    at Function.AxiosError.from (/app/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (/app/node_modules/axios/lib/adapters/http.js:518:25)
    at RedirectableRequest.emit (node:events:525:35)
    at RedirectableRequest.emit (node:domain:489:12)
    at ClientRequest.eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at ClientRequest.emit (node:domain:489:12)
    at TLSSocket.socketErrorListener (node:_http_client:494:9)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket.emit (node:domain:489:12) {
  code: 2,
  details: 'Error: getaddrinfo EAI_AGAIN webpush.wx.qq.com\n' +
    '    at Function.AxiosError.from (/app/node_modules/axios/lib/core/AxiosError.js:89:14)\n' +
    '    at RedirectableRequest.handleRequestError (/app/node_modules/axios/lib/adapters/http.js:518:25)\n' +
    '    at RedirectableRequest.emit (node:events:525:35)\n' +
    '    at RedirectableRequest.emit (node:domain:489:12)\n' +
    '    at ClientRequest.eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:14:24)\n' +
    '    at ClientRequest.emit (node:events:513:28)\n' +
    '    at ClientRequest.emit (node:domain:489:12)\n' +
    '    at TLSSocket.socketErrorListener (node:_http_client:494:9)\n' +
    '    at TLSSocket.emit (node:events:513:28)\n' +
    '    at TLSSocket.emit (node:domain:489:12)'
}
10:40:58 WARN PuppetWatchdogAgent start() reset() reason: {"data":"syncCheck()","timeoutMilliseconds":60000}
uncaughtException GError: WatchdogAgent reset: lastFood: "{"data":"syncCheck()","timeoutMilliseconds":60000}"
    at Watchdog.reset (file:///app/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)
    at Watchdog.emit (node:events:513:28)
    at Watchdog.emit (node:domain:489:12)
    at Timeout._onTimeout (file:///app/node_modules/watchdog/src/watchdog.ts:115:12)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  code: 2,
  details: 'Error: WatchdogAgent reset: lastFood: "{"data":"syncCheck()","timeoutMilliseconds":60000}"\n' +
    '    at Watchdog.reset (file:///app/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)\n' +
    '    at Watchdog.emit (node:events:513:28)\n' +
    '    at Watchdog.emit (node:domain:489:12)\n' +
    '    at Timeout._onTimeout (file:///app/node_modules/watchdog/src/watchdog.ts:115:12)\n' +
    '    at listOnTimeout (node:internal/timers:559:17)\n' +
    '    at processTimers (node:internal/timers:502:7)'
}

**Comment by AlexHuang3** [comment]
I met similar problem which appears every few hour and i have to restart the container manually.
