### ISSUE TITLE
超时

### ISSUE THREAD

**Issue by kemomi** [fuergaosi233/wechat-chatgpt#273]
WARN PuppetWechat4u monkeyPatch() wechat4u.checkPolling() notifyMobile() exception: AxiosError: timeout of 60000ms exceeded
uncaughtException GError [AxiosError]: timeout of 60000ms exceeded
    at RedirectableRequest.handleRequestTimeout (/app/node_modules/axios/lib/adapters/http.js:555:16)
    at RedirectableRequest.emit (node:events:513:28)
    at RedirectableRequest.emit (node:domain:489:12)
    at Timeout.<anonymous> (/app/node_modules/follow-redirects/index.js:169:12)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  code: 2,
  details: 'AxiosError: timeout of 60000ms exceeded\n' +
    '    at RedirectableRequest.handleRequestTimeout (/app/node_modules/axios/lib/adapters/http.js:555:16)\n' +
    '    at RedirectableRequest.emit (node:events:513:28)\n' +
    '    at RedirectableRequest.emit (node:domain:489:12)\n' +
    '    at Timeout.<anonymous> (/app/node_modules/follow-redirects/index.js:169:12)\n' +
    '    at listOnTimeout (node:internal/timers:559:17)\n' +
    '    at processTimers (node:internal/timers:502:7)'
}

**Comment by zqzess** [comment]
我也是这样，一直超时
