### ISSUE TITLE
使用latest镜像依然会出现token过期情况，重新去配置一下session_token restart container就正常了

### ISSUE THREAD

**Issue by yuenwah** [fuergaosi233/wechat-chatgpt#275]
Message: Message#Text[🗣Contact<Zero>]	excel 时间格式yyyy-MM-dd HH:mm:ss 求最大值
🎯 Triggered ChatGPT: excel 时间格式yyyy-MM-dd HH:mm:ss 求最大值
Error: ⚠️ No chatgpt item in pool
    at ChatGPTPoole.getConversation (file:///app/src/chatgpt.ts:176:13)
    at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:188:35)
    at ChatGPTBot.getGPTMessage (file:///app/src/chatgpt.ts:253:35)
    at ChatGPTBot.onPrivateMessage (file:///app/src/chatgpt.ts:308:35)
    at ChatGPTBot.onMessage (file:///app/src/chatgpt.ts:334:27)
    at WechatyImpl.<anonymous> (file:///app/src/main.ts:32:26)
    at WechatyImpl.emit (node:events:513:28)
    at WechatyImpl.emit (node:domain:489:12)
    at WechatyImpl.emit (file:///app/node_modules/wechaty/src/wechaty-mixins/gerror-mixin.ts:44:22)
    at PuppetWechat4u.<anonymous> (file:///app/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:281:22)
------------------------------------------
[root@bk_center wechat-chatgpt]#  docker pull holegots/wechat-chatgpt
Using default tag: latest
latest: Pulling from holegots/wechat-chatgpt
Digest: sha256:53d5d22525522264e1e3aaaf53fa06de080be7b37e08221e08b2597264e1934b
Status: Image is up to date for holegots/wechat-chatgpt:latest
docker.io/holegots/wechat-chatgpt:latest
-------------------------------------
[root@bk_center wechat-chatgpt]# date
2022年 12月 11日 星期日 20:54:50 CST

**Comment by baymax55** [comment]
我是重新配置后,依旧无法使用报:
`
Error: ⚠️ No chatgpt item in pool
    at ChatGPTPoole.getConversation (file:///app/src/chatgpt.ts:176:13)
    at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:188:35)
    at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:197:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ChatGPTBot.getGPTMessage (file:///app/src/chatgpt.ts:253:12)
    at async ChatGPTBot.onPrivateMessage (file:///app/src/chatgpt.ts:308:24)
    at async ChatGPTBot.onMessage (file:///app/src/chatgpt.ts:334:16)
    at async WechatyImpl.<anonymous> (file:///app/src/main.ts:32:9)
`

**Comment by lanyucomputer** [comment]
> 我是重新配置后,依旧无法使用报: `Error: ⚠️ No chatgpt item in pool at ChatGPTPoole.getConversation (file:///app/src/chatgpt.ts:176:13) at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:188:35) at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:197:21) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async ChatGPTBot.getGPTMessage (file:///app/src/chatgpt.ts:253:12) at async ChatGPTBot.onPrivateMessage (file:///app/src/chatgpt.ts:308:24) at async ChatGPTBot.onMessage (file:///app/src/chatgpt.ts:334:16) at async WechatyImpl.<anonymous> (file:///app/src/main.ts:32:9)`

我的也是，这个值变得太快了，一分钟就变了一次__Secure-next-auth.session-token

**Comment by yuenwah** [comment]
> > 我是重新配置后,依旧无法使用报: `Error: ⚠️ No chatgpt item in pool at ChatGPTPoole.getConversation (file:///app/src/chatgpt.ts:176:13) at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:188:35) at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:197:21) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async ChatGPTBot.getGPTMessage (file:///app/src/chatgpt.ts:253:12) at async ChatGPTBot.onPrivateMessage (file:///app/src/chatgpt.ts:308:24) at async ChatGPTBot.onMessage (file:///app/src/chatgpt.ts:334:16) at async WechatyImpl.<anonymous> (file:///app/src/main.ts:32:9)`
> 
> 我的也是，这个值变得太快了，一分钟就变了一次__Secure-next-auth.session-token

看起来是每次切出切入页面都会变化，但这个不影响它短时间内可用(1天左右 )，我现在是到第二天差不多就失效，但看开发者说已经有了自动刷新token的功能

**Comment by yuenwah** [comment]
https://github.com/fuergaosi233/wechat-chatgpt/issues/140
