### ISSUE TITLE
切换账号掉线

### ISSUE THREAD

**Issue by 826065523** [fuergaosi233/wechat-chatgpt#283]
`
14:04:41 WARN PuppetWatchdogAgent start() reset() reason: {"data":"syncCheck()","timeoutMilliseconds":60000}
uncaughtException GError: WatchdogAgent reset: lastFood: "{"data":"syncCheck()","timeoutMilliseconds":60000}"
    at Watchdog.reset (file:///app/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)
    at Watchdog.emit (node:events:513:28)
    at Watchdog.emit (node:domain:489:12)
    at Timeout._onTimeout (file:///app/node_modules/watchdog/src/watchdog.ts:115:12)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  code: 2,
  details: 'Error: WatchdogAgent reset: lastFood: "{"data":"syncCheck()","timeoutMilliseconds":60000}"\n' +
    '    at Watchdog.reset (file:///app/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)\n' +
    '    at Watchdog.emit (node:events:513:28)\n' +
    '    at Watchdog.emit (node:domain:489:12)\n' +
    '    at Timeout._onTimeout (file:///app/node_modules/watchdog/src/watchdog.ts:115:12)\n' +
    '    at listOnTimeout (node:internal/timers:559:17)\n' +
    '    at processTimers (node:internal/timers:502:7)'`

机器人账号扫码后在手机上切换账号时，机器人协同掉线

**Comment by darkambrose** [comment]
是的，我也遇到这个问题，只能暂时先用一个不用的手机顶着，安卓。

**Comment by huangzuomin** [comment]
需要一个备用机器，意志挂微信小号
