### ISSUE TITLE
6个小时没有用，之前也是一条回答完才问下一条，突然4个账号都报429错误了

### ISSUE THREAD

**Issue by YondSun** [fuergaosi233/wechat-chatgpt#291]
开始配置的A账号，用了一会怕封号。重新申请了3个号配置到项目里，虽然有3个账号，还是一条回答完才问下一条。刚才有6个小时都没有用，结果现在发现一个都不好使了…

手动换IP用浏览器登录账号有两种情况（换了几个IP都一样，所以是号被封了？）：
1. OpenAI
Whoa there! You might need to wait a bit.
2. 输入完账号密码，闪一下又回到登录前的页面了

报错信息如下：
uncaughtException Error: Command failed with exit code 1: sh -c poetry run python3 src/generate_session.py xxxx@xxx.com xxxxxxxx
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py", line 309, in part_seven
    self.part_eight(old_state=state, new_state=new_state)
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py", line 367, in part_eight
    raise Exception("Incorrect response code")
Exception: Incorrect response code

有大佬知道是什么情况吗

**Comment by coldhotstart** [comment]
openai authorization fail,  no easy solution for now.

**Comment by lanyucomputer** [comment]
__Secure-next-auth.session-token   这个token变得太快了，一会儿就变一下，是不是这个原因？

**Comment by lanyucomputer** [comment]
> openai authorization fail, no easy solution for now.

you mean __Secure-next-auth.session-token  changes to fast ,is it?
