### ISSUE TITLE
TW 服务器，使用账户密码登陆失败

### ISSUE THREAD

**Issue by sosmygirl** [fuergaosi233/wechat-chatgpt#299]
`Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"xxxxx@gmail.com","password":"password"}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":""}
uncaughtException Error: Command failed with exit code 1: sh -c poetry run python3 src/generate_session.py xxxxx@gmail.com password
Traceback (most recent call last):
  File "/app/src/generate_session.py", line 50, in <module>
    print(login(args.email, args.password))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/generate_session.py", line 19, in login
    chatbot = Chatbot(
              ^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 62, in __init__
    self.refresh_session()
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 296, in refresh_session
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 293, in refresh_session
    self.login(self.config["email"], self.config["password"])
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 326, in login
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 319, in login
    auth.begin()
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py", line 90, in begin
    raise Exception("API error")
Exception: API error
Namespace(email='xxxxx@gmail.com', password='password')
    at makeError (file:///app/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///app/node_modules/execa/index.js:119:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ChatGPTPoole.getSessionToken (file:///app/src/chatgpt.ts:58:42)
    at async file:///app/src/chatgpt.ts:140:33
    at async Promise.all (index 0)
    at async ChatGPTPoole.startPools (file:///app/src/chatgpt.ts:136:26)
    at async ChatGPTBot.startGPTBot (file:///app/src/chatgpt.ts:233:5)
    at async WechatyImpl.<anonymous> (file:///app/src/main.ts:23:7) {
  shortMessage: 'Command failed with exit code 1: sh -c poetry run python3 src/generate_session.py xxxxx@gmail.com password',
  command: 'sh -c poetry run python3 src/generate_session.py xxxxx@gmail.com password',
  escapedCommand: 'sh -c "poetry run python3 src/generate_session.py xxxxx@gmail.com password"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: "Namespace(email='xxxxx@gmail.com', password='password')",
  stderr: 'Traceback (most recent call last):\n' +
    '  File "/app/src/generate_session.py", line 50, in <module>\n' +
    '    print(login(args.email, args.password))\n' +
    '          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n' +
    '  File "/app/src/generate_session.py", line 19, in login\n' +
    '    chatbot = Chatbot(\n' +
    '              ^^^^^^^^\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 62, in __init__\n' +
    '    self.refresh_session()\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 296, in refresh_session\n' +
    '    raise exc\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 293, in refresh_session\n' +
    '    self.login(self.config["email"], self.config["password"])\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 326, in login\n' +
    '    raise exc\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 319, in login\n' +
    '    auth.begin()\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py", line 90, in begin\n' +
    '    raise Exception("API error")\n' +
    'Exception: API error',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
`

**Comment by fuergaosi233** [comment]
https://github.com/acheong08/ChatGPT/wiki/Setup
OpenAI requires a Cloudflare token to use now.
