### ISSUE TITLE
扫码后报API error

### ISSUE THREAD

**Issue by joeylin** [fuergaosi233/wechat-chatgpt#300]
可以正常扫描，但报这个错误，账号我刚申请并验证通过的，申请之后网页版可以登录，并正常聊天。
看起来像chatgpt的 auth API有变化？
```
Traceback (most recent call last):
  File "/app/src/generate_session.py", line 50, in <module>
    print(login(args.email, args.password))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/generate_session.py", line 19, in login
    chatbot = Chatbot(
              ^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 62, in __init__
    self.refresh_session()
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 296, in refresh_session
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 293, in refresh_session
    self.login(self.config["email"], self.config["password"])
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 326, in login
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 319, in login
    auth.begin()
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py", line 90, in begin
    raise Exception("API error")
Exception: API error
```
config.yaml信息（隐藏真实密码）
```
chatGPTAccountPool:
  - email: 331547274@qq.com
    password: xxxxxx
chatPrivateTiggerKeyword: ""
```

**Comment by chldong** [comment]
看来目前都是这个错误，基本可以判断为ChatGPT服务器那边的问题。

**Comment by xyzzen** [comment]
我用账号密码也这样.

**Comment by evolution-ant** [comment]
ChatGPT 增加了 cloudflare，账号密码的方式不可以用了

**Comment by wukongroot** [comment]
新增了"accessToken"，等作者更新，

**Comment by chenyongzhi001** [comment]
> ChatGPTtoken的机制好像也变了，切换了浏览器窗口就变

yes, me too

**Comment by joeylin** [comment]
现在恢复么？大家 @chldong @evolution-ant @xyzzen @Mebigger

**Comment by joeylin** [comment]
还是有异常，这个现在没有解决方案么？

**Comment by XxxuLimei** [comment]
我也遇到了同样的问题，有解决方法吗？
