### ISSUE TITLE
npm run dev时报错

### ISSUE THREAD

**Issue by Crabor** [fuergaosi233/wechat-chatgpt#304]
TSError: ⨯ Unable to compile TypeScript:
src/main.ts:1:10 - error TS2305: Module '"wechaty"' has no exported member 'WechatyBuilder'.

1 import { WechatyBuilder } from "wechaty";
           ~~~~~~~~~~~~~~
src/main.ts:13:24 - error TS7006: Parameter 'qrcode' implicitly has an 'any' type.

13     .on("scan", async (qrcode, status) => {
                          ~~~~~~
src/main.ts:13:32 - error TS7006: Parameter 'status' implicitly has an 'any' type.

13     .on("scan", async (qrcode, status) => {
                                  ~~~~~~
src/main.ts:20:25 - error TS7006: Parameter 'user' implicitly has an 'any' type.

20     .on("login", async (user) => {
                           ~~~~
src/main.ts:25:27 - error TS7006: Parameter 'message' implicitly has an 'any' type.

25     .on("message", async (message) => {
                             ~~~~~~~

    at createTSError (/home/crabor/projects/wechat-chatgpt/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/home/crabor/projects/wechat-chatgpt/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/home/crabor/projects/wechat-chatgpt/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/home/crabor/projects/wechat-chatgpt/node_modules/ts-node/src/index.ts:1433:41)
    at transformSource (/home/crabor/projects/wechat-chatgpt/node_modules/ts-node/src/esm.ts:400:37)
    at /home/crabor/projects/wechat-chatgpt/node_modules/ts-node/src/esm.ts:278:53
    at async addShortCircuitFlag (/home/crabor/projects/wechat-chatgpt/node_modules/ts-node/src/esm.ts:409:15)
    at async nextLoad (node:internal/modules/esm/loader:161:22)
    at async ESMLoader.load (node:internal/modules/esm/loader:594:20)
    at async ESMLoader.moduleProvider (node:internal/modules/esm/loader:446:11) {
  diagnosticCodes: [ 2305, 7006, 7006, 7006, 7006 ]
}

**Comment by fuergaosi233** [comment]
Use docker pls.
