### ISSUE TITLE
No chatgpt item in pool

### ISSUE THREAD

**Issue by Ratrme** [fuergaosi233/wechat-chatgpt#306]
Error: ⚠️ No chatgpt item in pool
    at ChatGPTPoole.getConversation (file:///app/src/chatgpt.ts:176:13)
    at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:188:35)
    at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:197:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ChatGPTBot.getGPTMessage (file:///app/src/chatgpt.ts:253:12)
    at async ChatGPTBot.onPrivateMessage (file:///app/src/chatgpt.ts:308:24)
    at async ChatGPTBot.onMessage (file:///app/src/chatgpt.ts:334:16)
    at async WechatyImpl.<anonymous> (file:///app/src/main.ts:32:9)

**Comment by byegates** [comment]
一样的问题，似乎chatGPT官方把 session-Token给封杀了?

**Comment by lj7xun** [comment]
不止     我使用session-Token和账号密码都是这个报错

**Comment by fuergaosi233** [comment]
https://github.com/acheong08/ChatGPT/wiki/Setup
OpenAI requires a Cloudflare token to use now.
I will fix it.

**Comment by YYYYasa** [comment]
看不懂↑怎么配置的，请问有人解释一下吗

**Comment by nx4dm1n** [comment]
chatGPT官方今天早上做了迭代更新，增加了一些安全验证的机制，主要是对人机进行识别，防止因为自动化程序导致的资源占用。所以这个项目的session_token和账号密码认证的方式都失效了，都会产生错误，等作者更新。

**Comment by YYYYasa** [comment]
> chatGPT官方今天早上做了迭代更新，增加了一些安全验证的机制，主要是对人机进行识别，防止因为自动化程序导致的资源占用。所以这个项目的session_token和账号密码认证的方式都失效了，都会产生错误，等作者更新。

好的谢谢

**Comment by a912289748** [comment]
快点更新

**Comment by tangmessi** [comment]
> https://github.com/acheong08/ChatGPT/wiki/Setup OpenAI requires a Cloudflare token to use now. I will fix it.

Looking forward to your good news

**Comment by kongyong16** [comment]
等待

**Comment by SebMao** [comment]
qwq等等

**Comment by byegates** [comment]
怎么样了

**Comment by byegates** [comment]
彻底没戏了？
