### ISSUE TITLE
更新token之后还是No chatgpt item in pool

### ISSUE THREAD

**Issue by MicroOpeMaster** [fuergaosi233/wechat-chatgpt#309]
昨天是可以正常使用的，睡一觉醒来就是no chatgpt item in pool，检查了config账号密码都是没问题的，尝试使用token也没有用
`Error: ⚠️ No chatgpt item in pool
    at ChatGPTPoole.getConversation (file:///app/src/chatgpt.ts:176:13)
    at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:188:35)
    at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:197:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ChatGPTBot.getGPTMessage (file:///app/src/chatgpt.ts:253:12)
    at async ChatGPTBot.onPrivateMessage (file:///app/src/chatgpt.ts:308:24)
    at async ChatGPTBot.onMessage (file:///app/src/chatgpt.ts:334:16)
    at async WechatyImpl.<anonymous> (file:///app/src/main.ts:32:9)
`

**Comment by cjd9023** [comment]
官网出了新安全措施, 开发者正在想办法解决中.

**Comment by lee-chard** [comment]
一样，你可以看看这个 #294

**Comment by yumu7777777** [comment]
现在都有这个问题，等等吧

**Comment by i-iooi-i** [comment]
看来大家都遇到了相同的问题

**Comment by kongyong16** [comment]
等作者更新版本吧
