### ISSUE TITLE
Error: ⚠️ No chatgpt item in pool

### ISSUE THREAD

**Issue by dockercore** [fuergaosi233/wechat-chatgpt#310]
Error: ⚠️ No chatgpt item in pool
    at ChatGPTPoole.getConversation (file:///app/src/chatgpt.ts:176:13)
    at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:188:35)
    at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:197:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ChatGPTBot.getGPTMessage (file:///app/src/chatgpt.ts:253:12)
    at async ChatGPTBot.onPrivateMessage (file:///app/src/chatgpt.ts:308:24)
    at async ChatGPTBot.onMessage (file:///app/src/chatgpt.ts:334:16)
    at async WechatyImpl.<anonymous> (file:///app/src/main.ts:32:9)

**Comment by WiZ1314** [comment]
官网出了新安全措施，开发者正处于想办法解决中。

**Comment by HenryHengLUO** [comment]
I cannot connect to chatgpt either.

**Comment by caipeizhi** [comment]
我也是这个错误，尝试试过添加cf_clearance，user_agent，Authorization都不行

**Comment by Qervas** [comment]
模拟一下点击操作？

**Comment by OliverGrace** [comment]
官网出问题

**Comment by gates940** [comment]
之前是好好的，应该是官网加了什么措施，任何接口调用都不太行了，只能是官网登陆使用。

**Comment by miozus** [comment]
同样报错，哭晕在厕所

**Comment by LailaiMaster** [comment]
+1

**Comment by vsv1020** [comment]
me too~+1

**Comment by demonlzxgg** [comment]
更新 token都不行~~

**Comment by Qervas** [comment]
目前另一个项目调用API可以用，现在登录要验证谷歌九宫格了，而且还有session超时检测

**Comment by fasterpma** [comment]
me too~
