### ISSUE TITLE
uncaughtException GError: connect ECONNREFUSED 0.0.0.0:443

### ISSUE THREAD

**Issue by Huozhe-Siqu** [fuergaosi233/wechat-chatgpt#311]
uncaughtException GError: connect ECONNREFUSED 0.0.0.0:443
    at Function.AxiosError.from (/app/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (/app/node_modules/axios/lib/adapters/http.js:518:25)
    at RedirectableRequest.emit (node:events:525:35)
    at RedirectableRequest.emit (node:domain:489:12)
    at ClientRequest.eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at ClientRequest.emit (node:domain:489:12)
    at TLSSocket.socketErrorListener (node:_http_client:494:9)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket.emit (node:domain:489:12) {
  code: 2,
  details: 'Error: connect ECONNREFUSED 0.0.0.0:443\n' +
    '    at Function.AxiosError.from (/app/node_modules/axios/lib/core/AxiosError.js:89:14)\n' +
    '    at RedirectableRequest.handleRequestError (/app/node_modules/axios/lib/adapters/http.js:518:25)\n' +
    '    at RedirectableRequest.emit (node:events:525:35)\n' +
    '    at RedirectableRequest.emit (node:domain:489:12)\n' +
    '    at ClientRequest.eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:14:24)\n' +
    '    at ClientRequest.emit (node:events:513:28)\n' +
    '    at ClientRequest.emit (node:domain:489:12)\n' +
    '    at TLSSocket.socketErrorListener (node:_http_client:494:9)\n' +
    '    at TLSSocket.emit (node:events:513:28)\n' +
    '    at TLSSocket.emit (node:domain:489:12)'
}

**Comment by Huozhe-Siqu** [comment]
好吧，是我dns的问题。
