### ISSUE TITLE
docker更新一下呗

### ISSUE THREAD

**Issue by cyDione** [fuergaosi233/wechat-chatgpt#318]

**Comment by ys-zzu** [comment]
+1

**Comment by yaje0008** [comment]
+1

**Comment by Maru412** [comment]
+1

**Comment by Maru412** [comment]
+1

**Comment by donkeyzero** [comment]
+1

**Comment by chenyongzhi001** [comment]
+10086

**Comment by caipeizhi** [comment]
这么多人在线等

**Comment by LiShengchu** [comment]
确实哈哈哈

**Comment by AA8j** [comment]
111

**Comment by jamebal** [comment]
+1

**Comment by xlxiaodai** [comment]
111

**Comment by jaceyi** [comment]
+1

**Comment by YangguangZhou** [comment]
+1

**Comment by cjd9023** [comment]
+0.1

**Comment by cjd9023** [comment]
觉得应该不是更新 Dockerfile, 而是 poetry.lock,  但如果2小时频繁需要更新 cf ,你们仍会坚持手动更新吗

**Comment by tangmessi** [comment]
++

**Comment by ys-zzu** [comment]
我自己构建docker，配置都填好了还是不行

**Comment by LeiLei123-cmd** [comment]
我也是，全部更新了一遍，但是还是不行
No chatgpt item in pool
2022-12-12 15:58:23     at ChatGPTPoole.getConversation (file:///app/src/chatgpt.ts:176:13)
2022-12-12 15:58:23     at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:188:35)
2022-12-12 15:58:23     at ChatGPTBot.getGPTMessage (file:///app/src/chatgpt.ts:253:35)
2022-12-12 15:58:23     at ChatGPTBot.onPrivateMessage (file:///app/src/chatgpt.ts:308:35)
2022-12-12 15:58:23     at ChatGPTBot.onMessage (file:///app/src/chatgpt.ts:334:27)
2022-12-12 15:58:23     at WechatyImpl.<anonymous> (file:///app/src/main.ts:32:26)
2022-12-12 15:58:23     at WechatyImpl.emit (node:events:513:28)

**Comment by ys-zzu** [comment]
自己构建docker也是报错

Error: ⚠️ No chatgpt item in pool
    at ChatGPTPoole.getConversation (file:///app/src/chatgpt.ts:200:13)
    at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:219:35)
    at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:230:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ChatGPTBot.getGPTMessage (file:///app/src/chatgpt.ts:286:12)
    at async ChatGPTBot.onPrivateMessage (file:///app/src/chatgpt.ts:341:24)
    at async ChatGPTBot.onMessage (file:///app/src/chatgpt.ts:367:16)
    at async WechatyImpl.<anonymous> (file:///app/src/main.ts:32:9)

**Comment by dhzq** [comment]
+1

**Comment by icxcoffee** [comment]
uncaughtException GError: getaddrinfo EAI_AGAIN login.wx.qq.com
    at Function.AxiosError.from (/app/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (/app/node_modules/axios/lib/adapters/http.js:518:25)
    at RedirectableRequest.emit (node:events:525:35)
    at RedirectableRequest.emit (node:domain:489:12)
    at ClientRequest.eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at ClientRequest.emit (node:domain:489:12)
    at TLSSocket.socketErrorListener (node:_http_client:494:9)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket.emit (node:domain:489:12) {
  code: 2,
  details: 'Error: getaddrinfo EAI_AGAIN login.wx.qq.com\n' +
    '    at Function.AxiosError.from (/app/node_modules/axios/lib/core/AxiosError.js:89:14)\n' +
    '    at RedirectableRequest.handleRequestError (/app/node_modules/axios/lib/adapters/http.js:518:25)\n' +
    '    at RedirectableRequest.emit (node:events:525:35)\n' +
    '    at RedirectableRequest.emit (node:domain:489:12)\n' +
    '    at ClientRequest.eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:14:24)\n' +
    '    at ClientRequest.emit (node:events:513:28)\n' +
    '    at ClientRequest.emit (node:domain:489:12)\n' +
    '    at TLSSocket.socketErrorListener (node:_http_client:494:9)\n' +
    '    at TLSSocket.emit (node:events:513:28)\n' +
    '    at TLSSocket.emit (node:domain:489:12)'
}

**Comment by jike55555** [comment]
+1
