### ISSUE TITLE
新注册的微信小号不行，微信老号可以使用

### ISSUE THREAD

**Issue by xyz1041221997** [fuergaosi233/wechat-chatgpt#319]
新注册的微信小号扫描后提示异常信息
uncaughtException AssertionError [ERR_ASSERTION]: 1 == 0
at Object.equal (/app/node_modules/wechat4u/src/util/global.js:53:14)
at /app/node_modules/wechat4u/src/core.js:195:16
at processTicksAndRejections (node:internal/process/task_queues:96:5) {
code: 2,
details: 'AssertionError [ERR_ASSERTION]: 1 == 0\n' +
'    at Object.equal (/app/node_modules/wechat4u/src/util/global.js:53:14)\n' +
'    at /app/node_modules/wechat4u/src/core.js:195:16\n' +
'    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
}

**Comment by emmmnaadada** [comment]
要实名认证

**Comment by Anonymouszzz** [comment]
没有实名认证

**Comment by goodluckily** [comment]
可能需要绑定银行卡,开通微信支付,实名认证这些操作

**Comment by songw** [comment]
实名认证了也不行

**Comment by Anonymouszzz** [comment]
openai加了新的认证 暂时寄了 等作者更新吧

**Comment by lu7shuo** [comment]
你试试看能不能登录网页版微信，不行的话就不可以

**Comment by Zhouguangwei327** [comment]
> 你试试看能不能登录网页版微信，不行的话就不可以

老的微信号登录不了网页版微信，但是可以使用，就是新的微信号不行，不确定为什么

**Comment by Zhouguangwei327** [comment]
> 需要实名认证，通过了就能登陆了

**Comment by boy0208** [comment]
登入之后微信给谁发消息呀
