### ISSUE TITLE
yaml文件里用账号和密码，出现以下错误，求助

### ISSUE THREAD

**Issue by Sherlockliu7777** [fuergaosi233/wechat-chatgpt#335]
Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"我的账号","password":"我的密码"}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":""}
uncaughtException Error: Command failed with exit code 1: sh -c poetry run python3 src/generate_session.py 账号 密码
Traceback (most recent call last):
  File "/app/src/generate_session.py", line 50, in <module>
    print(login(args.email, args.password))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/generate_session.py", line 19, in login
    chatbot = Chatbot(
              ^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 62, in __init__
    self.refresh_session()
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 296, in refresh_session
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 293, in refresh_session
    self.login(self.config["email"], self.config["password"])
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 326, in login
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 319, in login
    auth.begin()
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py", line 90, in begin
    raise Exception("API error")
Exception: API error

**Comment by kuangzhenxi** [comment]
我也是，楼主解决了吗

**Comment by zhaogangang** [comment]
me too

**Comment by seolhw** [comment]
me too
