### ISSUE TITLE
windows下运行docker容器 docker logs -f wechat-chatgpt报以下错误

### ISSUE THREAD

**Issue by MissLXM** [fuergaosi233/wechat-chatgpt#338]
![Snipaste_2022-12-12_20-01-04](https://user-images.githubusercontent.com/40783361/207040103-3ae9db57-276e-42de-895b-0b6ebdcbd171.jpg)

**Comment by wuyinwuxian** [comment]
遇到了同样问题
`
npm ERR! path /app
npm ERR! command failed
npm ERR! signal SIGTERM
npm ERR! command sh -c -- nodemon --exec node --watch config.yaml --loader ts-node/esm src/main.ts

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-12-12T13_35_10_260Z-debug-0.log
`

错误信息如上
在我发送 你好后日志如下
`Message: Message#Text[🗣Contact<wuyinwuxian>]    你好
🎯 Triggered ChatGPT: 你好
Error: ⚠️ No chatgpt item in pool
    at ChatGPTPoole.getConversation (file:///app/src/chatgpt.ts:176:13)
    at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:188:35)
    at ChatGPTBot.getGPTMessage (file:///app/src/chatgpt.ts:253:35)
    at ChatGPTBot.onPrivateMessage (file:///app/src/chatgpt.ts:308:35)
    at ChatGPTBot.onMessage (file:///app/src/chatgpt.ts:334:27)
    at WechatyImpl.<anonymous> (file:///app/src/main.ts:32:26)
    at WechatyImpl.emit (node:events:513:28)
    at WechatyImpl.emit (node:domain:489:12)
    at WechatyImpl.emit (file:///app/node_modules/wechaty/src/wechaty-mixins/gerror-mixin.ts:44:22)
    at PuppetWechat4u.<anonymous> (file:///app/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:281:22)`

**Comment by bluefly666** [comment]
加一
