### ISSUE TITLE
添加了 clearanceToken 和 userAgent 之后依然报错：No chatgpt item in pool

### ISSUE THREAD

**Issue by font-ds** [fuergaosi233/wechat-chatgpt#339]

**Comment by lhbppi** [comment]
俺也一样

**Comment by 0kz** [comment]
+1

**Comment by nx4dm1n** [comment]
还要注意IP地址，刚跑起来了，本机跑的。

**Comment by font-ds** [comment]
> 还要注意IP地址，刚跑起来了，本机跑的。

我本机mac也可以  但是用windows和服务器都跑不起来

**Comment by yeyimilk** [comment]
我用 Mac，外网，没有挂代理也有这个问题。

**Comment by Albertzc** [comment]
#210

**Comment by xtgmf** [comment]
Error: ⚠️ No chatgpt item in pool
2022-12-13 04:01:21     at ChatGPTPoole.getConversation (file:///app/src/chatgpt.ts:176:13)
2022-12-13 04:01:21     at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:188:35)
2022-12-13 04:01:21     at ChatGPTBot.getGPTMessage (file:///app/src/chatgpt.ts:253:35)
2022-12-13 04:01:21     at ChatGPTBot.onPrivateMessage (file:///app/src/chatgpt.ts:308:35)
2022-12-13 04:01:21     at ChatGPTBot.onMessage (file:///app/src/chatgpt.ts:334:27)
2022-12-13 04:01:21     at WechatyImpl.<anonymous> (file:///app/src/main.ts:32:26)
2022-12-13 04:01:21     at WechatyImpl.emit (node:events:513:28)
2022-12-13 04:01:21     at WechatyImpl.emit (node:domain:489:12)
2022-12-13 04:01:21     at WechatyImpl.emit (file:///app/node_modules/wechaty/src/wechaty-mixins/gerror-mixin.ts:44:22)
2022-12-13 04:01:21     at PuppetWechat4u.<anonymous> (file:///app/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:281:22)

**Comment by lx277856602** [comment]
Error: ⚠️ No chatgpt item in pool
    at ChatGPTPoole.getConversation (file:///app/src/chatgpt.ts:176:13)
    at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:188:35)
    at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:197:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ChatGPTBot.getGPTMessage (file:///app/src/chatgpt.ts:253:12)
    at async ChatGPTBot.onPrivateMessage (file:///app/src/chatgpt.ts:308:24)
    at async ChatGPTBot.onMessage (file:///app/src/chatgpt.ts:334:16)
    at async WechatyImpl.<anonymous> (file:///app/src/main.ts:32:9)

**Comment by brightgems** [comment]
Looks like it doesn't work any more, thanks for sharing information

**Comment by RealTong** [comment]
https://github.com/fuergaosi233/wechat-chatgpt/issues/210
