### ISSUE TITLE
mac 起不来

### ISSUE THREAD

**Issue by cooker** [fuergaosi233/wechat-chatgpt#34]
[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/**/*
[nodemon] watching extensions: ts
[nodemon] starting `node --loader ts-node/esm src/main.ts`
(node:7849) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
internal/modules/cjs/loader.js:902
  const err = new Error(message);
              ^

Error: Cannot find module 'typescript'
Require stack:
- /Users/grant/Downloads/wechat-chatgpt/node_modules/ts-node/dist/util.js
- /Users/grant/Downloads/wechat-chatgpt/node_modules/ts-node/dist/index.js
- /Users/grant/Downloads/wechat-chatgpt/node_modules/ts-node/dist/esm.js
- /Users/grant/Downloads/wechat-chatgpt/node_modules/ts-node/esm.mjs
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.resolve (internal/modules/cjs/helpers.js:107:19)
    at projectLocalResolveHelper (/Users/grant/Downloads/wechat-chatgpt/node_modules/ts-node/dist/util.js:117:24)
    at resolveCompiler (/Users/grant/Downloads/wechat-chatgpt/node_modules/ts-node/dist/configuration.js:232:22)
    at resolveAndLoadCompiler (/Users/grant/Downloads/wechat-chatgpt/node_modules/ts-node/dist/configuration.js:225:26)
    at findAndReadConfig (/Users/grant/Downloads/wechat-chatgpt/node_modules/ts-node/dist/configuration.js:48:28)
    at create (/Users/grant/Downloads/wechat-chatgpt/node_modules/ts-node/dist/index.js:146:69)
    at register (/Users/grant/Downloads/wechat-chatgpt/node_modules/ts-node/dist/index.js:127:19)
    at Object.registerAndCreateEsmHooks (/Users/grant/Downloads/wechat-chatgpt/node_modules/ts-node/dist/esm.js:25:49)
    at file:///Users/grant/Downloads/wechat-chatgpt/node_modules/ts-node/esm.mjs:8:7 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/grant/Downloads/wechat-chatgpt/node_modules/ts-node/dist/util.js',
    '/Users/grant/Downloads/wechat-chatgpt/node_modules/ts-node/dist/index.js',
    '/Users/grant/Downloads/wechat-chatgpt/node_modules/ts-node/dist/esm.js',
    '/Users/grant/Downloads/wechat-chatgpt/node_modules/ts-node/esm.mjs'
  ]
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by fuergaosi233** [comment]
Pls use docker image 🙏.
