### ISSUE TITLE
occur error after scanning qrcode

### ISSUE THREAD

**Issue by goforwork** [fuergaosi233/wechat-chatgpt#37]
uncaughtException AssertionError [ERR_ASSERTION]: 1 == 0
    at Object.equal (/app/node_modules/wechat4u/src/util/global.js:53:14)
    at /app/node_modules/wechat4u/src/core.js:195:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 1 == 0\n' +
    '    at Object.equal (/app/node_modules/wechat4u/src/util/global.js:53:14)\n' +
    '    at /app/node_modules/wechat4u/src/core.js:195:16\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
}

**Comment by RealTong** [comment]
可能你的微信不支持使用web协议
可能的原因是: 
* 使用的是某一时间段之后注册的微信.
* 使用的WeChat.

可以尝试: 
* 更换其他微信号
* 在`main.ts` line 6. 修改puppet 使用uos协议

```javascript
const bot = WechatyBuilder.build({
  name: "wechat-assistant", // generate xxxx.memory-card.json and save login data for the next login
  puppet: "wechaty-puppet-wechat",
  puppetOptions: {
    uos: true,
  }
});
```

**Comment by mofang1104** [comment]
修改了main.ts文件，但是报了下面的错误
> wechat-chatgpt@1.0.0 dev
> nodemon --exec node --loader ts-node/esm src/main.ts

[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/**/*
[nodemon] watching extensions: ts
[nodemon] starting `node --loader ts-node/esm src/main.ts`
(node:33) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
10:58:43 ERR PuppetWeChatBridge start() exception: Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (982053).
10:58:43 ERR PuppetWeChat initBridge() exception: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (982053).
10:58:43 ERR PuppetWeChat initBridge() this.bridge.stop() rejection: Error: no page
GError: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (982053).
    at ChromeLauncher.launch (/app/node_modules/puppeteer/src/node/Launcher.ts:146:30)
    at PuppeteerNode.launch (/app/node_modules/puppeteer/src/node/Puppeteer.ts:155:27)
    at PuppeteerExtra.launch (/app/node_modules/puppeteer-extra/src/index.ts:169:37)
    at async Bridge.initBrowser (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:166:17)
    at async Bridge.start (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:97:22)
    at async PuppetWeChat.initBridge (file:///app/node_modules/wechaty-puppet-wechat/src/puppet-wechat.ts:253:7)
    at async PuppetWeChat.onStart (file:///app/node_modules/wechaty-puppet-wechat/src/puppet-wechat.ts:130:19)
    at async PuppetWeChat.start (file:///app/node_modules/state-switch/src/service-ctl/service-ctl.ts:89:9)
    at async PuppetWeChat.start (file:///app/node_modules/wechaty-puppet/src/mixins/service-mixin.ts:34:7)
    at async PuppetWeChat.start (file:///app/node_modules/wechaty-puppet/src/mixins/ready-mixin.ts:24:7) {
  code: 2,
  details: 'Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (982053).\n' +
    '    at ChromeLauncher.launch (/app/node_modules/puppeteer/src/node/Launcher.ts:146:30)\n' +
    '    at PuppeteerNode.launch (/app/node_modules/puppeteer/src/node/Puppeteer.ts:155:27)\n' +
    '    at PuppeteerExtra.launch (/app/node_modules/puppeteer-extra/src/index.ts:169:37)\n' +
    '    at async Bridge.initBrowser (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:166:17)\n' +
    '    at async Bridge.start (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:97:22)\n' +
    '    at async PuppetWeChat.initBridge (file:///app/node_modules/wechaty-puppet-wechat/src/puppet-wechat.ts:253:7)\n' +
    '    at async PuppetWeChat.onStart (file:///app/node_modules/wechaty-puppet-wechat/src/puppet-wechat.ts:130:19)\n' +
    '    at async PuppetWeChat.start (file:///app/node_modules/state-switch/src/service-ctl/service-ctl.ts:89:9)\n' +
    '    at async PuppetWeChat.start (file:///app/node_modules/wechaty-puppet/src/mixins/service-mixin.ts:34:7)\n' +
    '    at async PuppetWeChat.start (file:///app/node_modules/wechaty-puppet/src/mixins/ready-mixin.ts:24:7)'
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by Anhlaidh** [comment]
我改了main.ts,依然是这个错误

uncaughtException AssertionError [ERR_ASSERTION]: 1 == 0
    at Object.equal (/app/node_modules/wechat4u/src/util/global.js:53:14)
    at /app/node_modules/wechat4u/src/core.js:195:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 1 == 0\n' +
    '    at Object.equal (/app/node_modules/wechat4u/src/util/global.js:53:14)\n' +
    '    at /app/node_modules/wechat4u/src/core.js:195:16\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
}

**Comment by gaoconggit** [comment]
我这边修改之后，报了一个超时的错误

**Comment by waytoarcher** [comment]
> 可能你的微信不支持使用web协议 可能的原因是:
> 
> * 使用的是某一时间段之后注册的微信.
> * 使用的WeChat.
> 
> 可以尝试:
> 
> * 更换其他微信号
> * 在`main.ts` line 6. 修改puppet 使用uos协议
> 
> ```js
> const bot = WechatyBuilder.build({
>   name: "wechat-assistant", // generate xxxx.memory-card.json and save login data for the next login
>   puppet: "wechaty-puppet-wechat",
>   puppetOptions: {
>     uos: true,
>   }
> });
> ```

```bash
#注册的新微信号，扫描登陆失败：
23:52:31 WARN PuppetWeChatBridge onDialog() page.on(dialog) type:type() {
        return this._type;
    } message:你需要开通微信支付，才可继续操作。
file:///home/sandy/wechat-gpt/wechat-chatgpt/node_modules/gerror/src/gerror/gerror.ts:69
      const e = new Error(payload)
                ^
GError: type() {
        return this._type;
    }(你需要开通微信支付，才可继续操作。)
    at Function.from (file:///home/sandy/wechat-gpt/wechat-chatgpt/node_modules/gerror/src/gerror/gerror.ts:69:17)
    at Bridge.onDialog (file:///home/sandy/wechat-gpt/wechat-chatgpt/node_modules/wechaty-puppet-wechat/src/bridge.ts:190:31)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 2,
  details: 'GError: type() {\n' +
    '        return this._type;\n' +
    '    }(你需要开通微信支付，才可继续操作。)\n' +
    '    at Function.from (file:///home/sandy/wechat-gpt/wechat-chatgpt/node_modules/gerror/src/gerror/gerror.ts:69:17)\n' +
    '    at Bridge.onDialog (file:///home/sandy/wechat-gpt/wechat-chatgpt/node_modules/wechaty-puppet-wechat/src/bridge.ts:190:31)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
[nodemon] app crashed - waiting for file changes before starting...

```
