### ISSUE TITLE
扫码登录后报错

### ISSUE THREAD

**Issue by liangjaden** [fuergaosi233/wechat-chatgpt#395]
Traceback (most recent call last):
  File "/app/src/generate_session.py", line 50, in <module>
    print(login(args.email, args.password))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/generate_session.py", line 19, in login
    chatbot = Chatbot(
              ^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 62, in __init__
    self.refresh_session()
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 296, in refresh_session
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 293, in refresh_session
    self.login(self.config["email"], self.config["password"])
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 326, in login
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 319, in login
    auth.begin()
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py", line 90, in begin
    raise Exception("API error")
Exception: API error

**Comment by liangjaden** [comment]
构建最新的镜像问题解决了
