### ISSUE TITLE
 API error

### ISSUE THREAD

**Issue by 1765348740** [fuergaosi233/wechat-chatgpt#397]
uncaughtException Error: Command failed with exit code 1: sh -c poetry run python3 src/generate_session.py xxxx@xx.com   xxxxx
Traceback (most recent call last):
  File "/app/src/generate_session.py", line 50, in <module>
    print(login(args.email, args.password))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/generate_session.py", line 19, in login
    chatbot = Chatbot(
              ^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 62, in __init__
    self.refresh_session()
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 296, in refresh_session
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 293, in refresh_session
    self.login(self.config["email"], self.config["password"])
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 326, in login
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 319, in login
    auth.begin()
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py", line 90, in begin
    raise Exception("API error")
Exception: API error
Namespace(email='xxxx@xxx.com', password='xxxxx')
    at makeError (file:///app/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///app/node_modules/execa/index.js:119:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ChatGPTPoole.getSessionToken (file:///app/src/chatgpt.ts:58:42)
    at async file:///app/src/chatgpt.ts:140:33
    at async Promise.all (index 0)
    at async ChatGPTPoole.startPools (file:///app/src/chatgpt.ts:136:26)
    at async ChatGPTBot.startGPTBot (file:///app/src/chatgpt.ts:233:5)
    at async WechatyImpl.<anonymous> (file:///app/src/main.ts:23:7) {
  shortMessage: 'Command failed with exit code 1: sh -c poetry run python3 src/generate_session.py 
  command: 'sh -c poetry run python3 src/generate_session.py 
  escapedCommand: 'sh -c "poetry run python3 src/generate_session.py
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: "Namespace(email='xxxxx', password='xxxxxxx')",
  stderr: 'Traceback (most recent call last):\n' +
    '  File "/app/src/generate_session.py", line 50, in <module>\n' +
    '    print(login(args.email, args.password))\n' +
    '          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n' +
    '  File "/app/src/generate_session.py", line 19, in login\n' +
    '    chatbot = Chatbot(\n' +
    '              ^^^^^^^^\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 62, in __init__\n' +
    '    self.refresh_session()\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 296, in refresh_session\n' +
    '    raise exc\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 293, in refresh_session\n' +
    '    self.login(self.config["email"], self.config["password"])\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 326, in login\n' +
    '    raise exc\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 319, in login\n' +
    '    auth.begin()\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py", line 90, in begin\n' +
    '    raise Exception("API error")\n' +
    'Exception: API error',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

**Comment by BayminY** [comment]
same error

**Comment by lofter414** [comment]
> same error

+1

**Comment by LayneChai** [comment]
same error

**Comment by YondSun** [comment]
+1用的是CAPTCHA_TOKEN

**Comment by LayneChai** [comment]
> CAPTCHA_TOKEN

在config 配置文件中没有这个字段，需要怎么设置使用这个 CAPTCHA_TOKEN，说明文件中只说明了可以用这个，但是具体的没说怎么用好像

**Comment by wsdzwx2001** [comment]
同样的错误
有解决的吗

**Comment by YondSun** [comment]
> > CAPTCHA_TOKEN
> 
> 在config 配置文件中没有这个字段，需要怎么设置使用这个 CAPTCHA_TOKEN，说明文件中只说明了可以用这个，但是具体的没说怎么用好像

#387

**Comment by emmmnaadada** [comment]
同样的错误

**Comment by tiger233** [comment]
same error

**Comment by tiger233** [comment]
> > CAPTCHA_TOKEN
> 
> 在config 配置文件中没有这个字段，需要怎么设置使用这个 CAPTCHA_TOKEN，说明文件中只说明了可以用这个，但是具体的没说怎么用好像

我是在启动容器的时候使用-v参数配置该环境变量的

**Comment by Killua-Zhuang** [comment]
> > > CAPTCHA_TOKEN
> > 
> > 
> > 在config 配置文件中没有这个字段，需要怎么设置使用这个 CAPTCHA_TOKEN，说明文件中只说明了可以用这个，但是具体的没说怎么用好像
> 
> 我是在启动容器的时候使用-v参数配置该环境变量的

解决了吗

**Comment by YondSun** [comment]
There may be a problem with the Docker image because I don't have an X86 device and Qume doesn't work.

@fuergaosi233 可以用我的服务器测试docker，如果需要请联系我
