### ISSUE TITLE
Error: ⚠️ No chatgpt item in pool

### ISSUE THREAD

**Issue by chendesk** [fuergaosi233/wechat-chatgpt#408]
这个应该怎么解决呀  换token码还是不可以
Error: ⚠️ No chatgpt item in pool
    at ChatGPTPoole.getConversation (file:///app/src/chatgpt.ts:176:13)
    at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:188:35)
    at ChatGPTBot.getGPTMessage (file:///app/src/chatgpt.ts:253:35)
    at ChatGPTBot.onPrivateMessage (file:///app/src/chatgpt.ts:308:35)
    at ChatGPTBot.onMessage (file:///app/src/chatgpt.ts:334:27)
    at WechatyImpl.<anonymous> (file:///app/src/main.ts:32:26)
    at WechatyImpl.emit (node:events:513:28)
    at WechatyImpl.emit (node:domain:489:12)
    at WechatyImpl.emit (file:///app/node_modules/wechaty/src/wechaty-mixins/gerror-mixin.ts:44:22)
    at PuppetWechat4u.<anonymous> (file:///app/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:281:22)

**Comment by tiger233** [comment]
Same error. 主要还是chatgpt网站登录失败

**Comment by QingShewky** [comment]
同样的问题，这是自己的原因还是官网的问题，而且新的说明里也没有token的方式了

**Comment by cl1169451697** [comment]
我也是这样

**Comment by fuergaosi233** [comment]
There is a problem with the way docker is started
