### ISSUE TITLE
设置了 NOPECHA_KEY 和 CAPTCHA_TOKEN 依然显示 API error

### ISSUE THREAD

**Issue by shadow0x000** [fuergaosi233/wechat-chatgpt#412]
Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"xxxxxx@qq.com","password":"xxxxxxx","isGoogleLogin":false}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":"ai"}
uncaughtException Error: Command failed with exit code 1: sh -c poetry run python3 src/generate_session.py xxxxxx@qq.com xxxxxxx
Traceback (most recent call last):
  File "/app/src/generate_session.py", line 50, in <module>
    print(login(args.email, args.password))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/generate_session.py", line 19, in login
    chatbot = Chatbot(
              ^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 62, in __init__
    self.refresh_session()
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 296, in refresh_session
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 293, in refresh_session
    self.login(self.config["email"], self.config["password"])
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 326, in login
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 319, in login
    auth.begin()
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py", line 90, in begin
    raise Exception("API error")
Exception: API error

账号密码部分以xxxxxxx隐藏

**Comment by Killua-Zhuang** [comment]
same error

**Comment by PowerChina** [comment]
same error

**Comment by moelyman** [comment]
same error

**Comment by YondSun** [comment]
same error

**Comment by KillZero12138** [comment]
> same error



> Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"[xxxxxx@qq.com](mailto:xxxxxx@qq.com)","password":"xxxxxxx","isGoogleLogin":false}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":"ai"} uncaughtException Error: Command failed with exit code 1: sh -c poetry run python3 src/generate_session.py [xxxxxx@qq.com](mailto:xxxxxx@qq.com) xxxxxxx Traceback (most recent call last): File "/app/src/generate_session.py", line 50, in print(login(args.email, args.password)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/app/src/generate_session.py", line 19, in login chatbot = Chatbot( ^^^^^^^^ File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 62, in **init** self.refresh_session() File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 296, in refresh_session raise exc File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 293, in refresh_session self.login(self.config["email"], self.config["password"]) File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 326, in login raise exc File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 319, in login auth.begin() File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py", line 90, in begin raise Exception("API error") Exception: API error
> 
> 账号密码部分以xxxxxxx隐藏

这个 NOPECHA_KEY 和 CAPTCHA_TOKEN 如何设置

**Comment by shadow0x000** [comment]
> > 同样的错误
> 
> > 启动 GPT Bot Config 是：{"chatGPTAccountPool":[{"email":" [xxxxxx@qq.com](mailto:xxxxxx@qq.com) ","password":"xxxxxxx","isGoogleLogin":false}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword" :"ai"} uncaughtException 错误：命令失败，退出代码 1：sh -c poetry run python3 src/generate_session.py [xxxxxx@qq.com](mailto:xxxxxx@qq.com) xxxxxxx Traceback（最近调用最后）：文件“/app/src/generate_session.py "，第 50 行，打印（登录（args.email，args.password））^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^ 文件“/app/src/generate_session.py”，第 19 行，登录 chatbot = Chatbot( ^^^^^^^^ 文件“/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3. 11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py”，第 62 行，在**初始化**self.refresh_session() 文件“/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py”，第 296 行，在 refresh_session raise exc 文件“/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py”，第 293 行，在 refresh_session self.login(self .config["email"], self.config["password"]) 文件 "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT /revChatGPT.py”，第 326 行，在登录中引发 exc 文件“/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py ”，第 319 行，在登录 auth.begin() 文件“/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py”，第 90 行，在 begin raise Exception("API error") Exception: API error
> > 账号密码部分以xxxxxxx隐藏
> 
> 这个NOPECHA_KEY和CAPTCHA_TOKEN如何设置


设置

> > 同样的错误
> 
> > 启动 GPT Bot Config 是：{"chatGPTAccountPool":[{"email":" [xxxxxx@qq.com](mailto:xxxxxx@qq.com) ","password":"xxxxxxx","isGoogleLogin":false}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword" :"ai"} uncaughtException 错误：命令失败，退出代码 1：sh -c poetry run python3 src/generate_session.py [xxxxxx@qq.com](mailto:xxxxxx@qq.com) xxxxxxx Traceback（最近调用最后）：文件“/app/src/generate_session.py "，第 50 行，打印（登录（args.email，args.password））^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^ 文件“/app/src/generate_session.py”，第 19 行，登录 chatbot = Chatbot( ^^^^^^^^ 文件“/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3. 11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py”，第 62 行，在**初始化**self.refresh_session() 文件“/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py”，第 296 行，在 refresh_session raise exc 文件“/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py”，第 293 行，在 refresh_session self.login(self .config["email"], self.config["password"]) 文件 "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT /revChatGPT.py”，第 326 行，在登录中引发 exc 文件“/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py ”，第 319 行，在登录 auth.begin() 文件“/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py”，第 90 行，在 begin raise Exception("API error") Exception: API error
> > 账号密码部分以xxxxxxx隐藏
> 
> 这个NOPECHA_KEY和CAPTCHA_TOKEN如何设置



docker run -d --name wechat-chatgpt -e CHAT_GPT_EMAIL=1694202@qq.com -e CHAT_GPT_PASSWORD=hysHYS5201314 -e CHAT_GPT_RETRY_TIMES=3 -e CHAT_PRIVATE_TRIGGER_KEYWORD=ai -e NOPECHA_KEY=pnemjttiehgvqgv0 -e CAPTCHA_TOKEN=48490d3b09958e240d5276418fd57ff7 -v $(pwd)/config.yaml:/app/config.yaml holegots/wechat-chatgpt:latest

> > same error
> 
> > Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"[xxxxxx@qq.com](mailto:xxxxxx@qq.com)","password":"xxxxxxx","isGoogleLogin":false}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":"ai"} uncaughtException Error: Command failed with exit code 1: sh -c poetry run python3 src/generate_session.py [xxxxxx@qq.com](mailto:xxxxxx@qq.com) xxxxxxx Traceback (most recent call last): File "/app/src/generate_session.py", line 50, in print(login(args.email, args.password)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/app/src/generate_session.py", line 19, in login chatbot = Chatbot( ^^^^^^^^ File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 62, in **init** self.refresh_session() File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 296, in refresh_session raise exc File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 293, in refresh_session self.login(self.config["email"], self.config["password"]) File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 326, in login raise exc File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 319, in login auth.begin() File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py", line 90, in begin raise Exception("API error") Exception: API error
> > 账号密码部分以xxxxxxx隐藏
> 
> 这个 NOPECHA_KEY 和 CAPTCHA_TOKEN 如何设置



docker run -d --name wechat-chatgpt -e NOPECHA_KEY=xxxxx -e CAPTCHA_TOKEN=xxxx -v $(pwd)/config.yaml:/app/config.yaml holegots/wechat-chatgpt:latest

启动时使用 -e
