### ISSUE TITLE
配置 OpenAI 的账户池后使用 NOPECHA_KEY 弹出报错

### ISSUE THREAD

**Issue by Yuban540540** [fuergaosi233/wechat-chatgpt#415]
initialized nopecha extension with key xxx
initialized nopecha extension with key xxx
TimeoutError: waiting for selector `#__next .btn-primary` failed: timeout 120000ms exceeded
    at new WaitTask (/home/ubuntu/wechat-chatgpt/node_modules/puppeteer/src/common/DOMWorld.ts:813:28)
    at DOMWorld.waitForSelectorInPage (/home/ubuntu/wechat-chatgpt/node_modules/puppeteer/src/common/DOMWorld.ts:656:22)
    at Object.internalHandler.waitFor (/home/ubuntu/wechat-chatgpt/node_modules/puppeteer/src/common/QueryHandler.ts:78:19)
    at DOMWorld.waitForSelector (/home/ubuntu/wechat-chatgpt/node_modules/puppeteer/src/common/DOMWorld.ts:511:25)
    at Frame.waitForSelector (/home/ubuntu/wechat-chatgpt/node_modules/puppeteer/src/common/FrameManager.ts:1290:47)
    at Page.waitForSelector (/home/ubuntu/wechat-chatgpt/node_modules/puppeteer/src/common/Page.ts:3222:29)
    at file:///home/ubuntu/wechat-chatgpt/node_modules/chatgpt/src/openai-auth.ts:115:14
    at file:///home/ubuntu/wechat-chatgpt/node_modules/chatgpt/src/openai-auth.ts:524:5
    at new Promise (<anonymous>)
    at waitForConditionOrAtCapacity (file:///home/ubuntu/wechat-chatgpt/node_modules/chatgpt/src/openai-auth.ts:502:10)

小白根据教程操作，项目部署完成后一个openao账户可以使用，多个会出现这个错误

**Comment by ruobingd** [comment]
同样的错误

**Comment by LFMJUN** [comment]
same error
1 account alse occur this error
