### ISSUE TITLE
启动项目时超时错误

### ISSUE THREAD

**Issue by 4F4C** [fuergaosi233/wechat-chatgpt#440]
请问我在启动项目时报下面这种错误是怎么回事？我的环境是ubuntu20，python3.8和nodejs18
TimeoutError: waiting for selector `#password` failed: timeout 180000ms exceeded
    at new WaitTask (/data/wechat-chatgpt/node_modules/puppeteer/src/common/DOMWorld.ts:813:28)
    at DOMWorld.waitForSelectorInPage (/data/wechat-chatgpt/node_modules/puppeteer/src/common/DOMWorld.ts:656:22)
    at Object.internalHandler.waitFor (/data/wechat-chatgpt/node_modules/puppeteer/src/common/QueryHandler.ts:78:19)
    at DOMWorld.waitForSelector (/data/wechat-chatgpt/node_modules/puppeteer/src/common/DOMWorld.ts:511:25)
    at Frame.waitForSelector (/data/wechat-chatgpt/node_modules/puppeteer/src/common/FrameManager.ts:1290:47)
    at Page.waitForSelector (/data/wechat-chatgpt/node_modules/puppeteer/src/common/Page.ts:3222:29)
    at getOpenAIAuth (file:///data/wechat-chatgpt/node_modules/chatgpt/src/openai-auth.ts:199:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ChatGPTAPIBrowser.initSession (file:///data/wechat-chatgpt/node_modules/chatgpt/src/chatgpt-api-browser.ts:162:24)
    at async file:///data/wechat-chatgpt/src/chatgpt.ts:72:11

**Comment by halleytl** [comment]
+1

**Comment by fuergaosi233** [comment]
Is the CAPTCHAS configured?

**Comment by A1069482459** [comment]
+1

**Comment by PelyDeng** [comment]
> Is the CAPTCHAS configured?

How to configure CAPTCHAS ?
