### ISSUE TITLE
Error: getaddrinfo ENOTFOUND webpush.wx2.qq.com

### ISSUE THREAD

**Issue by acheong08** [fuergaosi233/wechat-chatgpt#454]
```js
uncaughtException GError: getaddrinfo ENOTFOUND webpush.wx2.qq.com
    at Function.AxiosError.from (/home/acheong/workspace/wechat-chatgpt/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (/home/acheong/workspace/wechat-chatgpt/node_modules/axios/lib/adapters/http.js:518:25)
    at RedirectableRequest.emit (node:events:525:35)
    at RedirectableRequest.emit (node:domain:489:12)
    at ClientRequest.eventHandlers.<computed> (/home/acheong/workspace/wechat-chatgpt/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at ClientRequest.emit (node:domain:489:12)
    at TLSSocket.socketErrorListener (node:_http_client:490:9)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket.emit (node:domain:489:12) {
  code: 2,
  details: 'Error: getaddrinfo ENOTFOUND webpush.wx2.qq.com\n' +
    '    at Function.AxiosError.from (/home/acheong/workspace/wechat-chatgpt/node_modules/axios/lib/core/AxiosError.js:89:14)\n' +
    '    at RedirectableRequest.handleRequestError (/home/acheong/workspace/wechat-chatgpt/node_modules/axios/lib/adapters/http.js:518:25)\n' +
    '    at RedirectableRequest.emit (node:events:525:35)\n' +
    '    at RedirectableRequest.emit (node:domain:489:12)\n' +
    '    at ClientRequest.eventHandlers.<computed> (/home/acheong/workspace/wechat-chatgpt/node_modules/follow-redirects/index.js:14:24)\n' +
    '    at ClientRequest.emit (node:events:513:28)\n' +
    '    at ClientRequest.emit (node:domain:489:12)\n' +
    '    at TLSSocket.socketErrorListener (node:_http_client:490:9)\n' +
    '    at TLSSocket.emit (node:events:513:28)\n' +
    '    at TLSSocket.emit (node:domain:489:12)'
}
02:06:37 WARN PuppetWatchdogAgent start() reset() reason: {"data":"syncCheck()","timeoutMilliseconds":60000}
uncaughtException GError: WatchdogAgent reset: lastFood: "{"data":"syncCheck()","timeoutMilliseconds":60000}"
    at Watchdog.reset (file:///home/acheong/workspace/wechat-chatgpt/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)
    at Watchdog.emit (node:events:513:28)
    at Watchdog.emit (node:domain:489:12)
    at Timeout._onTimeout (file:///home/acheong/workspace/wechat-chatgpt/node_modules/watchdog/src/watchdog.ts:115:12)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7) {
  code: 2,
  details: 'Error: WatchdogAgent reset: lastFood: "{"data":"syncCheck()","timeoutMilliseconds":60000}"\n' +
    '    at Watchdog.reset (file:///home/acheong/workspace/wechat-chatgpt/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)\n' +
    '    at Watchdog.emit (node:events:513:28)\n' +
    '    at Watchdog.emit (node:domain:489:12)\n' +
    '    at Timeout._onTimeout (file:///home/acheong/workspace/wechat-chatgpt/node_modules/watchdog/src/watchdog.ts:115:12)\n' +
    '    at listOnTimeout (node:internal/timers:564:17)\n' +
    '    at processTimers (node:internal/timers:507:7)'
}
```

**Comment by fuergaosi233** [comment]
Trying to check DNS?

**Comment by acheong08** [comment]
Everything else seems to work. Maybe my VPN blocked the endpoint
