### ISSUE TITLE
在railway中出错railway

### ISSUE THREAD

**Issue by hadesya** [fuergaosi233/wechat-chatgpt#456]
[nodemon] app crashed - waiting for file changes before starting...

**Comment by jiayouxujin** [comment]
metoo

**Comment by starchou** [comment]
metoo  +1

**Comment by linkewei0580** [comment]
metoo +1

**Comment by linkewei0580** [comment]
> wechat-chatgpt@1.0.0 dev
> nodemon --exec node --watch config.yaml --loader ts-node/esm src/main.ts
[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): config.yaml
[nodemon] watching extensions: ts
[nodemon] starting `node --loader ts-node/esm src/main.ts`
(node:82) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"13701764610@163.com","password":"1370176lkw"}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":""}
Error: Navigation failed because browser has disconnected!
at /app/node_modules/puppeteer/src/common/LifecycleWatcher.ts:112:13
at /app/node_modules/puppeteer/vendor/mitt/src/index.ts:88:75
at Array.map (<anonymous>)
at Object.emit (/app/node_modules/puppeteer/vendor/mitt/src/index.ts:88:56)
at CDPSession.emit (/app/node_modules/puppeteer/src/common/EventEmitter.ts:102:18)
at CDPSession._onClosed (/app/node_modules/puppeteer/src/common/Connection.ts:355:10)
at Connection._onClose (/app/node_modules/puppeteer/src/common/Connection.ts:183:60)
at WebSocket.<anonymous> (/app/node_modules/puppeteer/src/node/NodeWebSocketTransport.ts:50:38)
at WebSocket.onClose (/app/node_modules/puppeteer/node_modules/ws/lib/event-target.js:210:18)
at WebSocket.emit (node:events:513:28)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by lishyeaaron** [comment]
same problem

**Comment by hx3333** [comment]
用railway部署也不行

**Comment by budongsir** [comment]
同样的问题

**Comment by eyaeya** [comment]
metoo！

**Comment by h3clikejava** [comment]
too me

**Comment by bianjiangjiangjiang** [comment]
谁有nopecha api啊，一起拼一个

**Comment by 854400656** [comment]
+1

**Comment by william20210206** [comment]
the same
