### ISSUE TITLE
TimeoutError: waiting for selector `button[data-provider="google"]` failed: timeout 180000ms exceeded

### ISSUE THREAD

**Issue by Darcy12138** [fuergaosi233/wechat-chatgpt#467]
最新的docker镜像在linux服务器启动报如标题所示的错误 该如何解决啊

**Comment by Darcy12138** [comment]
TimeoutError: waiting for selector `button[data-provider="google"]` failed: timeout 180000ms exceeded
    at new WaitTask (/app/node_modules/puppeteer/src/common/DOMWorld.ts:813:28)
    at DOMWorld.waitForSelectorInPage (/app/node_modules/puppeteer/src/common/DOMWorld.ts:656:22)
    at Object.internalHandler.waitFor (/app/node_modules/puppeteer/src/common/QueryHandler.ts:78:19)
    at DOMWorld.waitForSelector (/app/node_modules/puppeteer/src/common/DOMWorld.ts:511:25)
    at Frame.waitForSelector (/app/node_modules/puppeteer/src/common/FrameManager.ts:1290:47)
    at Page.waitForSelector (/app/node_modules/puppeteer/src/common/Page.ts:3222:29)
    at getOpenAIAuth (file:///app/node_modules/chatgpt/src/openai-auth.ts:143:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ChatGPTAPIBrowser.initSession (file:///app/node_modules/chatgpt/src/chatgpt-api-browser.ts:162:24)
    at async file:///app/src/chatgpt.ts:72:11
[nodemon] app crashed - waiting for file changes before starting...

**Comment by RealTong** [comment]
你应该是被CloudFlare人机验证挡住了, 过不了人机验证导致找不到google login的button元素

**Comment by lianghaohahh** [comment]
> CloudFlare

主动传一个 clearanceToken 试试
