### ISSUE TITLE
What is the problem

### ISSUE THREAD

**Issue by 94248** [fuergaosi233/wechat-chatgpt#469]
[nodemon] app crashed - waiting for file changes before starting...
Error: net::ERR_NAME_NOT_RESOLVED at https://chat.openai.com/auth/login
    at navigate (/app/node_modules/puppeteer/src/common/FrameManager.ts:218:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FrameManager.navigateFrame (/app/node_modules/puppeteer/src/common/FrameManager.ts:188:17)
    at async Frame.goto (/app/node_modules/puppeteer/src/common/FrameManager.ts:765:12)
    at async Page.goto (/app/node_modules/puppeteer/src/common/Page.ts:1766:12)
    at async getOpenAIAuth (file:///app/node_modules/chatgpt/src/openai-auth.ts:102:5)
    at async ChatGPTAPIBrowser.initSession (file:///app/node_modules/chatgpt/src/chatgpt-api-browser.ts:162:24)
    at async file:///app/src/chatgpt.ts:72:11
    at async Promise.all (index 0)
    at async ChatGPTPool.startPools (file:///app/src/chatgpt.ts:66:25)

**Comment by RealTong** [comment]
Please check your dns

**Comment by 94248** [comment]
> Please check your dns

Changing the DNS of the server still does not solve the problem

**Comment by 94248** [comment]
> 请检查你的dns

Change server DNS?
