### ISSUE TITLE
Railway部署报错

### ISSUE THREAD

**Issue by LesterDong** [fuergaosi233/wechat-chatgpt#473]
Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"my email","password":"my passwd"}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":"gpt"}
Error: Navigation failed because browser has disconnected!
at /app/node_modules/puppeteer/src/common/LifecycleWatcher.ts:112:13
at /app/node_modules/puppeteer/vendor/mitt/src/index.ts:88:75
at Array.map (<anonymous>)
at Object.emit (/app/node_modules/puppeteer/vendor/mitt/src/index.ts:88:56)
at CDPSession.emit (/app/node_modules/puppeteer/src/common/EventEmitter.ts:102:18)
at CDPSession._onClosed (/app/node_modules/puppeteer/src/common/Connection.ts:355:10)
at Connection._onClose (/app/node_modules/puppeteer/src/common/Connection.ts:183:60)
at WebSocket.<anonymous> (/app/node_modules/puppeteer/src/node/NodeWebSocketTransport.ts:50:38)
at WebSocket.onClose (/app/node_modules/puppeteer/node_modules/ws/lib/event-target.js:210:18)
at WebSocket.emit (node:events:513:28)

**Comment by RealTong** [comment]
Please check your dns

**Comment by h3clikejava** [comment]
一样 
Error: Protocol error (Page.addScriptToEvaluateOnNewDocument): Session closed. Most likely the page has been closed.
