### ISSUE TITLE
有大佬在吗，每次只能正常运行24h就报错了，Error: WatchdogAgent reset: lastFood: "{"data":"syncCheck()","timeoutMilliseconds":60000}"\n' +     '    at Watchdog.reset (file:///app/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)\

### ISSUE THREAD

**Issue by lianghaohahh** [fuergaosi233/wechat-chatgpt#479]
![image](https://user-images.githubusercontent.com/109569009/211231868-1f878ddf-4120-4ab7-83b7-2ac92cd6ed80.png)

**Comment by xuxiao-xx** [comment]
Same issue with the reporter.
Error trace:
`03:27:41 WARN PuppetWatchdogAgent start() reset() reason: {"data":"syncCheck()","timeoutMilliseconds":60000}
uncaughtException GError: WatchdogAgent reset: lastFood: "{"data":"syncCheck()","timeoutMilliseconds":60000}"
    at Watchdog.reset (file:///app/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)
    at Watchdog.emit (node:events:513:28)
    at Watchdog.emit (node:domain:489:12)
    at Timeout._onTimeout (file:///app/node_modules/watchdog/src/watchdog.ts:115:12)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7) {
  code: 2,
  details: 'Error: WatchdogAgent reset: lastFood: "{"data":"syncCheck()","timeoutMilliseconds":60000}"\n' +
    '    at Watchdog.reset (file:///app/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)\n' +
    '    at Watchdog.emit (node:events:513:28)\n' +
    '    at Watchdog.emit (node:domain:489:12)\n' +
    '    at Timeout._onTimeout (file:///app/node_modules/watchdog/src/watchdog.ts:115:12)\n' +
    '    at listOnTimeout (node:internal/timers:564:17)\n' +
    '    at processTimers (node:internal/timers:507:7)'
}
uncaughtException GError [AxiosError]: timeout of 60000ms exceeded
    at RedirectableRequest.handleRequestTimeout (/app/node_modules/axios/lib/adapters/http.js:555:16)
    at RedirectableRequest.emit (node:events:513:28)
    at RedirectableRequest.emit (node:domain:489:12)
    at Timeout.<anonymous> (/app/node_modules/follow-redirects/index.js:169:12)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7) {
  code: 2,
  details: 'AxiosError: timeout of 60000ms exceeded\n' +
    '    at RedirectableRequest.handleRequestTimeout (/app/node_modules/axios/lib/adapters/http.js:555:16)\n' +
    '    at RedirectableRequest.emit (node:events:513:28)\n' +
    '    at RedirectableRequest.emit (node:domain:489:12)\n' +
    '    at Timeout.<anonymous> (/app/node_modules/follow-redirects/index.js:169:12)\n' +
    '    at listOnTimeout (node:internal/timers:564:17)\n' +
    '    at processTimers (node:internal/timers:507:7)'
}`

**Comment by jiangaiming** [comment]
本地node环境跑，我也是这样，

**Comment by jiangaiming** [comment]
本地node环境跑，我也是这样，

**Comment by h3clikejava** [comment]
我也是这个情况，有大佬知道怎么解决吗？

**Comment by Lyq0055** [comment]
我也是这个情况，有大佬知道怎么解决吗？

**Comment by stevenQinwen** [comment]
解决了吗
