### ISSUE TITLE
No chatgpt account in pool

### ISSUE THREAD

**Issue by Radiationxuan** [fuergaosi233/wechat-chatgpt#480]
Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"xxxxxxxx@xxxx.com","password":"xxxxxxxxxx"}],"chatGptRetryTimes":10,"chatPrivateTiggerKeyword":"Hi"}
^
Error: ⚠️ No chatgpt account in pool
at ChatGPTPool.startPools (file:///app/src/chatgpt.ts:104:13)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at async ChatGPTBot.startGPTBot (file:///app/src/bot.ts:41:5)
at async main (file:///app/src/main.ts:16:3)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by getGitxxx** [comment]
the same issuer above :(

**Comment by Ice-Shine** [comment]
我也是这个问题，是不是不能使用微软账户登录的
I have the same problem.Can I login with Microsoft account?

**Comment by 94248** [comment]
+1

**Comment by ilusymon** [comment]
+1

**Comment by qwweerdf** [comment]
+1

**Comment by zyzlimit** [comment]
同样的问题，而且我也用了 2Captcha代理，应该不会是human验证不通过的原因。梯子也是全局的，ip也不是hk的。
那怎么回事呢，有没有大佬了解的。

**Comment by OnlyMeW** [comment]
同问。。。

**Comment by dreamingms** [comment]
同问

**Comment by TheBaldFighter** [comment]
me too, how to fix it?

**Comment by wenyu021** [comment]
Same problem when i use google login

**Comment by rgmyyw** [comment]
+1
