### ISSUE TITLE
[Error] ProtocolError: Protocol error (Page.addScriptToEvaluateOnNewDocument): Target closed.

### ISSUE THREAD

**Issue by JoonSumisu** [fuergaosi233/wechat-chatgpt#487]
ProtocolError: Protocol error (Page.addScriptToEvaluateOnNewDocument): Target closed.
at /app/node_modules/puppeteer/src/common/Connection.ts:304:16
at new Promise (<anonymous>)
at CDPSession.send (/app/node_modules/puppeteer/src/common/Connection.ts:300:12)
at Page.evaluateOnNewDocument (/app/node_modules/puppeteer/src/common/Page.ts:2599:24)
at ChatGPTAPIBrowser.initSession (file:///app/node_modules/chatgpt/src/chatgpt-api-browser.ts:148:18)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at async AsyncRetry.retries (file:///app/src/chatgpt.ts:75:13)
at async ChatGPTPool.startPools (file:///app/src/chatgpt.ts:73:9)
at async ChatGPTBot.startGPTBot (file:///app/src/bot.ts:41:5)
at async main (file:///app/src/main.ts:16:3) {
originalMessage: ''
}
[nodemon] app crashed - waiting for file changes before starting...
[nodemon] app crashed - waiting for file changes before starting...
}

**Comment by goushijie** [comment]
相同的问题，一直没有解决

**Comment by zdRan** [comment]
+1

**Comment by durongze** [comment]
+1
