### ISSUE TITLE
bot 回复 Error: No chatgpt session token

### ISSUE THREAD

**Issue by AmandaloveYang** [fuergaosi233/wechat-chatgpt#5]
Message: Message#Unknown[🗣Contact<chloe>]
Message: Message#Unknown[🗣Contact<chloe>]
Message: Message#Text[🗣Contact<chloe>@👥Room<杨永信电击诊疗室>]         @chloe 测速
receive message: @chloe 测速 from chloe in 杨永信电击诊疗室, room: @@551383a976ea00436eb2e6a45d5e689bebedd41eddd9c33d4f1b8864a3fe8270
Hit GPT Enabled Group: 杨永信电击诊疗室 in room: @@551383a976ea00436eb2e6a45d5e689bebedd41eddd9c33d4f1b8864a3fe8270
Error: No chatgpt session token
    at ChatGPTBot.get chatgpt [as chatgpt] (file:///D:/360%E6%9E%81%E9%80%9F%E6%B5%8F%E8%A7%88%E5%99%A8%E4%B8%8B%E8%BD%BD/wechat-chatgpt-main/wechat-chatgpt-main/src/chatgpt.ts:59:13)
    at ChatGPTBot.getGPTMessage (file:///D:/360%E6%9E%81%E9%80%9F%E6%B5%8F%E8%A7%88%E5%99%A8%E4%B8%8B%E8%BD%BD/wechat-chatgpt-main/wechat-chatgpt-main/src/chatgpt.ts:91:25)
    at ChatGPTBot.onMessage (file:///D:/360%E6%9E%81%E9%80%9F%E6%B5%8F%E8%A7%88%E5%99%A8%E4%B8%8B%E8%BD%BD/wechat-chatgpt-main/wechat-chatgpt-main/src/chatgpt.ts:122:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async WechatyImpl.<anonymous> (file:///D:/360%E6%9E%81%E9%80%9F%E6%B5%8F%E8%A7%88%E5%99%A8%E4%B8%8B%E8%BD%BD/wechat-chatgpt-main/wechat-chatgpt-main/src/main.ts:30:7)

**Comment by AmandaloveYang** [comment]
去看chatgpt的官方文档吗？

**Comment by AmandaloveYang** [comment]
> It looks like you failed to get the session_token for ChatGPT through the account password. You can configure the session_token directly by following the documentation.

去看chatgpt的官方文档吗？

**Comment by dianjiaogit** [comment]
> > It looks like you failed to get the session_token for ChatGPT through the account password. You can configure the session_token directly by following the documentation.
> 
> 去看chatgpt的官方文档吗？

项目的README里面有写到该如何获取并修改session_token
请参考https://github.com/fuergaosi233/wechat-chatgpt#b-use-session-token

**Comment by AmandaloveYang** [comment]
> > > It looks like you failed to get the session_token for ChatGPT through the account password. You can configure the session_token directly by following the documentation.
> > 
> > 
> > 去看chatgpt的官方文档吗？
> 
> 项目的README里面有写到该如何获取并修改session_token 请参考https://github.com/fuergaosi233/wechat-chatgpt#b-use-session-token

已解决！thanks！
