### ISSUE TITLE
新的问题

### ISSUE THREAD

**Issue by 94248** [fuergaosi233/wechat-chatgpt#502]
file:///app/src/chatgpt.ts:67
    for (const account of config.chatGPTAccountPool) {
                                 ^
TypeError: config.chatGPTAccountPool is not iterable
    at ChatGPTPool.startPools (file:///app/src/chatgpt.ts:67:34)
    at ChatGPTBot.startGPTBot (file:///app/src/bot.ts:41:28)
    at main (file:///app/src/main.ts:16:20)
    at file:///app/src/main.ts:52:1
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by shaoao110** [comment]
同问

**Comment by LinFallen** [comment]
how to solve it?

**Comment by tasyskybenjamin** [comment]
+1
