### ISSUE TITLE
用Docker部署后登陆验证码步骤报错：app crashed - waiting for file changes before starting...

### ISSUE THREAD

**Issue by OnlyMeW** [fuergaosi233/wechat-chatgpt#503]
启动容器：docker run   -e CAPTCHA_TOKEN="×××××××××××××××" -d --name wechat-chatgpt -v $(pwd)/config.yaml:/app/config.yaml holegots/wechat-chatgpt:latest
出现以下内容，请大佬帮忙。谢谢email和password文中用星号*代替

[nodemon] restarting due to changes...
[nodemon] starting `node --loader ts-node/esm src/main.ts`
(node:1263) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"********","password":"********","isGoogleLogin":false}],"chatGptRetryTimes":5,"chatPrivateTiggerKeyword":"Hi:","openAIProxy":""}
solving captchas using 2captcha...
captchas result {
  captchas: [
    {
      sitekey: '6Lc-wnQjAAAAADa5SPd68d0O3xmj0030uaVzpnXP',
      callback: 'callback',
      _vendor: 'recaptcha',
      id: 'c5d0b9ibb9yf',
      s: null,
      widgetId: 0,
      display: [Object],
      url: 'https://auth0.openai.com/u/login/identifier?state=hKFo2SAtenh6aUV6UWhXN1JrM1pGWHo3aldtYUo1TGpKQkhkUKFur3VuaXZlcnNhbC1sb2dpbqN0aWTZIHc3RHNCQWEwUDA0TDhVS1VXYS0tOXJUX3VVUkNURExlo2NpZNkgVGRKSWNiZTE2V29USHROOTVueXl3aDVFNHlPbzZJdEc',
      hasResponseElement: true,
      isEnterprise: true,
      isInViewport: true,
      isInvisible: false,
      _type: 'checkbox'
    }
  ],
  filtered: [],
  solutions: [
    {
      _vendor: 'recaptcha',
      provider: '2captcha',
      id: 'c5d0b9ibb9yf',
      requestAt: 2023-01-19T04:14:21.902Z,
      providerCaptchaId: '72624867331',
      text: '03AD1IbLAFMzCIsbp1YFKCYwWuLWUVQmBWYsfSeK9Oo9ILqEtn3AN27w1w8KN1TQ9NKLEOihTF4iFDgMXgC47QOU4oG6tW2VL_NlZysl-le8j0iZS224HMWpdCUKoUJkchMAsgQO2L4ebLtqgmn_h0CE-jyHRqUl5u0ZZgJRUwpn_J8h7gkRpMHAoyKzejunqde3oBW64xwmR3_hZ8UL5FHpYNmueG-HhwRI5l2L3W5c6R6Gg_AaBEO4vksZKqHeprpwR-DBYIvJFLxn8Nymfh2ly45CH6T_nm8806-P5T3-HZL9H4p91lEQCLfSh6NrMeepfxY4ozbTiixU4AY8ACjktRFshZk3T1k4_ei7YdNeV_ukSaN8HvYFsnq7ltdmK4wwbKBoCx8RvDvTDyZYp_FNrzcPnHNQn7u1NGJ73LF9A_q3Z6Akuxu_zhWsOLOPNwIdMrl3UUA9FRZ2_rBcHMmD87v0VKApD1H_dh6qDtNDmwPpUYIX3V5JXrrs7ZWwIarSKj1pLlq9JKw7AK5K0_wbashfNKmUMVaWPdmqU-qLnr5tv-rBbIy339VraJNicuQWCRjE0GWsClpI-CsYFI5ZkiEF20WxCc2FpXvmcIWIl3tOE69DltMdZImOJmG5wXETUL05NGirOhTHPtuiB7MONUgxUTb4T7B1yQps9B84xQ7cxBps6jY2zjzhrzyUNOuyg3GBd2HGZbsBzdKgVD7EKu99RgMYpNQxM20r-ahvFFeGZlhdK7OLx67sw_rUcn6eJuG30aPepuyeJBQp4nMCh2CVd62uzPYqm7qbAZQT17e3PcGbm3Lb0uczbYx5AUZHM0pKGMBnpwPXUlf8Fk7IY4pk1n0uvQIBwzXkBrETXee0wMCFhHPSVPxLUGmVsAs4BJFz-iL65RH_r_F9ew2blD9yVnx0xlOaIrvuY5LDfCCfClpXU8j3yQfq8Eh3ohAY3ZLYdPr4ksQGbE4NDQ9-B1LL3L_6zG7QrwTLSl1tJq_uFmFq64BHYFSRSGWBNFutuZOVuIcTRsK7DIxBa_KWYmg4Z3l7oI-zU4_UJOsD6oBqRlfK229-jarag887ehiDJm-xg0NOEixcUWVEzVdtj_IDMrjEUaJAD7kWEuf_QsjJgbucboDNHzFUNUXUd9nVhgLx4bm0wCVv4tbq_b0XSDonX9PXp8Wvogn-FS2N_EUFmMB0pf34ymF-jNw6usdDoW80CNhAJuKbLRWh_srpCl1BjVhfkNI_W-Bn-C_HJ-RnQxHeCRh7rVsZegr5gdiJs1l2GXaXLxAB4ESuwP3i-AFu203RD-WH-nFek_2-3DGfT4xzMla27TOn7kaoh1xdbcNIERqUgysLDjBuAbT6xrNakUITxxNH8whR-a52l0GRyiR01U1qLqRwqaKQXQFb1-Rkrw3ZtkfD3qmNF0Td1RDs-5Q605ADbG6xzzIQtmMzBS5O2qtIglHacKYa8DgAmbnAR-fpS-NYwiA6EJfW1sJ85A8oFulbTB07LleQOcesKjO9vZI-oqqNCW5jX5V4nSQzb6mgUSllahH3jC9tLW29bP1wrL-CnrWEv3AKgOJuphFECrG8oR-AF1b23Z5sxB1bKBXt9S2O_0BK1CMgFESdNRG_NLgEyTR1MOCAZrv_D8NjipQuLMDhzK2VhuYRGrVdlp4AIubNc9LiMgU0ab5Sdh28E_mA',
      responseAt: 2023-01-19T04:14:26.067Z,
      hasSolution: true,
      duration: 4.165
    }
  ],
  solved: [
    {
      _vendor: 'recaptcha',
      id: 'c5d0b9ibb9yf',
      responseElement: true,
      responseCallback: true,
      isSolved: true,
      solvedAt: {}
    }
  ],
  error: undefined
}
solving captchas using 2captcha...
captchas result {
  captchas: [
    {
      sitekey: '6Lc-wnQjAAAAADa5SPd68d0O3xmj0030uaVzpnXP',
      callback: 'callback',
      _vendor: 'recaptcha',
      id: 'bfp2u4a952gk',
      s: null,
      widgetId: 0,
      display: [Object],
      url: 'https://auth0.openai.com/u/login/identifier?state=hKFo2SBfbkZmVHY4ZDlCRXZZREVZX2FGcllfS3J2aXl1NTdqdKFur3VuaXZlcnNhbC1sb2dpbqN0aWTZIERoUHdDQ1BKZWRTRUJ4b3VrR1hoUmRXR3B1d0ZsWlJHo2NpZNkgVGRKSWNiZTE2V29USHROOTVueXl3aDVFNHlPbzZJdEc',
      hasResponseElement: true,
      isEnterprise: true,
      isInViewport: true,
      isInvisible: false,
      _type: 'checkbox'
    }
  ],
  filtered: [],
  solutions: [
    {
      _vendor: 'recaptcha',
      provider: '2captcha',
      id: 'bfp2u4a952gk',
      requestAt: 2023-01-19T04:14:51.502Z,
      providerCaptchaId: '72624870952',
      text: '03AD1IbLAtROE5t3ZC1iymjwZfMr6P0fiWS8E5HyM9kfXikRIAqcdw5oFslofhXYqil_sC9FB-rfMdeYyVtrcpRXEYRHtDpWJ30ySHSw6AbVPuCSDdQ7QrDURNeIqyaTucPDRoeJmh_GMGaEJw0oDuMIeAe__C0ZWMy1cj4u2FW5NBKBslJ28XWZnIXXpM7iBIjDWilFsx_5y2uuTZe5sfpnO8MFFSpqQtK0B7xT_L9j_8iIHqogWpPAvPpXf5wM_a-zRqL_bwVMYAx-iWR0V-lf_Yl0TeTVJmmz0aj-a5xGNSuutXT6NtchtD3CgSsDezLJ9788vjyhkzT3OnE9BQX7RgQhOHjmw7FK43WZCJUpg3KlGJcVQRb_B2XicanGoC-4fU-WCaNnlpuAwfPzMeHzFqLspKgBnktSDYFeW5x1BDGWHaoIEiN80WzXlLHiXwns2-Px50URS82PFasKhkSWv1-bA1EEiylyJm6FsSvh8pTz0UmEPPplLP_t85Xvg7yQgyXvsfPyNqER1ZNPaAQmRDW-QkUD_op9vQWnmPFJ0nXzN2cy2zCeS9CMIU064a6DGh1r5geOORzajs9SHh6qdxyogPbOG4DCNtUrXfAdMuoBYwgP5WdJEQqn6s2xU1LqklBhpFPYPsI9y_deep1xIZ7sSs0BgrBTjtyOlwRLIz0ThtTo9dk7Nnv_pm7x6E7X6QX71esaPDBzPCPuRIei9Zz6jIOEbsBcl7EyInw0xhtq5jHijQBPjSU8sFnqS80odkKqkgO3r-qgbPX84wEttrhV238Q_p5RZgI-CATlXRYkKl8pzPBfuHzcXcbTm6g55sknkmylJ__iVmS9Ve9nV44RUzSheueRxgVLlDLbILy1JDJ1QALFQLmXBU08nCmSTUbHgjNNRUoSl-dhv0ocbcqKtKPMyB9Vf6FO1mZJ7qt-yCjsy86XWctWRmEu4n6VaQfUdD1oKSsr2fcy37webWGkWXZaAgU-aIUAr0uX0xn8e_IAOOI5nph9V1d5Y6BQAarcGemJPa59I9njC9Z2E4_gkGJgdt-_Cj2NtdoO12nCJIqHA5uatK3xv0dVDyCChY-Vue4DSUSwd_9vIQVQSkOuxFofmlCX3x1f8YbBNsnHbUnBvlo8nJ7yu1BftYFPldg_MDoKB_Karza_EdXRUueoX1xqaG5HXghJW6iOzHJxoPorni6zi6nTLfzq71iDN8O1d3xPazuCeX-u-lCzq0ODSkhtndtCs4OeT-96FE2JXSAIjeKtQ3D0qjsRXJmjZfE0GCcQQ5UqIPpNIdrJeusUF9sM8-5Uktu2iWQHHLUgq2NrlRlJgU5mHqS6ND4fokodPetR8v1CTlKwc8mr9k4sM-cDRVP_MNCr5F1JwGDFtC4pKzN_SnAizgsYEsipW5PeizPEAy3uPRi1xXDU3yZxKYjIK8JzPmJZF7zgBx3DARzcU4tyH1sC7-iRaQb8QWlIjJ5ifL0a1t-Lxecx-TzjAm5_ZzeMVUr6SfIWcXyvL0BPDEDXdWNUTkcdZtfkZ0DKy5-6i6EBollxrIjkq86gWIv0oecx9Rez2sIMXzT4fc-fPY1LjfnsMN9jJVbAer-uNcps4UwnRtZviCmmO594Sh_PFKjTuutyGLXH-pkPpfjL4qtfRnQhjp19gVtxRorjcbQXm4YOs67NBPohLbJdPxQRH5cyXUawD23MTvI9BROWv3V7_3SllFlJZEkCA6N3Qr9B0S',
      responseAt: 2023-01-19T04:14:54.760Z,
      hasSolution: true,
      duration: 3.258
    }
  ],
  solved: [
    {
      _vendor: 'recaptcha',
      id: 'bfp2u4a952gk',
      responseElement: true,
      responseCallback: true,
      isSolved: true,
      solvedAt: {}
    }
  ],
  error: undefined
}
solving captchas using 2captcha...
captchas result {
  captchas: [
    {
      sitekey: '6Lc-wnQjAAAAADa5SPd68d0O3xmj0030uaVzpnXP',
      callback: 'callback',
      _vendor: 'recaptcha',
      id: 'erf1ephwnys0',
      s: null,
      widgetId: 0,
      display: [Object],
      url: 'https://auth0.openai.com/u/login/identifier?state=hKFo2SBzcGM4RHVpTXJBa1hiRjN2eGxIQm4tZXFXVjRsdG94T6Fur3VuaXZlcnNhbC1sb2dpbqN0aWTZIGd1YmJreTdLbHBEeW9saU1YZUszclRsdG5LS2hUdVFIo2NpZNkgVGRKSWNiZTE2V29USHROOTVueXl3aDVFNHlPbzZJdEc',
      hasResponseElement: true,
      isEnterprise: true,
      isInViewport: true,
      isInvisible: false,
      _type: 'checkbox'
    }
  ],
  filtered: [],
  solutions: [
    {
      _vendor: 'recaptcha',
      provider: '2captcha',
      id: 'erf1ephwnys0',
      requestAt: 2023-01-19T04:15:24.073Z,
      providerCaptchaId: '72624874856',
      text: '03AD1IbLBeQcDcV3BpZ2js3WcqnbkiJmjXMga1SDHTDxmff0KK67PD6Jcja__jS3CbjgjKBhXYMHgkGbkZD-SnxnIqLu4pNs3V5WQlUKxQJIHMFCAo6_80slPi_wx8buuAwd9bnF0oAefnl5NE6HcmhVdPH38QI6VlU_qEV2QHgpAebJYtkOxc8yRA3V4auJgRVcQ7z7zg8Ie0XMTTTbBVIrSTQF-n-kz1uF1e0bT1iMqmoL_Hy9xkeW7n7eODbbSfbqx8v3xkdfATKB25pCtBDcQjAudhfRYIMcJ2276bkZuruVevtJq7M9wkGWQlhnk1itUHZmUM4JNpQZO0UchB3cn5-7_tyv_jhE7Zmeff-qDLWc0e-1MCZFgLxAYSodmhZacALKe6jjkqh9n9glD2ldNL2Ocl4m30NyPfO1tsQIdXwmhPc2Y-aGRJ7Sf0KsLQ4b-JbGfceujiHuMXrEGlOhjPFQN7jFVfgqrywg-Qt2aP28s5mjV4LdsSiLMXRwrNATQK-mkdXkjUBnPT5wEotYLe2hmynRiiBdff046VbVzrRQfGb5XwcLLAEtfU154osgmmQN8q7hQv31S1deOTXMLHFhlG2wGyr55Arl7mkAhy89CdncEkmsWn0HQBMN62xjJ1_TEJiF6ap3DO_o-KDpiYzy4ct-CSGeuXxgNxRWvxweGkSWDNzaMpLSAzw6oJbwpxw1ZYdAWR1guqgLN6dwFK4yXYQG0hW1ZnY-HpaixzjjMRZJbAeorvXCNa_l5ilLPZE9kQkQFFNPARznMFkcTOyRxB60tKEnbKzIjn3pc3jZwJmBjn6VcrcqoCXOq70gtjuQxVS4T4UHMZ7nW3OIQLyl_RiwwxgwNG3O8Q0-R9N00XnylmtvoOZxDXvsNylQ4B9UUoTbi1viMKbTIQR95zMKL4nRbJ2uK6bdbIkEhV61Q3ZJK7Vcbj1Z7n7nqQEdfbj_jlgxpvrAeBGDpQkDrOXzLoaDwap4IL-4NGbA9noYqcK_Zn9I_4ELCGAMqnKrWpoq4sgFc9haxomtQCnONk6i3VOa5Zc_MqshFCC-TzaZ5gvPbUMCr_uBZyjd5_W6lSJFylLjF9IBx9G9G0Dw49Ec-QxJ5jJqExGpHnPZqyg3djeLanUv2wlnjAx8DPqJBvL-_w0gEsEYlDwWUFXwgq9L--Lt0SQ3ZcdTgcDMA1SMpdWIV8P9dO5k1-ph3HEYFPrRvamfTNIyt-A0ZIXklRhFCe_OMXmL2wOF2Mk_fAmkZSX4hyLYhWPCRwAqStMPjSTexfaV0uUk6hdW8z1xM1Ue-9NDXBSD4WoRCO5B30CxTV-BAMt67jUC8JBvBEYQP7_s3n8QUMUmvJLbQ0F4grt20tWtfn-hYe_M8w2lrvua2IIzzgQhlcK2pNL2nRR0HnM980Wd0MYoW8HcblmfzN79vMWrwQyA_Ut8txU4LRuyoMtE7c5yRaQqBkVBRyghGHzUd1pxpFVw6ZGChAHisrDE3xhMBOlyrPmkPR-DTySQERUKbn1iV-3tBgfXgGLf2sZGkYn9q7xSODdJqPTOmE8GTXrIXOKxk7PmGMDST3xr-LeUbscLOMwLLX0ZWz0EePzKDdyqg4w_YVUoy6wnJiWvheY2f8B9_yHGPUir3dLifGcYnD5LChR5M9Kv0TYf_Yjxc8DPK_eINC64CWAjV11Wr9pPO3pG-R6jmdtLasxXkCJZ6wPQ5YECmYINDEhLztEZazryl2oCEO6y315W7uFHjjKt72EA',
      responseAt: 2023-01-19T04:15:27.323Z,
      hasSolution: true,
      duration: 3.25
    }
  ],
  solved: [
    {
      _vendor: 'recaptcha',
      id: 'erf1ephwnys0',
      responseElement: true,
      responseCallback: true,
      isSolved: true,
      solvedAt: {}
    }
  ],
  error: undefined
}
solving captchas using 2captcha...
captchas result {
  captchas: [
    {
      sitekey: '6Lc-wnQjAAAAADa5SPd68d0O3xmj0030uaVzpnXP',
      callback: 'callback',
      _vendor: 'recaptcha',
      id: 'wzfyglxbd7bh',
      s: null,
      widgetId: 0,
      display: [Object],
      url: 'https://auth0.openai.com/u/login/identifier?state=hKFo2SBueTd6dTJ2VDFva2ctYnBJQWFmazZzQnFYLWdvYThQSqFur3VuaXZlcnNhbC1sb2dpbqN0aWTZIFgtSTFsZzMzUnY4OXFBUHBzbHhHNHI5ZG9tTmtXNk9qo2NpZNkgVGRKSWNiZTE2V29USHROOTVueXl3aDVFNHlPbzZJdEc',
      hasResponseElement: true,
      isEnterprise: true,
      isInViewport: true,
      isInvisible: false,
      _type: 'checkbox'
    }
  ],
  filtered: [],
  solutions: [
    {
      _vendor: 'recaptcha',
      provider: '2captcha',
      id: 'wzfyglxbd7bh',
      requestAt: 2023-01-19T04:16:03.245Z,
      providerCaptchaId: '72624879113',
      text: '03AD1IbLDx2U5-qPa6M1z_Oy1EK5aZUxoW4Q5Lb7CuRoYH4BrUcksD3s4PHa6ksh2q2yei4L7q_3FD1kMb3rOE8p8KiaozmMeaPZ_vkJnUr3enWkRx40l1fTAtJngFx7MJKIq401o_zLs86Y9WnOr33nnVNwu17wmDzOcAUTo8q3OTzx8eXJmGhDC9pBt7If5OyC_5lsjWCJiZ8hVufygbkmLTOQYwJ7LC9hJtXK5jHw3WvPe3RzMqEhJ3S7-yVFb7H-r6KdFtDU-Qy87OjkiWL7Optxgvvn2Jste_K8fZb_y98z1FrWESKdktLpwtAatjOcBTb6BJ6L4E4UR3-egTePTpfBFJmVmYZLkgz3Hnme79ZnLEwZBUweHkzW3Cv260yZZKd5RcKmeJ2oZkswjhrvKf0Kvr7Xkb8suMaT5nRixBLxBTgfzVfMdnN6wU7h4b3t7UDqxCQruKsGiXUarQcumnTGfEjIDC-InBNMCISbsv5dGHYtaLCpB6P4IzlkKGtnlRAsrv1jZE8hsGUeLNgQ-v3lp4VXeWTV0oKXWBH_Fm0xjhYpa4xyTlaRc_2o-wnBkjBQbSPgaGMTpJWrB3iU_ssEt-Iua648tAOBLA8T-Bl_wXhVB-elsjbxQaUEexLjWifVP4hjex33L_DVh2awEcAEOlif_NI3oebkuj90V-CJ91BCUEFtD0FSZDW1_Wc0PNY5l7iH9Oij1pjKMyO8ojKVjXHwBpI10EUxseZ8LgvmelVVAZ0333ukLHwWX66QkpDpck3vQaqG-p0hgmfl8keDKyLvO5vGMiv4KlUX6D7GxBs1xElXX6cl--nqHC8EVsAzo2Jh0XO1Oesy4medqjNWj6yRJSoSgr8kRZQfxRNuhAz-6UEVRh0fGLlPwWRkqBi41NGU6LH7RmKRfKBtDSz47nsdG5IXrOcx1vMP7XXBrny0AxopDz3p8qrYhasiwhhFEM6gMwOPxLoAKR8KKbpG5OiQsPVH-ISKRj4hDr1Yr1qPjSeafEqr70OPC2qo-IbgngIfYmaTZ10FnQQCF6CJyKg-FrT5SiHQMtlg6YVP44cxul2FZ8lBYJcjN0qfME7sGRX0WbhlmAPg92X3hTsJpxKeBjez5fgPknSSWlXTwJ3Ki08d1p9R4_Bhm7gZkdC72IxwafSfHcCk2X6DJxLsi7Eu-IUJ55rMDAlehgB02btlzF3DaCAbJJl4ckiNi_32HuHXM6B17nHBxfsPxwwxjL4EmYe2M_BviOChlWy1I6-5R_2SHJcOt9ChKoOWUnWA0Ifw1t8UmBAEWHcEidWVIFwT4tJQHSFzaxlcKo4WPTMCGH3AA4NjSA6fX1dL_hKUz9sA4ZQr51NxXCzyZvJW2ek39LuOYHb2ts5XSy1D1vRtLUQADtKdNNl3gLUYh9mvaKw_FOYuc4IrwNYh19In2yIxKkWAPyUP3XfXxE9u2b4mYA_04Y-ITsA4l5cTLB7vSKHfGxSipsZeB_im8hTP97fdLNZTjeQSxqCOsLXrP9Vrt1IaP8l4-7u24bZ36QbNyphzPlUeZSQuVygJZJZguMP1qlpGSN9mBvKF8CsLgJdWEBWxiFd6yrJBNHYbZsYDO8qj79Di1NIgyJALX-jlN7gX1clUdfKrOREBzp_xZ8-6OzxLjV87PyeXfYsvOXj1n2xQXlgetmlGX-PhmbcPJSdmRtxkpguzfBF7VqUwPCgaLtZDsmOz7WKOvTIb875vPQwXPC',
      responseAt: 2023-01-19T04:16:06.465Z,
      hasSolution: true,
      duration: 3.22
    }
  ],
  solved: [
    {
      _vendor: 'recaptcha',
      id: 'wzfyglxbd7bh',
      responseElement: true,
      responseCallback: true,
      isSolved: true,
      solvedAt: {}
    }
  ],
  error: undefined
}
Try init account: ******** failed, remove it from pool
file:///app/src/chatgpt.ts:104
      throw new Error("⚠ No chatgpt account in pool");
            ^
Error: ⚠ No chatgpt account in pool
    at ChatGPTPool.startPools (file:///app/src/chatgpt.ts:104:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ChatGPTBot.startGPTBot (file:///app/src/bot.ts:41:5)
    at async main (file:///app/src/main.ts:16:3)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by OnlyMeW** [comment]
重试了很多次了，换服务器也试过，没有成功过一次。无奈之下才求助，希望大佬指导一下。感谢
