### ISSUE TITLE
求助：docker能运行，npm不能运行，报错

### ISSUE THREAD

**Issue by budongsir** [fuergaosi233/wechat-chatgpt#507]
## docker方式运行一切正常，同样的配置npm运行提示：

```shell
(Use `node --trace-warnings ...` to show where the warning was created)
Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"eleksvz@gmail.com","password":"xxx","isGoogleLogin":false}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":"","openAIProxy":""}
Try init account: eleksvz@gmail.co failed, remove it from pool
file:///root/wechat-chatgpt/src/chatgpt.ts:104
      throw new Error("⚠️ No chatgpt account in pool");
            ^
Error: ⚠️ No chatgpt account in pool
    at ChatGPTPool.startPools (file:///root/wechat-chatgpt/src/chatgpt.ts:104:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ChatGPTBot.startGPTBot (file:///root/wechat-chatgpt/src/bot.ts:41:5)
    at async main (file:///root/wechat-chatgpt/src/main.ts:16:3)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by thechen130** [comment]
请问docker怎么配置啊

**Comment by xianrui69** [comment]
同样报错 +1 等一个后续

**Comment by Jay-Z-zhang** [comment]
+1

**Comment by dryl90** [comment]
默认的chrome启动地址在C:\Program Files\Google\Chrome\Application
如果没有不能唤起chrome
