### ISSUE TITLE
docker 启动 初始化账号失败

### ISSUE THREAD

**Issue by ferrymo** [fuergaosi233/wechat-chatgpt#515]
**启动时已通过 -e指定CAPTCHA_TOKEN（获取的session token）,**
### 以下为启动命令参照
`
docker run -d --name wechat-chatgpt -e CAPTCHA_TOKEN="xxxxx" -v D:\project\GitHub\wechat-chatgpt/config.yaml:/app/config.yaml holegots/wechat-chatgpt
`

### 以下为运行日志

```
> wechat-chatgpt@1.0.0 dev
> nodemon --exec node --watch config.yaml --loader ts-node/esm src/main.ts

[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): config.yaml
[nodemon] watching extensions: ts
[nodemon] starting `node --loader ts-node/esm src/main.ts`
(node:58) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"XXXX","password":"XXXX","isGoogleLogin":false}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":"","openAIProxy":""}
solving captchas using 2captcha...
no captchas found
no captchas found
no captchas found
solving captchas using 2captcha...
no captchas found
no captchas found
no captchas found
solving captchas using 2captcha...
no captchas found
no captchas found
no captchas found
solving captchas using 2captcha...
no captchas found
no captchas found
no captchas found
Try init account: XXXXX@XXX.cn failed, remove it from pool
file:///app/src/chatgpt.ts:104
      throw new Error("⚠️ No chatgpt account in pool");
            ^
Error: ⚠️ No chatgpt account in pool
    at ChatGPTPool.startPools (file:///app/src/chatgpt.ts:104:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ChatGPTBot.startGPTBot (file:///app/src/bot.ts:41:5)
    at async main (file:///app/src/main.ts:16:3)
```

**Comment by ferrymo** [comment]
@fuergaosi233  老哥能帮忙看看嘛，是啥原因

**Comment by hx3333** [comment]
这个有人解决了吗？能帮看一下不

**Comment by SGreenHand** [comment]
俺也一样

**Comment by xiuzigege** [comment]
俺也一样

**Comment by zxy1124** [comment]
大佬解决了吗
