### ISSUE TITLE
app crashed - waiting for file changes before starting...

### ISSUE THREAD

**Issue by Zuco1111** [fuergaosi233/wechat-chatgpt#520]
阿里云新加坡服务器，查看logs的时候一直提示app crashed，重装也试过了，使用的是
`docker run -d --name wechat-chatgpt -v $(pwd)/config.yaml:/app/config.yaml --entrypoint '/bin/sh' holegots/wechat-chatgpt:latest -c 'xvfb-run --auto-servernum --server-num=1 npm run dev'`

> wechat-chatgpt@1.0.0 dev
> nodemon --exec node --watch config.yaml --loader ts-node/esm src/main.ts

[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): config.yaml
[nodemon] watching extensions: ts
[nodemon] starting `node --loader ts-node/esm src/main.ts`
(node:52) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"xxxx@gmail.com","password":"xxxxxxxx","isGoogleLogin":false}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":"","openAIProxy":""}
Killed
[nodemon] app crashed - waiting for file changes before starting...

**Comment by kwonsolomon** [comment]
xd解决了吗

**Comment by ls20vip** [comment]
我也遇到了，它打开浏览器之后又快速的把浏览器给关闭了

**Comment by ShinoKana** [comment]
same

**Comment by xianrui69** [comment]
make

**Comment by alexzhong001** [comment]
wechat-chatgpt@1.0.0 dev
﻿> nodemon --exec node --watch config.yaml --loader ts-node/esm src/main.ts
﻿[nodemon] 2.0.20
﻿[nodemon] to restart at any time, enter `rs`
﻿[nodemon] watching path(s): config.yaml
﻿[nodemon] watching extensions: ts
﻿[nodemon] starting `node --loader ts-node/esm src/main.ts`
﻿(node:82) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
﻿(Use `node --trace-warnings ...` to show where the warning was created)
﻿Start GPT Bot Config is:{"chatGPTAccountPool":[{"email”:”xxxx@hotmail.com","password":"hxxxxxx”}],”chatGptRetryTimes":10,"chatPrivateTiggerKeyword":""}
﻿ProtocolError: Protocol error (Page.addScriptToEvaluateOnNewDocument): Target closed.
﻿at /app/node_modules/puppeteer/src/common/Connection.ts:304:16
﻿at new Promise (<anonymous>)
﻿at CDPSession.send (/app/node_modules/puppeteer/src/common/Connection.ts:300:12)
﻿at Page.evaluateOnNewDocument (/app/node_modules/puppeteer/src/common/Page.ts:2599:24)
﻿at ChatGPTAPIBrowser.initSession (file:///app/node_modules/chatgpt/src/chatgpt-api-browser.ts:153:18)
﻿at processTicksAndRejections (node:internal/process/task_queues:95:5)
﻿at async AsyncRetry.retries (file:///app/src/chatgpt.ts:75:13)
﻿at async ChatGPTPool.startPools (file:///app/src/chatgpt.ts:73:9)
﻿at async ChatGPTBot.startGPTBot (file:///app/src/bot.ts:41:5)
﻿at async main (file:///app/src/main.ts:16:3) {
﻿originalMessage: ''
﻿}
﻿[nodemon] app crashed - waiting for file changes before starting...

It seems that the problem is persisting.

**Comment by goushijie** [comment]
same

**Comment by DichPoon** [comment]
一样的错误

**Comment by Zuco1111** [comment]
更新，可能是脚本中Wechaty出了点问题，我今天在用Wechaty的时候是同样的报错，正在找解决方案
Update. Maybe there is something wrong in Wechaty. I met the same problem int Wechaty.

**Comment by OG-beep** [comment]
same

**Comment by lpflhh** [comment]
> 我也遇到了，它打开浏览器之后又快速的把浏览器给关闭了

你是怎么看到ta的操作的？你能进入容器内部看到图形界面吗？能否说一下步骤呀？
