### ISSUE TITLE
大哥大姐们，帮帮忙，两天了还是没解决

### ISSUE THREAD

**Issue by dryl90** [fuergaosi233/wechat-chatgpt#535]
**通过该方法启动，在2CAPTCHA充值了3美刀，并拿到了tokenapi，容器的terminal中测试了可正常访问chatgpt官网**

docker run -d --name wechat-chatgpt2 -e CAPTCHA_TOKEN="xxxxxxxxxx" -v $(pwd)/config.yaml:/app/config.yaml holegots/wechat-chatgpt:latest

**日志如下**

_2023-02-05 12:20:48 
2023-02-05 12:20:48 > wechat-chatgpt@1.0.0 dev
2023-02-05 12:20:48 > nodemon --exec node --watch config.yaml --loader ts-node/esm src/main.ts
2023-02-05 12:20:48 
2023-02-05 12:20:48 [nodemon] 2.0.20
2023-02-05 12:20:48 [nodemon] to restart at any time, enter `rs`
2023-02-05 12:20:48 [nodemon] watching path(s): config.yaml
2023-02-05 12:20:48 [nodemon] watching extensions: ts
2023-02-05 12:20:48 [nodemon] starting `node --loader ts-node/esm src/main.ts`
2023-02-05 12:20:51 Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"xxxxxx","password":"xxxx","isGoogleLogin":false}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":"","openAIProxy":""}
2023-02-05 12:20:48 (node:74) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
2023-02-05 12:20:48 (Use `node --trace-warnings ...` to show where the warning was created)_

**上面这个日志会卡很久，然后几分钟后就会出现如下报错，npm run dev 也会有相同的错误**

_Try init account: XXXXX failed, remove it from pool
file:///D:/applcation/chatgpt/wechat-chatgpt/src/chatgpt.ts:105
      throw new Error("⚠️ No chatgpt account in pool");
            ^
Error: ⚠️ No chatgpt account in pool
    at ChatGPTPool.startPools (file:///D:/applcation/chatgpt/wechat-chatgpt/src/chatgpt.ts:105:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ChatGPTBot.startGPTBot (file:///D:/applcation/chatgpt/wechat-chatgpt/src/bot.ts:41:5)
    at async main (file:///D:/applcation/chatgpt/wechat-chatgpt/src/main.ts:16:3)_

**Comment by dryl90** [comment]
npm run dev 可以启动机器人了，原因是代码中默认的chrome地址与我实际的chrome地址不匹配，导致chrome启动不起来。

**Comment by dryl90** [comment]
> npm run dev 可以启动机器人了，原因是代码中默认的chrome地址与我实际的chrome地址不匹配，导致chrome启动不起来。 但又出现了两个其他问题 **（1）error 400； An error ocurred. Try refreshing your browser （2）每次重启都会发历史消息，造成刷屏。**

第二个问题，删除wechat-assistant.memory-card文件可以解决

**Comment by Diaoest-Mian** [comment]
> npm run dev 可以启动机器人了，原因是代码中默认的chrome地址与我实际的chrome地址不匹配，导致chrome启动不起来。 但又出现了两个其他问题 **（1）error 400； An error ocurred. Try refreshing your browser （2）每次重启都会发历史消息，造成刷屏。**

大哥，你400的问题是咋解决的

**Comment by joeyijun** [comment]
> **通过该方法启动，在2CAPTCHA充值了3美刀，并拿到了tokenapi，容器的terminal中测试了可正常访问chatgpt官网**
> 
> docker run -d --name wechat-chatgpt2 -e CAPTCHA_TOKEN="xxxxxxxxxx" -v $(pwd)/config.yaml:/app/config.yaml holegots/wechat-chatgpt:latest
> 
> **日志如下**
> 
> _2023-02-05 12:20:48 2023-02-05 12:20:48 > wechat-chatgpt@1.0.0 dev 2023-02-05 12:20:48 > nodemon --exec node --watch config.yaml --loader ts-node/esm src/main.ts 2023-02-05 12:20:48 2023-02-05 12:20:48 [nodemon] 2.0.20 2023-02-05 12:20:48 [nodemon] to restart at any time, enter `rs` 2023-02-05 12:20:48 [nodemon] watching path(s): config.yaml 2023-02-05 12:20:48 [nodemon] watching extensions: ts 2023-02-05 12:20:48 [nodemon] starting `node --loader ts-node/esm src/main.ts` 2023-02-05 12:20:51 Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"xxxxxx","password":"xxxx","isGoogleLogin":false}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":"","openAIProxy":""} 2023-02-05 12:20:48 (node:74) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time 2023-02-05 12:20:48 (Use `node --trace-warnings ...` to show where the warning was created)_
> 
> **上面这个日志会卡很久，然后几分钟后就会出现如下报错，npm run dev 也会有相同的错误**
> 
> _Try init account: XXXXX failed, remove it from pool file:///D:/applcation/chatgpt/wechat-chatgpt/src/chatgpt.ts:105 throw new Error("⚠️ No chatgpt account in pool"); ^ Error: ⚠️ No chatgpt account in pool at ChatGPTPool.startPools (file:///D:/applcation/chatgpt/wechat-chatgpt/src/chatgpt.ts:105:13) at processTicksAndRejections (node:internal/process/task_queues:95:5) at async ChatGPTBot.startGPTBot (file:///D:/applcation/chatgpt/wechat-chatgpt/src/bot.ts:41:5) at async main (file:///D:/applcation/chatgpt/wechat-chatgpt/src/main.ts:16:3)_

我也是这样，不知道哪出问题了

**Comment by dryl90** [comment]
400的问题没解决，等大佬解答



丁冉






---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年02月05日 23:56 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [fuergaosi233/wechat-chatgpt] 大哥大姐们，帮帮忙，两天了还是没解决 (Issue #535) |

npm run dev 可以启动机器人了，原因是代码中默认的chrome地址与我实际的chrome地址不匹配，导致chrome启动不起来。 但又出现了两个其他问题 （1）error 400； An error ocurred. Try refreshing your browser （2）每次重启都会发历史消息，造成刷屏。

大哥，你400的问题是咋解决的

**Comment by dreamfly32** [comment]
https://github.com/fuergaosi233/wechat-chatgpt/issues/488

**Comment by goushijie** [comment]
不是稳定版本？什么时候发布一个稳定版本

**Comment by helperAI** [comment]
我也是报这个错误。也在2CAPTCHA充值了3美刀。

> nodemon --exec node --watch config.yaml --loader ts-node/esm src/main.ts
[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): config.yaml
[nodemon] watching extensions: ts
[nodemon] starting `node --loader ts-node/esm src/main.ts`
[nodemon] Internal watch failed: ENOSPC: System limit for number of file watchers reached, watch '/app/docs/images/railway-deployment.png'
(node:82) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by ranjie211** [comment]
> 

大佬 这个代码默认地址与实际地址不匹配怎么解决啊 代码的默认地址在哪里看啊
