### ISSUE TITLE
日志中没有验证码

### ISSUE THREAD

**Issue by intna** [fuergaosi233/wechat-chatgpt#542]
我这是美国硅谷的腾讯云服务器，2核，跑起来没有验证码。。

**Comment by intna** [comment]
过一会儿就报
Error: ⚠️ No chatgpt account in pool
    at ChatGPTPool.startPools (file:///app/src/chatgpt.ts:104:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ChatGPTBot.startGPTBot (file:///app/src/bot.ts:41:5)
    at async main (file:///app/src/main.ts:16:3)

**Comment by BmYy0203** [comment]
一样的问题

**Comment by goushijie** [comment]
一样的问题，开发还没有解决
