### ISSUE TITLE
google账号登录拿到api-key 填到session-token里面，email和password为空 不能使用

### ISSUE THREAD

**Issue by leonlei** [fuergaosi233/wechat-chatgpt#560]
(node:82) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Start GPT Bot Config is:{"chatGPTAccountPool":[{}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":"@bot"}
file:///app/node_modules/chatgpt/src/chatgpt-api-browser.ts:121
const error = new types.ChatGPTError('ChatGPT invalid email')
^
ChatGPTError: ChatGPT invalid email
at new ChatGPTAPIBrowser (file:///app/node_modules/chatgpt/src/chatgpt-api-browser.ts:121:21)
at ChatGPTPool.startPools (file:///app/src/chatgpt.ts:68:23)
at ChatGPTBot.startGPTBot (file:///app/src/bot.ts:41:28)
at main (file:///app/src/main.ts:16:20)
at file:///app/src/main.ts:52:1
at ModuleJob.run (node:internal/modules/esm/module_job:193:25) {
statusCode: 401
}

**Comment by dreamfly32** [comment]
api-key不能用，目前只能用账号密码

**Comment by leonlei** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by xiehui999** [comment]
谷歌账号登录的好想没有设置密码的地方， 意思是授权登录的这种就没办法看了

**Comment by dreamfly32** [comment]
> 谷歌账号登录的好想没有设置密码的地方， 意思是授权登录的这种就没办法看了

配置文件填写谷歌账号密码，isGoogleLogin设置为true

**Comment by liuzexiazbx** [comment]
> > 谷歌账号登录的好想没有设置密码的地方， 意思是授权登录的这种就没办法看了
> 
> 配置文件填写谷歌账号密码，isGoogleLogin设置为true
测试了这样不行的，还是提示ChatGPTError: ChatGPT invalid password
    at new ChatGPTAPIBrowser (file:///E:/wechat-chatgpt-main/node_modules/chatgpt/src/chatgpt-api-browser.ts:127:21)
    at ChatGPTPool.startPools (file:///E:/wechat-chatgpt-main/src/chatgpt.ts:68:23)
    at ChatGPTBot.startGPTBot (file:///E:/wechat-chatgpt-main/src/bot.ts:41:28)
    at main (file:///E:/wechat-chatgpt-main/src/main.ts:16:20)
    at file:///E:/wechat-chatgpt-main/src/main.ts:52:1
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  statusCode: 401
}

**Comment by chyzzz** [comment]
> > 谷歌账号登录的好想没有设置密码的地方， 意思是授权登录的这种就没办法看了
> 
> 配置文件填写谷歌账号密码，isGoogleLogin设置为true

那我用Railway部署的有什么办法设置isGoogleLogin吗？

**Comment by HiJackXD** [comment]
现在仅仅是配置文件里有这么一行，实际代码里没用到，没有相关google登录的逻辑

**Comment by GitSarp** [comment]
难受啊，飞。我也是谷歌登录不上去

**Comment by leonlei** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
