### ISSUE TITLE
微信扫码登录的错误提示

### ISSUE THREAD

**Issue by eyaeya** [fuergaosi233/wechat-chatgpt#59]
当我用微信扫码登录时，提示如下信息：

uncaughtException AssertionError [ERR_ASSERTION]: 1 == 0                                                                                          
    at Object.equal (/app/node_modules/wechat4u/src/util/global.js:53:14)                                                                         
    at /app/node_modules/wechat4u/src/core.js:195:16                                                                                              
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {                                                                       
  code: 2,                                                                                                                                        
  details: 'AssertionError [ERR_ASSERTION]: 1 == 0\n' +                                                                                           
    '    at Object.equal (/app/node_modules/wechat4u/src/util/global.js:53:14)\n' +                                                               
    '    at /app/node_modules/wechat4u/src/core.js:195:16\n' +                                                                                    
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'                                                                   
}  

我猜测，这可能与我的微信号或腾讯安全机制有关，但我不确定（因这是我新申请的账号）。如果有可行的解法，还请告知。

**Comment by mofang1104** [comment]
和我的错误一样

**Comment by HandsomeWu6** [comment]
微信需要实名认证 @eyaeya

**Comment by eyaeya** [comment]
> 微信需要实名认证 @eyaeya

成功了！！感谢！！
