### ISSUE TITLE
配置完config.yaml后运行docker后log里面二维码出不来，报错

### ISSUE THREAD

**Issue by Fuxkyou** [fuergaosi233/wechat-chatgpt#591]
docker logs 错误信息如下：
Try init account: ********@gmail.com failed, remove it from pool
file:///app/src/chatgpt.ts:104
      throw new Error("?? No chatgpt account in pool");
            ^
Error: ?? No chatgpt account in pool
    at ChatGPTPool.startPools (file:///app/src/chatgpt.ts:104:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ChatGPTBot.startGPTBot (file:///app/src/bot.ts:41:5)
    at async main (file:///app/src/main.ts:16:3)
[nodemon] app crashed - waiting for file changes before starting...

配置文件如下：
chatGPTAccountPool:
  - email: "*****@gmail.com"
    password: "****"
    isGoogleLogin: false
    SessionToken:  ***
chatPrivateTiggerKeyword: ""
openAIProxy: ""

**Comment by fuergaosi233** [comment]
看起来登录失败了🤔

**Comment by bearofcode** [comment]
同样，通过Railway部署也是报错，但是账号在网页上是能正常登录的

**Comment by linelee02** [comment]
xvfb-run: error: Xvfb failed to start

**Comment by xiusen0515** [comment]
> xvfb-run: error: Xvfb failed to start

docker restart wechat-chatgpt

**Comment by durongze** [comment]
现在应该是报这个吧？
ProtocolError: Protocol error (Page.addScriptToEvaluateOnNewDocument): Target closed.
    at /app/node_modules/puppeteer/src/common/Connection.ts:304:16
    at new Promise (<anonymous>)
    at CDPSession.send (/app/node_modules/puppeteer/src/common/Connection.ts:300:12)
    at Page.evaluateOnNewDocument (/app/node_modules/puppeteer/src/common/Page.ts:2599:24)
    at ChatGPTAPIBrowser.initSession (file:///app/node_modules/chatgpt/src/chatgpt-api-browser.ts:148:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AsyncRetry.retries (file:///app/src/chatgpt.ts:75:13)
    at async ChatGPTPool.startPools (file:///app/src/chatgpt.ts:73:9)
    at async ChatGPTBot.startGPTBot (file:///app/src/bot.ts:41:5)
    at async main (file:///app/src/main.ts:16:3) {
  originalMessage: ''

**Comment by Fuxkyou** [comment]
> > xvfb-run: error: Xvfb failed to start
> 
> docker restart wechat-chatgpt

xvfb failed to start is after restart docker.
The docker network curl openai.com  is  OK. 
maybe is docker images not good ?need to change the dockerfile to rebuild ?

**Comment by 1459244936** [comment]
为什么不用填api的
