### ISSUE TITLE
docker run之后出现如下错误

### ISSUE THREAD

**Issue by crazyCrabs** [fuergaosi233/wechat-chatgpt#66]
uncaughtException GError: getaddrinfo EAI_AGAIN login.wx.qq.com
    at Function.AxiosError.from (/app/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (/app/node_modules/axios/lib/adapters/http.js:518:25)
    at RedirectableRequest.emit (node:events:525:35)
    at RedirectableRequest.emit (node:domain:489:12)
    at ClientRequest.eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at ClientRequest.emit (node:domain:489:12)
    at TLSSocket.socketErrorListener (node:_http_client:494:9)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket.emit (node:domain:489:12) {
  code: 2,
  details: 'Error: getaddrinfo EAI_AGAIN login.wx.qq.com\n' +
    '    at Function.AxiosError.from (/app/node_modules/axios/lib/core/AxiosError.js:89:14)\n' +
    '    at RedirectableRequest.handleRequestError (/app/node_modules/axios/lib/adapters/http.js:518:25)\n' +
    '    at RedirectableRequest.emit (node:events:525:35)\n' +
    '    at RedirectableRequest.emit (node:domain:489:12)\n' +
    '    at ClientRequest.eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:14:24)\n' +
    '    at ClientRequest.emit (node:events:513:28)\n' +
    '    at ClientRequest.emit (node:domain:489:12)\n' +
    '    at TLSSocket.socketErrorListener (node:_http_client:494:9)\n' +
    '    at TLSSocket.emit (node:events:513:28)\n' +
    '    at TLSSocket.emit (node:domain:489:12)'
}

**Comment by crazyCrabs** [comment]
网络问题，docke run的时候加上  --network=host 即可

**Comment by fuergaosi233** [comment]
I think it's your DNS configuration problem.
