### ISSUE TITLE
No chatgpt account in pool

### ISSUE THREAD

**Issue by rgmyyw** [fuergaosi233/wechat-chatgpt#671]
开始是卡主start 哪里, 后面重新部署, 又一直报错

使用`railway` 部署,  各种key 和人机校验的key 都已经添加

```sh
file:///app/src/chatgpt.ts:104
throw new Error("⚠️ No chatgpt account in pool");
^
Error: ⚠️ No chatgpt account in pool
at ChatGPTPool.startPools (file:///app/src/chatgpt.ts:104:13)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at async ChatGPTBot.startGPTBot (file:///app/src/bot.ts:50:5)
at async main (file:///app/src/main.ts:17:3)
[nodemon] app crashed - waiting for file changes before starting...

```

**Comment by lpflhh** [comment]
一样的错误

**Comment by vanslee** [comment]
应该是docker容器没有配置代理,你只是宿主机使用了代理,

**Comment by lpflhh** [comment]
> 应该是docker容器没有配置代理,你只是宿主机使用了代理,

vps在美国本土，不需要代理也能开openai官网的

**Comment by NicoXu-npc** [comment]
我也一样 这该咋办 只会用railway这样的部署方式qwq

**Comment by longchena** [comment]
遇到一样的问题

**Comment by penggu** [comment]
遇到同样问题。我用的也是railway方式。是只有这种方式才出问题吗？
