### ISSUE TITLE
求解答

### ISSUE THREAD

**Issue by hyliunain** [fuergaosi233/wechat-chatgpt#673]
Try init account: xxxxxxxxxx@qq.com failed, remove it from pool
file:///app/src/chatgpt.ts:104
      throw new Error("⚠️ No chatgpt account in pool");
            ^
Error: ⚠️ No chatgpt account in pool
    at ChatGPTPool.startPools (file:///app/src/chatgpt.ts:104:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ChatGPTBot.startGPTBot (file:///app/src/bot.ts:41:5)
    at async main (file:///app/src/main.ts:12:3)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by gxy8221450** [comment]
相同问题

**Comment by Chrisluo4570** [comment]
+1
