### ISSUE TITLE
uncaughtException TypeError: config.chatGPTAccountPool.map is not a function

### ISSUE THREAD

**Issue by AmandaloveYang** [fuergaosi233/wechat-chatgpt#7]
当我扫码登录之后
User Contact<chloe> logged in
uncaughtException TypeError: config.chatGPTAccountPool.map is not a function
    at ChatGPTBot.startGPTBot (file:///D:/learn%E2%80%94%E2%80%94vue/wechat-chatgpt-main/wechat-chatgpt-main/src/chatgpt.ts:41:35)
    at WechatyImpl.<anonymous> (file:///D:/learn%E2%80%94%E2%80%94vue/wechat-chatgpt-main/wechat-chatgpt-main/src/main.ts:21:22)
    at WechatyImpl.emit (node:events:527:28)
    at WechatyImpl.emit (node:domain:475:12)
    at WechatyImpl.emit (file:///D:/learn%E2%80%94%E2%80%94vue/wechat-chatgpt-main/wechat-chatgpt-main/node_modules/wechaty/src/wechaty-mixins/gerror-mixin.ts:44:22)
    at PuppetWechat4u.<anonymous> (file:///D:/learn%E2%80%94%E2%80%94vue/wechat-chatgpt-main/wechat-chatgpt-main/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:246:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Message: Message#Unknown[🗣Contact<chloe>]

**Comment by AmandaloveYang** [comment]
解决了，感谢大佬的源码！

**Comment by xcc3641** [comment]
请问如何解决的？我也遇到这个问题。
