### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by zhou-yi-git** [fuergaosi233/wechat-chatgpt#709]
触发问答之后报错
🎯 Triggered ChatGPT: 小G Railway是什么
TypeError: Cannot read properties of undefined (reading '0')
at file:///app/src/chatgpt.ts:25:35
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at async ChatGPTBot.getGPTMessage (file:///app/src/bot.ts:68:12)
at async ChatGPTBot.onPrivateMessage (file:///app/src/bot.ts:129:24)
at async ChatGPTBot.onMessage (file:///app/src/bot.ts:155:16)
at async WechatyImpl.<anonymous> (file:///app/src/main.ts:32:9)

**Comment by RealTong** [comment]
Some error https://github.com/fuergaosi233/wechat-chatgpt/issues/707 .

试试 chatgpt-api 分支

**Comment by zzqxztc** [comment]
> Same error #707 .
> 
> 可以检查一下api key对不对, 还是账号的API是不是被ban了
> 
> 在 #708 解决了

并没有
Railway的还是报这个错

**Comment by hanszaishengzhang** [comment]
> 这个

+1

**Comment by hanszaishengzhang** [comment]
Railway的还是报这个错

**Comment by zzqxztc** [comment]
> 切换一下分支吧用chat-api分支

我的不知道为啥不回复，已经切换分支重新部署....
