### ISSUE TITLE
报错如下，请问是啥没弄好吗？

### ISSUE THREAD

**Issue by Windrunner20** [fuergaosi233/wechat-chatgpt#720]
ReferenceError: fetch is not defined
    at sendMessage (file:///root/wechat-chatgpt/src/chatgpt.ts:7:22)
    at ChatGPTBot.getGPTMessage (file:///root/wechat-chatgpt/src/bot.ts:68:18)
    at ChatGPTBot.onPrivateMessage (file:///root/wechat-chatgpt/src/bot.ts:129:35)
    at ChatGPTBot.onMessage (file:///root/wechat-chatgpt/src/bot.ts:155:27)
    at WechatyImpl.<anonymous> (file:///root/wechat-chatgpt/src/main.ts:32:26)
    at WechatyImpl.emit (node:events:513:28)
    at WechatyImpl.emit (node:domain:489:12)
    at WechatyImpl.emit (file:///root/wechat-chatgpt/node_modules/wechaty/src/wechaty-mixins/gerror-mixin.ts:44:22)
    at PuppetWechat4u.<anonymous> (file:///root/wechat-chatgpt/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:281:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by RealTong** [comment]
换个比较新的nodejs版本试试
