### ISSUE TITLE
啥时候能更新到GPT4呀，直接改名字好像不行。

### ISSUE THREAD

**Issue by AfterForst** [fuergaosi233/wechat-chatgpt#722]
我直接修改的    -e MODEL="gpt-4" \
但是发送信息的话就会报错无反应。
TypeError: Cannot read properties of undefined (reading '0')
    at file:///app/src/chatgpt.ts:25:35
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ChatGPTBot.getGPTMessage (file:///app/src/bot.ts:68:12)
    at async ChatGPTBot.onPrivateMessage (file:///app/src/bot.ts:129:24)
    at async ChatGPTBot.onMessage (file:///app/src/bot.ts:155:16)
    at async WechatyImpl.<anonymous> (file:///app/src/main.ts:32:9)

想请教一下各位大佬。

**Comment by RealTong** [comment]
GPT-4的API需要等待waitlist . 
目前开发者也没拿到测试机会. 我们在等到有合适的方案会第一时间跟进
