### ISSUE TITLE
node版本已经升到最新，但还是报错TypeError: fetch failed

### ISSUE THREAD

**Issue by hhl1022** [fuergaosi233/wechat-chatgpt#723]
请问如何判断网络是否有问题呢？

**Comment by RealTong** [comment]
The information provided is not sufficient to determine what the problem is. 
Please add logs

**Comment by Hai-kaizhi** [comment]
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async sendMessage (file:///F:/chatGPT/wechat-chatgpt-main/src/chatgpt.ts:7:22)
    at async ChatGPTBot.getGPTMessage (file:///F:/chatGPT/wechat-chatgpt-main/src/bot.ts:68:12)    
    at async ChatGPTBot.onPrivateMessage (file:///F:/chatGPT/wechat-chatgpt-main/src/bot.ts:129:24)
    at async ChatGPTBot.onMessage (file:///F:/chatGPT/wechat-chatgpt-main/src/bot.ts:155:16)       
    at async WechatyImpl.<anonymous> (file:///F:/chatGPT/wechat-chatgpt-main/src/main.ts:32:9) {   
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (node:internal/deps/undici/undici:8380:28)
      at node:internal/deps/undici/undici:8338:50
      at Immediate._onImmediate (node:internal/deps/undici/undici:8367:37)
      at processImmediate (node:internal/timers:476:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}
node是最新版，开了科技，还是这个错误

**Comment by RealTong** [comment]
'UND_ERR_CONNECT_TIMEOUT' 代理还是有问题.

建议不要和GFW作斗争, 直接使用Railway或者反代API
