### ISSUE TITLE
无法使用，TypeError: fetch failed，用了全局翻墙也用不了

### ISSUE THREAD

**Issue by yiouyou** [fuergaosi233/wechat-chatgpt#730]
```
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async sendMessage (file:///E:/_Ai/wechat-chatgpt/src/chatgpt.ts:7:22)
    at async ChatGPTBot.getGPTMessage (file:///E:/_Ai/wechat-chatgpt/src/bot.ts:68:12)
    at async ChatGPTBot.onPrivateMessage (file:///E:/_Ai/wechat-chatgpt/src/bot.ts:129:24)        
    at async ChatGPTBot.onMessage (file:///E:/_Ai/wechat-chatgpt/src/bot.ts:155:16)
    at async WechatyImpl.<anonymous> (file:///E:/_Ai/wechat-chatgpt/src/main.ts:32:9) {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (node:internal/deps/undici/undici:8380:28)
      at node:internal/deps/undici/undici:8338:50
      at Immediate._onImmediate (node:internal/deps/undici/undici:8367:37)
      at processImmediate (node:internal/timers:476:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}
```

**Comment by RealTong** [comment]
Please check your network. Or please reverse proxy the API yourself.
https://github.com/fuergaosi233/openai-proxy
