### ISSUE TITLE
node最新版，但是报错TypeError: fetch failed

### ISSUE THREAD

**Issue by Hai-kaizhi** [fuergaosi233/wechat-chatgpt#737]
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async sendMessage (file:///F:/chatGPT/wechat-chatgpt-main/src/chatgpt.ts:7:22)
    at async ChatGPTBot.getGPTMessage (file:///F:/chatGPT/wechat-chatgpt-main/src/bot.ts:68:12)    
    at async ChatGPTBot.onPrivateMessage (file:///F:/chatGPT/wechat-chatgpt-main/src/bot.ts:129:24)
    at async ChatGPTBot.onMessage (file:///F:/chatGPT/wechat-chatgpt-main/src/bot.ts:155:16)       
    at async WechatyImpl.<anonymous> (file:///F:/chatGPT/wechat-chatgpt-main/src/main.ts:32:9) {   
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (node:internal/deps/undici/undici:8380:28)
      at node:internal/deps/undici/undici:8338:50
      at Immediate._onImmediate (node:internal/deps/undici/undici:8367:37)
      at processImmediate (node:internal/timers:476:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}

**Comment by huweidong** [comment]
老哥  我跟你的一样  请问有解吗？

**Comment by dontry** [comment]
你确认你的node是19吗？可以用`nvm install 19`下载并切换。fetch这个模块是18以后才有的

**Comment by Hai-kaizhi** [comment]
> 

还是一样，刚刚切换到19了，还是报这个错：
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11457:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async sendMessage (file:///F:/chatGPT/wechat-chatgpt-main/src/chatgpt.ts:7:22)
    at async ChatGPTBot.getGPTMessage (file:///F:/chatGPT/wechat-chatgpt-main/src/bot.ts:68:12)
    at async ChatGPTBot.onPrivateMessage (file:///F:/chatGPT/wechat-chatgpt-main/src/bot.ts:129:24)
    at async ChatGPTBot.onMessage (file:///F:/chatGPT/wechat-chatgpt-main/src/bot.ts:155:16)
    at async WechatyImpl.<anonymous> (file:///F:/chatGPT/wechat-chatgpt-main/src/main.ts:32:9) {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (node:internal/deps/undici/undici:8422:28)
      at node:internal/deps/undici/undici:8380:50
      at Immediate._onImmediate (node:internal/deps/undici/undici:8409:37)
      at processImmediate (node:internal/timers:478:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}
哥，你是搞好了吗，我想问一下你这里配置文件的文件名就是：'.env'  吗？，里面是不是只用添加一个key就行，需要梯子吗，我用过梯子没有区别

**Comment by Hai-kaizhi** [comment]
> 老哥 我跟你的一样 请问有解吗？

没有啊！！用了梯子也一样，奇了个怪

**Comment by dontry** [comment]
> > 
> 
> 还是一样，刚刚切换到19了，还是报这个错： TypeError: fetch failed at Object.fetch (node:internal/deps/undici/undici:11457:11) at processTicksAndRejections (node:internal/process/task_queues:95:5) at async sendMessage (file:///F:/chatGPT/wechat-chatgpt-main/src/chatgpt.ts:7:22) at async ChatGPTBot.getGPTMessage (file:///F:/chatGPT/wechat-chatgpt-main/src/bot.ts:68:12) at async ChatGPTBot.onPrivateMessage (file:///F:/chatGPT/wechat-chatgpt-main/src/bot.ts:129:24) at async ChatGPTBot.onMessage (file:///F:/chatGPT/wechat-chatgpt-main/src/bot.ts:155:16) at async WechatyImpl. (file:///F:/chatGPT/wechat-chatgpt-main/src/main.ts:32:9) { cause: ConnectTimeoutError: Connect Timeout Error at onConnectTimeout (node:internal/deps/undici/undici:8422:28) at node:internal/deps/undici/undici:8380:50 at Immediate._onImmediate (node:internal/deps/undici/undici:8409:37) at processImmediate (node:internal/timers:478:21) { code: 'UND_ERR_CONNECT_TIMEOUT' } } 哥，你是搞好了吗，我想问一下你这里配置文件的文件名就是：'.env' 吗？，里面是不是只用添加一个key就行，需要梯子吗，我用过梯子没有区别

“UND_ERR_CONNECT_TIMEOUT“ 这个连接超时错误可能和梯子有关。

**Comment by RealTong** [comment]
@Hai-kaizhi @huweidong 
Please check your network.
你的代理软件可能只支持浏览器翻墙.  请确认代理是否设置成功, 或者启用增强模式 https://docs.cfw.lbyczf.com/contents/tun.html

**Comment by huweidong** [comment]
@Hai-kaizhi 是网络的问题 你看看你访问https://api.openai.com/v1  会不会被拒绝，会被拒绝就会出现这个错误了，我换了个vpn就可以了
