### ISSUE TITLE
ReferenceError: fetch is not defined

### ISSUE THREAD

**Issue by huweidong** [fuergaosi233/wechat-chatgpt#739]
User Contact<皓白> logged in
🎯 Sat Mar 18 2023 00:52:05 GMT+0800 (中国标准时间) Message: Message#Unknown[🗣Contact<皓白>]	
🎯 Sat Mar 18 2023 00:52:07 GMT+0800 (中国标准时间) Message: Message#Unknown[🗣Contact<皓白>]	
🎯 Sat Mar 18 2023 00:52:19 GMT+0800 (中国标准时间) Message: Message#Text[🗣Contact<憧lv憬>]	你好
🎯 Triggered ChatGPT: 你好
ReferenceError: fetch is not defined
    at sendMessage (file:///Users/hwd/Desktop/ChatGPT/wechat-chatgpt/src/chatgpt.ts:7:22)
    at ChatGPTBot.getGPTMessage (file:///Users/hwd/Desktop/ChatGPT/wechat-chatgpt/src/bot.ts:68:18)
    at ChatGPTBot.onPrivateMessage (file:///Users/hwd/Desktop/ChatGPT/wechat-chatgpt/src/bot.ts:129:35)
    at ChatGPTBot.onMessage (file:///Users/hwd/Desktop/ChatGPT/wechat-chatgpt/src/bot.ts:155:27)
    at WechatyImpl.<anonymous> (file:///Users/hwd/Desktop/ChatGPT/wechat-chatgpt/src/main.ts:32:26)
    at WechatyImpl.emit (node:events:527:28)
    at WechatyImpl.emit (node:domain:475:12)
    at WechatyImpl.emit (file:///Users/hwd/Desktop/ChatGPT/wechat-chatgpt/node_modules/wechaty/src/wechaty-mixins/gerror-mixin.ts:44:22)
    at PuppetWechat4u.<anonymous> (file:///Users/hwd/Desktop/ChatGPT/wechat-chatgpt/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:281:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    

node --version
v17.6.0
你好，我用node跑起来报这个错误，请问是需要升级node的版本吗？

**Comment by huweidong** [comment]
node版本问题
