### ISSUE TITLE
经常发生超时错误

### ISSUE THREAD

**Issue by dontry** [fuergaosi233/wechat-chatgpt#741]
我在本地使用node运行会经常发生超时错误。请问有解决方法吗？
```
uncaughtException GError: WatchdogAgent reset: lastFood: "{"data":"syncCheck()","timeoutMilliseconds":60000}"
    at Watchdog.reset (file:///Users/dongc/Documents/side-projects/wechat-chatgpt/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)
    at Watchdog.emit (node:events:512:28)
    at Watchdog.emit (node:domain:489:12)
    at Timeout._onTimeout (file:///Users/dongc/Documents/side-projects/wechat-chatgpt/node_modules/watchdog/src/watchdog.ts:115:12)
    at listOnTimeout (node:internal/timers:573:17)
    at processTimers (node:internal/timers:514:7) {
  code: 2,
  details: 'Error: WatchdogAgent reset: lastFood: "{"data":"syncCheck()","timeoutMilliseconds":60000}"\n' +
    '    at Watchdog.reset (file:///Users/dongc/Documents/side-projects/wechat-chatgpt/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)\n' +
    '    at Watchdog.emit (node:events:512:28)\n' +
    '    at Watchdog.emit (node:domain:489:12)\n' +
    '    at Timeout._onTimeout (file:///Users/dongc/Documents/side-projects/wechat-chatgpt/node_modules/watchdog/src/watchdog.ts:115:12)\n' +
    '    at listOnTimeout (node:internal/timers:573:17)\n' +
    '    at processTimers (node:internal/timers:514:7)'
}
uncaughtException GError [AxiosError]: timeout of 60000ms exceeded
    at RedirectableRequest.handleRequestTimeout (/Users/dongc/Documents/side-projects/wechat-chatgpt/node_modules/axios/lib/adapters/http.js:555:16)
    at RedirectableRequest.emit (node:events:512:28)
    at RedirectableRequest.emit (node:domain:489:12)
    at Timeout.<anonymous> (/Users/dongc/Documents/side-projects/wechat-chatgpt/node_modules/follow-redirects/index.js:169:12)
    at listOnTimeout (node:internal/timers:573:17)
    at processTimers (node:internal/timers:514:7) {
  code: 2,
  details: 'AxiosError: timeout of 60000ms exceeded\n' +
    '    at RedirectableRequest.handleRequestTimeout (/Users/dongc/Documents/side-projects/wechat-chatgpt/node_modules/axios/lib/adapters/http.js:555:16)\n' +
    '    at RedirectableRequest.emit (node:events:512:28)\n' +
    '    at RedirectableRequest.emit (node:domain:489:12)\n' +
    '    at Timeout.<anonymous> (/Users/dongc/Documents/side-projects/wechat-chatgpt/node_modules/follow-redirects/index.js:169:12)\n' +
    '    at listOnTimeout (node:internal/timers:573:17)\n' +
    '    at processTimers (node:internal/timers:514:7)'
}
```

**Comment by damonxz** [comment]
同问，运行一段时间就挂掉了，再也无法触发

**Comment by RealTong** [comment]
免费版本只能这样. 
否则可以尝试付费 https://wechaty.js.org/docs/puppet-services/  和 padlocal
