### ISSUE TITLE
Use with nodejs时出现如下错误，使用的是chatgpt-api分支。使用docker部署main则可以正常使用

### ISSUE THREAD

**Issue by zyl132** [fuergaosi233/wechat-chatgpt#748]
![屏幕截图 2023-03-19 132309](https://user-images.githubusercontent.com/64294605/226155496-68e859d7-313f-403a-a7c3-331e816bb695.png)
Error
    at WechatifiedUserClass.listener (file:///wechat-chatgpt/node_modules/wechaty/src/user-modules/message.ts:344:21)
    at PuppetWechat4u.<anonymous> (file:///wechat-chatgpt/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:284:38)

**Comment by zyl132** [comment]
🤵 Contact: attention 💬 Text: 你好
🎯 Triggered ChatGPT: 你好
ChatGPT MESSages:  [
  { role: 'system', content: '你是专家' },
  { role: 'user', content: '你好' }
]
05:20:33 WARN Message listener() payload.listenerId should be set! See: https://github.com/wechaty/puppet/issues/187
Puppet: wechaty-puppet-wechat4u<wechaty-puppet>@1.10.2<1.20.2>
Error
    at WechatifiedUserClass.listener (file:///wechat-chatgpt/node_modules/wechaty/src/user-modules/message.ts:344:21)
    at PuppetWechat4u.<anonymous> (file:///wechat-chatgpt/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:284:38)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Request failed with status code 401
    at createError (/wechat-chatgpt/node_modules/openai/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/wechat-chatgpt/node_modules/openai/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/wechat-chatgpt/node_modules/openai/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },

**Comment by RealTong** [comment]
https://github.com/fuergaosi233/wechat-chatgpt/pull/755

已解决
