### ISSUE TITLE
feat:再配置项中增加一个proxy4chatbot

### ISSUE THREAD

**Issue by m4p1e** [fuergaosi233/wechat-chatgpt#76]
跑docker镜像的时候，附加上https_proxy会导致微信登录出现重定向超上限... 报错如下

```
uncaughtException Error [ERR_FR_TOO_MANY_REDIRECTS]: Maximum number of redirects exceeded
    at Function.AxiosError.from (/app/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (/app/node_modules/axios/lib/adapters/http.js:518:25)
    at RedirectableRequest.emit (node:events:525:35)
    at RedirectableRequest.emit (node:domain:489:12)
    at RedirectableRequest._processResponse (/app/node_modules/follow-redirects/index.js:371:10)
    at ClientRequest.RedirectableRequest._onNativeResponse (/app/node_modules/follow-redirects/index.js:62:10)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:513:28)
    at ClientRequest.emit (node:domain:489:12)
    at HTTPParser.parserOnIncomingClient (node:_http_client:693:27) {
  code: 2,
  details: 'Error [ERR_FR_TOO_MANY_REDIRECTS]: Maximum number of redirects exceeded\n' +
    '    at Function.AxiosError.from (/app/node_modules/axios/lib/core/AxiosError.js:89:14)\n' +
    '    at RedirectableRequest.handleRequestError (/app/node_modules/axios/lib/adapters/http.js:518:25)\n' +
    '    at RedirectableRequest.emit (node:events:525:35)\n' +
    '    at RedirectableRequest.emit (node:domain:489:12)\n' +
    '    at RedirectableRequest._processResponse (/app/node_modules/follow-redirects/index.js:371:10)\n' +
    '    at ClientRequest.RedirectableRequest._onNativeResponse (/app/node_modules/follow-redirects/index.js:62:10)\n' +
    '    at Object.onceWrapper (node:events:628:26)\n' +
    '    at ClientRequest.emit (node:events:513:28)\n' +
    '    at ClientRequest.emit (node:domain:489:12)\n' +
    '    at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)'
```

**Comment by fuergaosi233** [comment]
https://github.com/fuergaosi233/wechat-chatgpt/pull/216
