### ISSUE TITLE
最新版本长文本报错

### ISSUE THREAD

**Issue by 29745560** [fuergaosi233/wechat-chatgpt#783]
🎯 Triggered ChatGPT: 我想写一篇论文
08:17:07 WARN PuppetWeChat friendshipRawPayload(4824959899253666714)
GError: Page crashed!
at Page._onTargetCrashed (/app/node_modules/puppeteer/src/common/Page.ts:774:24)
at /app/node_modules/puppeteer/src/common/Page.ts:573:53
at /app/node_modules/puppeteer/vendor/mitt/src/index.ts:88:75
at Array.map (<anonymous>)
at Object.emit (/app/node_modules/puppeteer/vendor/mitt/src/index.ts:88:56)
at CDPSession.emit (/app/node_modules/puppeteer/src/common/EventEmitter.ts:102:18)
at CDPSession._onMessage (/app/node_modules/puppeteer/src/common/Connection.ts:324:12)
at Connection._onMessage (/app/node_modules/puppeteer/src/common/Connection.ts:153:28)
at WebSocket.<anonymous> (/app/node_modules/puppeteer/src/node/NodeWebSocketTransport.ts:47:42)
at WebSocket.onMessage (/app/node_modules/puppeteer/node_modules/ws/lib/event-target.js:199:18) {
code: 2,
details: 'Error: Page crashed!\n' +
'    at Page._onTargetCrashed (/app/node_modules/puppeteer/src/common/Page.ts:774:24)\n' +
'    at /app/node_modules/puppeteer/src/common/Page.ts:573:53\n' +
'    at /app/node_modules/puppeteer/vendor/mitt/src/index.ts:88:75\n' +
'    at Array.map (<anonymous>)\n' +
'    at Object.emit (/app/node_modules/puppeteer/vendor/mitt/src/index.ts:88:56)\n' +
'    at CDPSession.emit (/app/node_modules/puppeteer/src/common/EventEmitter.ts:102:18)\n' +
'    at CDPSession._onMessage (/app/node_modules/puppeteer/src/common/Connection.ts:324:12)\n' +
'    at Connection._onMessage (/app/node_modules/puppeteer/src/common/Connection.ts:153:28)\n' +
'    at WebSocket.<anonymous> (/app/node_modules/puppeteer/src/node/NodeWebSocketTransport.ts:47:42)\n' +
'    at WebSocket.onMessage (/app/node_modules/puppeteer/node_modules/ws/lib/event-target.js:199:18)'
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by RealTong** [comment]
https://github.com/fuergaosi233/wechat-chatgpt/issues/770
