### ISSUE TITLE
运行一长段时间后报错AssertionError和GError

### ISSUE THREAD

**Issue by ANgdi** [fuergaosi233/wechat-chatgpt#794]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Deployment Platform

- [X] Railway
- [ ] Fly.io
- [ ] Docker & Docker Compose
- [ ] Node.js

### Description of the problem

挂在Railway正常运行了约20hrs后出现 AssertionError以及GError，求教怎么解决？

### wechat-chatgpt operation log

uncaughtException AssertionError [ERR_ASSERTION]: 3 == 0
at Object.equal (/app/node_modules/wechat4u/src/util/global.js:53:14)
at /app/node_modules/wechat4u/src/core.js:392:16
at processTicksAndRejections (node:internal/process/task_queues:95:5) {
code: 2,
details: 'AssertionError [ERR_ASSERTION]: 3 == 0\n' +
'    at Object.equal (/app/node_modules/wechat4u/src/util/global.js:53:14)\n' +
'    at /app/node_modules/wechat4u/src/core.js:392:16\n' +
'    at processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
10:04:47 WARN PuppetWatchdogAgent start() reset() reason: {"data":"syncCheck()","timeoutMilliseconds":60000}
uncaughtException GError: WatchdogAgent reset: lastFood: "{"data":"syncCheck()","timeoutMilliseconds":60000}"
at Watchdog.reset (file:///app/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)
at Watchdog.emit (node:events:512:28)
at Watchdog.emit (node:domain:489:12)
at Timeout._onTimeout (file:///app/node_modules/watchdog/src/watchdog.ts:115:12)
at listOnTimeout (node:internal/timers:573:17)
at processTimers (node:internal/timers:514:7) {
code: 2,
details: 'Error: WatchdogAgent reset: lastFood: "{"data":"syncCheck()","timeoutMilliseconds":60000}"\n' +
'    at Watchdog.reset (file:///app/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)\n' +
'    at Watchdog.emit (node:events:512:28)\n' +
'    at Watchdog.emit (node:domain:489:12)\n' +
'    at Timeout._onTimeout (file:///app/node_modules/watchdog/src/watchdog.ts:115:12)\n' +
'    at listOnTimeout (node:internal/timers:573:17)\n' +
'    at processTimers (node:internal/timers:514:7)'

![0d8d39dabcc8b1a39fa0ed09753741a](https://user-images.githubusercontent.com/34974327/227183428-8cfc9b5e-9e6e-457c-b55c-da958c2d4703.png)

**Comment by dustookk** [comment]
same issue here, could be too much texts in one message

**Comment by xwjla** [comment]
看源码每一个用户和用户发的消息以及系统回的消息都存在了data.ts文件中的db对象里，也就相当于存在了内存里，所以挂的时长太长，railway的内存吃不消，系统就容易卡主直到超时，定时重启或者维护db里的数据大小

**Comment by Lixianshengchao** [comment]
后台报这个错误怎么回事？
Error: Request failed with status code 400
    at createError (/app/node_modules/openai/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/openai/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/openai/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:524:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {

**Comment by dustookk** [comment]
> 看源码每一个用户和用户发的消息以及系统回的消息都存在了data.ts文件中的db对象里，也就相当于存在了内存里，所以挂的时长太长，railway的内存吃不消，系统就容易卡主直到超时，定时重启或者维护db里的数据大小

> 
还有就是每次都全部的上下文加到http的请求内容里，这里没有限制么？

**Comment by ANgdi** [comment]
> 看源码每一个用户和用户发的消息以及系统回的消息都存在了data.ts文件中的db对象里，也就相当于存在了内存里，所以挂的时长太长，railway的内存吃不消，系统就容易卡主直到超时，定时重启或者维护db里的数据大小

明白啦，感谢！
