### ISSUE TITLE
骗钱的垃圾，提示我：你需要开通微信支付，才可继续操作[Bug]: 

### ISSUE THREAD

**Issue by mingliuwulai** [fuergaosi233/wechat-chatgpt#797]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Deployment Platform

- [ ] Railway
- [ ] Fly.io
- [X] Docker & Docker Compose
- [ ] Node.js

### Description of the problem

<img width="834" alt="image" src="https://user-images.githubusercontent.com/37989318/227465682-f0fb496c-6ec8-48dc-ad69-5a98f2e056a3.png">
先获取登陆许可，再偷钱。大家小心点！！！

### wechat-chatgpt operation log

<details>
```console
 WARN PuppetWeChatBridge onDialog() page.on(dialog) type:type() {
        return this._type;
    } message:你需要开通微信支付，才可继续操作。
file:///app/node_modules/gerror/src/gerror/gerror.ts:69
      const e = new Error(payload)
                ^
GError: type() {
        return this._type;
    }(你需要开通微信支付，才可继续操作。)
    at Function.from (file:///app/node_modules/gerror/src/gerror/gerror.ts:69:17)
    at Bridge.onDialog (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:190:31)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 2,
  details: 'GError: type() {\n' +
    '        return this._type;\n' +
    '    }(你需要开通微信支付，才可继续操作。)\n' +
    '    at Function.from (file:///app/node_modules/gerror/src/gerror/gerror.ts:69:17)\n' +
    '    at Bridge.onDialog (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:190:31)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
[nodemon] app crashed - waiting for file changes before starting...

```
</details>

**Comment by bear-zd** [comment]
这个错误是因为账号没有实名吧

**Comment by lx348321409** [comment]
这是实名认证的 ，微信机制，你可以无知，但不能骂人

**Comment by yyy-charlie** [comment]
我也是刚注册了一个微信号去登录，报这个错是因为登录网页版要实名认证，这是微信的提示。。。

**Comment by mingliuwulai** [comment]
我的错，抱歉。看到错误提示有点想歪了。
