### ISSUE TITLE
[Bug]: 微信切换账号后，重新扫码登录会报错

### ISSUE THREAD

**Issue by yyy-charlie** [fuergaosi233/wechat-chatgpt#798]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Deployment Platform

- [X] Railway
- [ ] Fly.io
- [ ] Docker & Docker Compose
- [ ] Node.js

### Description of the problem

我新开了一个账号，切换到主账号后就会退出登录，重新登进来后再扫码就会报错，重启了好几次也没用，后面只能重新部署再扫码登录

### wechat-chatgpt operation log

<details>
```
08:52:22 ERR PuppetWeChatBridge onLoad() exception: Error: execute proxyWechaty(init) error: 503, init() without a ready angular env
file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:356
throw new Error('execute proxyWechaty(init) error: ' + retObj?.code + ', ' + retObj?.message)
^
GError: execute proxyWechaty(init) error: 503, init() without a ready angular env
at Bridge.inject (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:356:15)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Bridge.onLoad (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:214:7) {
code: 2,
details: 'Error: execute proxyWechaty(init) error: 503, init() without a ready angular env\n' +
'    at Bridge.inject (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:356:15)\n' +
'    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
'    at async Bridge.onLoad (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:214:7)'
}
[nodemon] app crashed - waiting for file changes before starting...
xvfb-run: error: Xvfb failed to start
xvfb-run: error: Xvfb failed to start
xvfb-run: error: Xvfb failed to start
xvfb-run: error: Xvfb failed to start
xvfb-run: error: Xvfb failed to start
xvfb-run: error: Xvfb failed to start
xvfb-run: error: Xvfb failed to start
xvfb-run: error: Xvfb failed to start
xvfb-run: error: Xvfb failed to start
```

</details>

**Comment by yyy-charlie** [comment]
![QQ截图20230324171018](https://user-images.githubusercontent.com/33770139/227477288-5d0bcefa-ce9d-4764-a89e-07c854e0c7b6.png)

**Comment by RealTong** [comment]
Delete the container and recreate it.
