### ISSUE TITLE
[Bug]: 使用问号?作为关键词报错

### ISSUE THREAD

**Issue by zccguagua** [fuergaosi233/wechat-chatgpt#799]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Deployment Platform

- [X] Railway
- [ ] Fly.io
- [ ] Docker & Docker Compose
- [ ] Node.js

### Description of the problem

我想使用问号?来作为触发关键词,所以CHAT_PRIVATE_TRIGGER_KEYWORD=?,但是报错了.错误如下,如何解决

### wechat-chatgpt operation log

<details>
```
SyntaxError: Invalid regular expression: /?/: Nothing to repeat
at new RegExp (<anonymous>)
at ChatGPTBot.get chatPrivateTriggerRule [as chatPrivateTriggerRule] (file:///app/src/bot.ts:49:15)
at ChatGPTBot.triggerGPTMessage (file:///app/src/bot.ts:168:26)
at ChatGPTBot.onMessage (file:///app/src/bot.ts:281:14)
at WechatyImpl.<anonymous> (file:///app/src/main.ts:40:26)
at WechatyImpl.emit (node:events:512:28)
at WechatyImpl.emit (node:domain:489:12)
at WechatyImpl.emit (file:///app/node_modules/wechaty/src/wechaty-mixins/gerror-mixin.ts:44:22)
at PuppetWeChat.<anonymous> (file:///app/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:281:22)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
```
</details>

**Comment by zccguagua** [comment]
我合并的了代码,现在可以使用"?"作为关键词触发,但要注意区分半角和全角"？"
