### ISSUE TITLE
[Bug]: Something went wrong，容器报错

### ISSUE THREAD

**Issue by Lixianshengchao** [fuergaosi233/wechat-chatgpt#806]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Deployment Platform

- [ ] Railway
- [ ] Fly.io
- [X] Docker & Docker Compose
- [ ] Node.js

### Description of the problem

运行一段时间，无法正常回复。Something went wrong 容器日志报错：
Error: Request failed with status code 400
    at createError (/app/node_modules/openai/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/openai/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/openai/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:524:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {

### wechat-chatgpt operation log

<details>
```console
Error: Request failed with status code 400
    at createError (/app/node_modules/openai/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/openai/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/openai/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:524:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
```
</details>

**Comment by RealTong** [comment]
检查一下你的key能不能用
