### ISSUE TITLE
[Bug]: 没有任何操作，自动crashed

### ISSUE THREAD

**Issue by zgqq** [fuergaosi233/wechat-chatgpt#830]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Deployment Platform

- [X] Railway
- [ ] Fly.io
- [ ] Docker & Docker Compose
- [ ] Node.js

### Description of the problem

应该是微信运动引起的？

### wechat-chatgpt operation log

<details>
```console
# Paste output here

🤵 Contact: 微信运动 💬 Text: [收到一条网页版微信暂不支持的消息类型，请在手机上查看]
🎯 Triggered ChatGPT: [收到一条网页版微信暂不支持的消息类型，请在手机上查看]
🤵 Contact: 权律三 💬 Text: 这条消息提示你需要在手机上查看，因为网页版微信暂不支持该消息类型。你可以尝试打开手机上的微信查看该消息。如果你已经在手机上查看了该消息但仍然无法解决问题，可以尝试联系微信客服获得更多帮助。
🤵 Contact: 微信运动 💬 Text: &lt;?xml version="1.0"?&gt;<br/>&lt;msg&gt;<br/>	&lt;appmsg appid="" sdkver="0"&gt;<br/>		&lt;title&gt;&lt;![CDATA[微信运动 | 常见问题解答]]&gt;&lt;/title&gt;<br/>		&lt;des&gt;&lt;![CDATA[数据同步不及时？运动数据暴露隐私？快进来，也许这里有你要的答案......]]&gt;&lt;/des&gt;<br/>		&lt;action /&gt;<br/>		&lt;type&gt;5&lt;/type&gt;<br/>		&lt;showtype&gt;0&lt;/showtype&gt;<br/>		&lt;soundtype&gt;0&lt;/soundtype&gt;<br/>		&lt;content&gt;&lt;![CDATA[]]&gt;&lt;/content&gt;<br/>		&lt;contentattr&gt;0&lt;/contentattr&gt;<br/>		&lt;url&gt;&lt;![CDATA[http://kf.qq.com/touch/scene_faq.html?scene_id=kf628]]&gt;&lt;/url&gt;<br/>		&lt;lowurl&gt;&lt;![CDATA[]]&gt;&lt;/lowurl&gt;<br/>		&lt;appattach&gt;<br/>			&lt;totallen&gt;0&lt;/totallen&gt;<br/>			&lt;attachid /&gt;<br/>			&lt;fileext /&gt;<br/>			&lt;cdnthumburl&gt;&lt;![CDATA[]]&gt;&lt;/cdnthumburl&gt;<br/>			&lt;cdnthumbaeskey&gt;&lt;![CDATA[]]&gt;&lt;/cdnthumbaeskey&gt;<br/>			&lt;aeskey&gt;&lt;![CDATA[]]&gt;&lt;/aeskey&gt;<br/>		&lt;/appattach&gt;<br/>		&lt;extinfo /&gt;<br/>		&lt;sourceusername&gt;&lt;/sourceusername&gt;<br/>		&lt;sourcedisplayname&gt;&lt;![CDATA[]]&gt;&lt;/sourcedisplayname&gt;<br/>		&lt;mmreader&gt;<br/>			&lt;category type="0" count="1"&gt;<br/>				&lt;name&gt;&lt;![CDATA[微信运动]]&gt;&lt;/name&gt;<br/>				&lt;topnew&gt;<br/>					&lt;cover&gt;&lt;![CDATA[http://mmbiz.qpic.cn/mmbiz/vCcMMOtJPofSAdyLehGQ4m5pVAIlZUiaMvKsflUKheNAKf7H8qLCbQY5Au8cW4iaWzyyEWuYLl99C0KTRhv8n4iaw/640?wx_fmt=jpeg&amp;tp=webp&amp;wxfrom=5]]&gt;&lt;/cover&gt;<br/>					&lt;width&gt;336&lt;/width&gt;<br/>					&lt;height&gt;215&lt;/height&gt;<br/>					&lt;digest&gt;&lt;![CDATA[数据同步不及时？运动数据暴露隐私？快进来，也许这里有你要的答案......]]&gt;&lt;/digest&gt;<br/>				&lt;/topnew&gt;<br/>				&lt;item&gt;<br/>					&lt;itemshowtype&gt;0&lt;/itemshowtype&gt;<br/>					&lt;title&gt;&lt;![CDATA[微信运动 | 常见问题解答]]&gt;&lt;/title&gt;<br/>					&lt;url&gt;&lt;![CDATA[http://kf.qq.com/touch/scene_faq.html?scene_id=kf628]]&gt;&lt;/url&gt;<br/>					&lt;shorturl&gt;&lt;![CDATA[]]&gt;&lt;/shorturl&gt;<br/>					&lt;longurl&gt;&lt;![CDATA[]]&gt;&lt;/longurl&gt;<br/>					&lt;pub_time&gt;1680015213&lt;/pub_time&gt;<br/>					&lt;cover&gt;&lt;![CDATA[http://mmbiz.qpic.cn/mmbiz/vCcMMOtJPofSAdyLehGQ4m5pVAIlZUiaMvKsflUKheNAKf7H8qLCbQY5Au8cW4iaWzyyEWuYLl99C0KTRhv8n4iaw/640?wx_fmt=jpeg&amp;tp=webp&amp;wxfrom=5]]&gt;&lt;/cover&gt;<br/>					&lt;tweetid /&gt;<br/>					&lt;digest&gt;&lt;![CDATA[数据同步不及时？运动数据暴露隐私？快进来，也许这里有你要的答案......]]&gt;&lt;/digest&gt;<br/>					&lt;fileid&gt;0&lt;/fileid&gt;<br/>					&lt;sources&gt;<br/>						&lt;source&gt;<br/>							&lt;name&gt;&lt;![CDATA[微信运动]]&gt;&lt;/name&gt;<br/>						&lt;/source&gt;<br/>					&lt;/sources&gt;<br/>					&lt;styles /&gt;<br/>					&lt;native_url /&gt;<br/>					&lt;del_flag&gt;0&lt;/del_flag&gt;<br/>					&lt;contentattr&gt;0&lt;/contentattr&gt;<br/>					&lt;play_length&gt;0&lt;/play_length&gt;<br/>					&lt;play_url&gt;&lt;![CDATA[]]&gt;&lt;/play_url&gt;<br/>					&lt;voice_id&gt;&lt;![CDATA[]]&gt;&lt;/voice_id&gt;<br/>					&lt;player&gt;&lt;![CDATA[]]&gt;&lt;/player&gt;<br/>					&lt;template_op_type&gt;0&lt;/template_op_type&gt;<br/>					&lt;weapp_username&gt;&lt;![CDATA[]]&gt;&lt;/weapp_username&gt;<br/>					&lt;weapp_path&gt;&lt;![CDATA[]]&gt;&lt;/weapp_path&gt;<br/>					&lt;weapp_version&gt;0&lt;/weapp_version&gt;<br/>					&lt;weapp_state&gt;0&lt;/weapp_state&gt;<br/>					&lt;music_source&gt;0&lt;/music_source&gt;<br/>					&lt;pic_num&gt;0&lt;/pic_num&gt;<br/>					&lt;show_complaint_button&gt;0&lt;/show_complaint_button&gt;<br/>					&lt;vid&gt;&lt;![CDATA[]]&gt;&lt;/vid&gt;<br/>					&lt;recommendation&gt;&lt;![CDATA[]]&gt;&lt;/recommendation&gt;<br/>					&lt;pic_urls /&gt;<br/>					&lt;comment_topic_id&gt;0&lt;/comment_topic_id&gt;<br/>					&lt;cover_235_1&gt;&lt;![CDATA[]]&gt;&lt;/cover_235_1&gt;<br/>					&lt;cover_1_1&gt;&lt;![CDATA[]]&gt;&lt;/cover_1_1&gt;<br/>					&lt;cover_16_9&gt;&lt;![CDATA[]]&gt;&lt;/cover_16_9&gt;<br/>					&lt;appmsg_like_type&gt;0&lt;/appmsg_like_type&gt;<br/>					&lt;video_width&gt;0&lt;/video_width&gt;<br/>					&lt;video_height&gt;0&lt;/video_height&gt;<br/>					&lt;is_pay_subscribe&gt;0&lt;/is_pay_subscribe&gt;<br/>					&lt;summary&gt;&lt;![CDATA[]]&gt;&lt;/summary&gt;<br/>					&lt;general_string&gt;&lt;![CDATA[]]&gt;&lt;/general_string&gt;<br/>					&lt;finder_feed /&gt;<br/>					&lt;finder_live /&gt;<br/>				&lt;/item&gt;<br/>			&lt;/category&gt;<br/>			&lt;publisher&gt;<br/>				&lt;username&gt;&lt;/username&gt;<br/>				&lt;nickname&gt;&lt;![CDATA[微信运动]]&gt;&lt;/nickname&gt;<br/>			&lt;/publisher&gt;<br/>			&lt;template_header /&gt;<br/>			&lt;template_detail /&gt;<br/>			&lt;forbid_forward&gt;0&lt;/forbid_forward&gt;<br/>			&lt;notify_msg /&gt;<br/>		&lt;/mmreader&gt;<br/>		&lt;thumburl&gt;&lt;![CDATA[http://mmbiz.qpic.cn/mmbiz/vCcMMOtJPofSAdyLehGQ4m5pVAIlZUiaMvKsflUKheNAKf7H8qLCbQY5Au8cW4iaWzyyEWuYLl99C0KTRhv8n4iaw/640?wx_fmt=jpeg&amp;tp=webp&amp;wxfrom=5]]&gt;&lt;/thumburl&gt;<br/>	&lt;/appmsg&gt;<br/>	&lt;fromusername&gt;&lt;/fromusername&gt;<br/>	&lt;appinfo&gt;<br/>		&lt;version&gt;0&lt;/version&gt;<br/>		&lt;appname&gt;&lt;![CDATA[微信运动]]&gt;&lt;/appname&gt;<br/>		&lt;isforceupdate&gt;1&lt;/isforceupdate&gt;<br/>	&lt;/appinfo&gt;<br/>&lt;/msg&gt;<br/>
🚪 Room: [耶]春田咕咕幼稚园 🤵 Contact: hao 💬 Text: 这么巧，我，我没妹子。
GError: Page crashed!
at Page._onTargetCrashed (/app/node_modules/puppeteer/src/common/Page.ts:774:24)
at /app/node_modules/puppeteer/src/common/Page.ts:573:53
at /app/node_modules/puppeteer/vendor/mitt/src/index.ts:88:75
at Array.map (<anonymous>)
at Object.emit (/app/node_modules/puppeteer/vendor/mitt/src/index.ts:88:56)
at CDPSession.emit (/app/node_modules/puppeteer/src/common/EventEmitter.ts:102:18)
at CDPSession._onMessage (/app/node_modules/puppeteer/src/common/Connection.ts:324:12)
at Connection._onMessage (/app/node_modules/puppeteer/src/common/Connection.ts:153:28)
at WebSocket.<anonymous> (/app/node_modules/puppeteer/src/node/NodeWebSocketTransport.ts:47:42)
at WebSocket.onMessage (/app/node_modules/puppeteer/node_modules/ws/lib/event-target.js:199:18) {
code: 2,
details: 'Error: Page crashed!\n' +
'    at Page._onTargetCrashed (/app/node_modules/puppeteer/src/common/Page.ts:774:24)\n' +
'    at /app/node_modules/puppeteer/src/common/Page.ts:573:53\n' +
'    at /app/node_modules/puppeteer/vendor/mitt/src/index.ts:88:75\n' +
'    at Array.map (<anonymous>)\n' +
'    at Object.emit (/app/node_modules/puppeteer/vendor/mitt/src/index.ts:88:56)\n' +
'    at CDPSession.emit (/app/node_modules/puppeteer/src/common/EventEmitter.ts:102:18)\n' +
'    at CDPSession._onMessage (/app/node_modules/puppeteer/src/common/Connection.ts:324:12)\n' +
'    at Connection._onMessage (/app/node_modules/puppeteer/src/common/Connection.ts:153:28)\n' +
'    at WebSocket.<anonymous> (/app/node_modules/puppeteer/src/node/NodeWebSocketTransport.ts:47:42)\n' +
'    at WebSocket.onMessage (/app/node_modules/puppeteer/node_modules/ws/lib/event-target.js:199:18)'
}
[nodemon] app crashed - waiting for file changes before starting...

```
</details>

**Comment by bobochangzzz** [comment]
同样情况。

**Comment by Li-dacheng** [comment]
+1

**Comment by Bo-Magazin** [comment]
+1

**Comment by CNRongRuo** [comment]
+1

**Comment by shixing2** [comment]
app crashed - waiting for file changes before starting...

**Comment by shixing2** [comment]
怎么解决？

**Comment by a472691** [comment]
+1

**Comment by keepondream** [comment]
+1

**Comment by Rayuuu** [comment]
+1，在大群里就非常容易crash

**Comment by RealTong** [comment]
> +1，在大群里就非常容易crash

程序会把和机器人互动的消息存入内容, 如果内存不够很容易crash

**Comment by a173030685** [comment]
> > +1，在大群里就非常容易crash
> 
> 程序会把和机器人互动的消息存入内容, 如果内存不够很容易crash

如何提高内存呢，railway
