### ISSUE TITLE
[Bug]: 运行一段时间后报错(出现一次)

### ISSUE THREAD

**Issue by zccguagua** [fuergaosi233/wechat-chatgpt#837]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Deployment Platform

- [X] Railway
- [ ] Fly.io
- [ ] Docker & Docker Compose
- [ ] Node.js

### Description of the problem

运行一段时间(大概8小时)后出现错误(昨天出现一次,今天运行17小时后未出现)日志如下

### wechat-chatgpt operation log

<details>
WARN PuppetWeChat roomRawPayload() currLength(442) <= prevLength(443) ???
 ERR PuppetWeChat roomRawPayload(@@3d81f253c69e61ed623984e8263fb0dc28a109eee873a3469b6848a12d8b749e) exception: no payload
file:///app/node_modules/gerror/src/gerror/gerror.ts:69
const e = new Error(payload)
^
GError: message not found for id: 4141691071674769556
at Function.from (file:///app/node_modules/gerror/src/gerror/gerror.ts:69:17)
at PuppetWeChat.<anonymous> (file:///app/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:277:45) {
code: 2,
details: 'GError: message not found for id: 4141691071674769556\n' +
'    at Function.from (file:///app/node_modules/gerror/src/gerror/gerror.ts:69:17)\n' +
'    at PuppetWeChat.<anonymous> (file:///app/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:277:45)'
}
[nodemon] app crashed - waiting for file changes before starting...
</details>

**Comment by Codeniu** [comment]
我也遇到这个错误了

**Comment by Codeniu** [comment]
我是一会就会出现这个错误

**Comment by SZnAl** [comment]
同样的问题，出发关键词没一会儿就报错了

**Comment by CoolHCL** [comment]
I have the same problem, too

**Comment by matrixyf** [comment]
一样的问题，我是在一个手机上开了双应用过来启动微信小号，怀疑是微信小号的进程被系统杀掉以后，机器人服务就自动挂了
