### ISSUE TITLE
Environment Variables的API何时可用？

### ISSUE THREAD

**Issue by M-Hun** [fuergaosi233/wechat-chatgpt#840]
首先非常感谢开发者对此项目地维护。README文件中Environment Variables的API为何划上了删除线？是指该功能正在开发中吗？我迫切地需要自定义我的ChatGPT API 地址。

**Comment by M-Hun** [comment]
docker自定义API后报错如下
`Error: Request failed with status code 404
    at createError (/app/node_modules/openai/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/openai/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/openai/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:524:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)`

**Comment by RealTong** [comment]
> docker自定义API后报错如下 `Error: Request failed with status code 404 at createError (/app/node_modules/openai/node_modules/axios/lib/core/createError.js:16:15) at settle (/app/node_modules/openai/node_modules/axios/lib/core/settle.js:17:12) at IncomingMessage.handleStreamEnd (/app/node_modules/openai/node_modules/axios/lib/adapters/http.js:322:11) at IncomingMessage.emit (node:events:524:35) at IncomingMessage.emit (node:domain:489:12) at endReadableNT (node:internal/streams/readable:1359:12) at processTicksAndRejections (node:internal/process/task_queues:82:21)`

`https://API.EXAMPLE.COM/v1` 
Note that it needs to be followed by `v1`
