### ISSUE TITLE
Railway方式：已经扫码登陆了，但是依旧在log里持续输出二维码，并且最后报错，错误如下：Error: Execution context was destroyed, most likely because of a navigation.

### ISSUE THREAD

**Issue by CharlesShao** [fuergaosi233/wechat-chatgpt#841]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Deployment Platform

- [X] Railway
- [ ] Fly.io
- [ ] Docker & Docker Compose
- [ ] Node.js

### Description of the problem

15:19:18 WARN PuppetWeChatBridge proxyWechaty() noWechaty exception: Error: Execution context was destroyed, most likely because of a navigation.
15:19:18 ERR PuppetWeChatBridge getUserName() exception: Execution context was destroyed, most likely because of a navigation.
15:19:18 ERR PuppetWeChatEvent onLogin() exception: Error: Execution context was destroyed, most likely because of a navigation.
GError: Execution context was destroyed, most likely because of a navigation.
at rewriteError (/app/node_modules/puppeteer/src/common/ExecutionContext.ts:322:15)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at async ExecutionContext._evaluateInternal (/app/node_modules/puppeteer/src/common/ExecutionContext.ts:271:7)
at async ExecutionContext.evaluate (/app/node_modules/puppeteer/src/common/ExecutionContext.ts:140:12)
at async Bridge.proxyWechaty (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:769:25)
at async Bridge.getUserName (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:417:24)
at async PuppetWeChat.onLogin (file:///app/node_modules/wechaty-puppet-wechat/src/event.ts:147:20) {
code: 2,
details: 'Error: Execution context was destroyed, most likely because of a navigation.\n' +
'    at rewriteError (/app/node_modules/puppeteer/src/common/ExecutionContext.ts:322:15)\n' +
'    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
'    at async ExecutionContext._evaluateInternal (/app/node_modules/puppeteer/src/common/ExecutionContext.ts:271:7)\n' +
'    at async ExecutionContext.evaluate (/app/node_modules/puppeteer/src/common/ExecutionContext.ts:140:12)\n' +
'    at async Bridge.proxyWechaty (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:769:25)\n' +
'    at async Bridge.getUserName (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:417:24)\n' +
'    at async PuppetWeChat.onLogin (file:///app/node_modules/wechaty-puppet-wechat/src/event.ts:147:20)'
}
[nodemon] app crashed - waiting for file changes before starting...

### wechat-chatgpt operation log

<details>
```console
15:19:18 WARN PuppetWeChatBridge proxyWechaty() noWechaty exception: Error: Execution context was destroyed, most likely because of a navigation.
15:19:18 ERR PuppetWeChatBridge getUserName() exception: Execution context was destroyed, most likely because of a navigation.
15:19:18 ERR PuppetWeChatEvent onLogin() exception: Error: Execution context was destroyed, most likely because of a navigation.
GError: Execution context was destroyed, most likely because of a navigation.
at rewriteError (/app/node_modules/puppeteer/src/common/ExecutionContext.ts:322:15)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at async ExecutionContext._evaluateInternal (/app/node_modules/puppeteer/src/common/ExecutionContext.ts:271:7)
at async ExecutionContext.evaluate (/app/node_modules/puppeteer/src/common/ExecutionContext.ts:140:12)
at async Bridge.proxyWechaty (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:769:25)
at async Bridge.getUserName (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:417:24)
at async PuppetWeChat.onLogin (file:///app/node_modules/wechaty-puppet-wechat/src/event.ts:147:20) {
code: 2,
details: 'Error: Execution context was destroyed, most likely because of a navigation.\n' +
'    at rewriteError (/app/node_modules/puppeteer/src/common/ExecutionContext.ts:322:15)\n' +
'    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
'    at async ExecutionContext._evaluateInternal (/app/node_modules/puppeteer/src/common/ExecutionContext.ts:271:7)\n' +
'    at async ExecutionContext.evaluate (/app/node_modules/puppeteer/src/common/ExecutionContext.ts:140:12)\n' +
'    at async Bridge.proxyWechaty (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:769:25)\n' +
'    at async Bridge.getUserName (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:417:24)\n' +
'    at async PuppetWeChat.onLogin (file:///app/node_modules/wechaty-puppet-wechat/src/event.ts:147:20)'
}
[nodemon] app crashed - waiting for file changes before starting...
```
</details>

**Comment by Newlearners** [comment]
微信扫码登录以后这个微信账号在手机客户端别退出，退出了就会报错

**Comment by DearChuck** [comment]
> 微信扫码登录以后这个微信账号在手机客户端别退出，退出了就会报错

你好，请问登陆后怎么使用啊？并没有看到使用方法啊
