### ISSUE TITLE
[Bug]: 微信登录出错

### ISSUE THREAD

**Issue by Carpe-Wang** [fuergaosi233/wechat-chatgpt#864]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Deployment Platform

- [X] Railway
- [ ] Fly.io
- [ ] Docker & Docker Compose
- [ ] Node.js

### Description of the problem

我尝试登陆了微信之后，会出现这种报错提醒。

### wechat-chatgpt operation log

<details>
```console
# Paste output here
 WARN PuppetWatchdogAgent start() reset() reason: {"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}
Apr 09 02:09:59.430 file:///app/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65
Apr 09 02:09:59.430 this.puppet.emit('error', new Error(
Apr 09 02:09:59.430 ^
Apr 09 02:09:59.433 GError: WatchdogAgent reset: lastFood: "{"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}"
Apr 09 02:09:59.433 at Watchdog.reset (file:///app/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)
Apr 09 02:09:59.433 at Watchdog.emit (node:events:512:28)
Apr 09 02:09:59.433 at Watchdog.emit (node:domain:489:12)
Apr 09 02:09:59.433 at Timeout._onTimeout (file:///app/node_modules/watchdog/src/watchdog.ts:115:12)
Apr 09 02:09:59.433 at listOnTimeout (node:internal/timers:573:17)
Apr 09 02:09:59.433 at processTimers (node:internal/timers:514:7) {
Apr 09 02:09:59.434 code: 2,
Apr 09 02:09:59.434 details: 'Error: WatchdogAgent reset: lastFood: "{"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}"\n' +
Apr 09 02:09:59.434 '    at Watchdog.reset (file:///app/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)\n' +
Apr 09 02:09:59.434 '    at Watchdog.emit (node:events:512:28)\n' +
Apr 09 02:09:59.434 '    at Watchdog.emit (node:domain:489:12)\n' +
Apr 09 02:09:59.434 '    at Timeout._onTimeout (file:///app/node_modules/watchdog/src/watchdog.ts:115:12)\n' +
Apr 09 02:09:59.434 '    at listOnTimeout (node:internal/timers:573:17)\n' +
Apr 09 02:09:59.434 '    at processTimers (node:internal/timers:514:7)'
Apr 09 02:09:59.434 }
Apr 09 02:09:59.756 [nodemon] app crashed - waiting for file changes before starting...

</details>

**Comment by ywzheng19** [comment]
群里@使用时，回复的答案中包含上一个人的回复，大佬有遇到过吗
