### ISSUE TITLE
[Bug]: 找不到id，然后报错了，整个容器就停止了

### ISSUE THREAD

**Issue by hh1336** [fuergaosi233/wechat-chatgpt#868]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Deployment Platform

- [ ] Railway
- [ ] Fly.io
- [X] Docker & Docker Compose
- [ ] Node.js

### Description of the problem

聊天过程中，就报错了，然后就出现了这个错误

### wechat-chatgpt operation log

<details>
```console
file:///app/node_modules/wechaty-puppet-wechat/src/firer.ts:355
      throw new Error('no id')
            ^
GError: no id
    at Firer.checkRoomLeave (file:///app/node_modules/wechaty-puppet-wechat/src/firer.ts:355:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PuppetWeChat.onMessage (file:///app/node_modules/wechaty-puppet-wechat/src/event.ts:218:29) {
  code: 2,
  details: 'Error: no id\n' +
    '    at Firer.checkRoomLeave (file:///app/node_modules/wechaty-puppet-wechat/src/firer.ts:355:13)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async PuppetWeChat.onMessage (file:///app/node_modules/wechaty-puppet-wechat/src/event.ts:218:29)'
}
[nodemon] app crashed - waiting for file changes before starting...
```
</details>

**Comment by Idoesfrontend** [comment]
Following @hh1336 did you find a sol?

**Comment by hh1336** [comment]
> 

no

**Comment by Idoesfrontend** [comment]
@hh1336 

I found a solution - I had to use more ram or minimize the amount of groups that I was in.
