### ISSUE TITLE
扫码登陆之后页面崩溃

### ISSUE THREAD

**Issue by wh1291753596** [fuergaosi233/wechat-chatgpt#874]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Deployment Platform

- [X] Railway
- [ ] Fly.io
- [ ] Docker & Docker Compose
- [ ] Node.js

### Description of the problem

使用微信扫码登陆，刚刚登陆就页面崩溃。等待无反应。重新部署无效

### wechat-chatgpt operation log

GError: Page crashed!
at Page._onTargetCrashed (/app/node_modules/puppeteer/src/common/Page.ts:774:24)
at /app/node_modules/puppeteer/src/common/Page.ts:573:53
at /app/node_modules/puppeteer/vendor/mitt/src/index.ts:88:75
at Array.map (<anonymous>)
at Object.emit (/app/node_modules/puppeteer/vendor/mitt/src/index.ts:88:56)
at CDPSession.emit (/app/node_modules/puppeteer/src/common/EventEmitter.ts:102:18)
at CDPSession._onMessage (/app/node_modules/puppeteer/src/common/Connection.ts:324:12)
at Connection._onMessage (/app/node_modules/puppeteer/src/common/Connection.ts:153:28)
at WebSocket.<anonymous> (/app/node_modules/puppeteer/src/node/NodeWebSocketTransport.ts:47:42)
at WebSocket.onMessage (/app/node_modules/puppeteer/node_modules/ws/lib/event-target.js:199:18) {
code: 2,
details: 'Error: Page crashed!\n' +
'    at Page._onTargetCrashed (/app/node_modules/puppeteer/src/common/Page.ts:774:24)\n' +
'    at /app/node_modules/puppeteer/src/common/Page.ts:573:53\n' +
'    at /app/node_modules/puppeteer/vendor/mitt/src/index.ts:88:75\n' +
'    at Array.map (<anonymous>)\n' +
'    at Object.emit (/app/node_modules/puppeteer/vendor/mitt/src/index.ts:88:56)\n' +
'    at CDPSession.emit (/app/node_modules/puppeteer/src/common/EventEmitter.ts:102:18)\n' +
'    at CDPSession._onMessage (/app/node_modules/puppeteer/src/common/Connection.ts:324:12)\n' +
'    at Connection._onMessage (/app/node_modules/puppeteer/src/common/Connection.ts:153:28)\n' +
'    at WebSocket.<anonymous> (/app/node_modules/puppeteer/src/node/NodeWebSocketTransport.ts:47:42)\n' +
'    at WebSocket.onMessage (/app/node_modules/puppeteer/node_modules/ws/lib/event-target.js:199:18)'
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by wayss000** [comment]
解决了吗？

**Comment by Hukybo** [comment]
GError: Page crashed!

**Comment by hejuntt1014** [comment]
pc微信登录一下微信把之前的鉴权给顶掉
