### ISSUE TITLE
[Bug]: 运行一段时间后就会报错崩溃掉，master分支

### ISSUE THREAD

**Issue by a173030685** [fuergaosi233/wechat-chatgpt#876]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Deployment Platform

- [X] Railway
- [ ] Fly.io
- [ ] Docker & Docker Compose
- [ ] Node.js

### Description of the problem

![image](https://user-images.githubusercontent.com/9361755/231990599-cbbda061-cac5-4c75-9bbe-e241f223573c.png)

### wechat-chatgpt operation log

<details>
```console
﻿GError: Page crashed!
﻿at Page._onTargetCrashed (/app/node_modules/puppeteer/src/common/Page.ts:774:24)
﻿at /app/node_modules/puppeteer/src/common/Page.ts:573:53
﻿at /app/node_modules/puppeteer/vendor/mitt/src/index.ts:88:75
﻿at Array.map (<anonymous>)
﻿at Object.emit (/app/node_modules/puppeteer/vendor/mitt/src/index.ts:88:56)
﻿at CDPSession.emit (/app/node_modules/puppeteer/src/common/EventEmitter.ts:102:18)
﻿at CDPSession._onMessage (/app/node_modules/puppeteer/src/common/Connection.ts:324:12)
﻿at Connection._onMessage (/app/node_modules/puppeteer/src/common/Connection.ts:153:28)
﻿at WebSocket.<anonymous> (/app/node_modules/puppeteer/src/node/NodeWebSocketTransport.ts:47:42)
﻿at WebSocket.onMessage (/app/node_modules/puppeteer/node_modules/ws/lib/event-target.js:199:18) {
﻿code: 2,
﻿details: 'Error: Page crashed!\n' +
﻿'    at Page._onTargetCrashed (/app/node_modules/puppeteer/src/common/Page.ts:774:24)\n' +
﻿'    at /app/node_modules/puppeteer/src/common/Page.ts:573:53\n' +
﻿'    at /app/node_modules/puppeteer/vendor/mitt/src/index.ts:88:75\n' +
﻿'    at Array.map (<anonymous>)\n' +
﻿'    at Object.emit (/app/node_modules/puppeteer/vendor/mitt/src/index.ts:88:56)\n' +
﻿'    at CDPSession.emit (/app/node_modules/puppeteer/src/common/EventEmitter.ts:102:18)\n' +
﻿'    at CDPSession._onMessage (/app/node_modules/puppeteer/src/common/Connection.ts:324:12)\n' +
﻿'    at Connection._onMessage (/app/node_modules/puppeteer/src/common/Connection.ts:153:28)\n' +
﻿'    at WebSocket.<anonymous> (/app/node_modules/puppeteer/src/node/NodeWebSocketTransport.ts:47:42)\n' +
﻿'    at WebSocket.onMessage (/app/node_modules/puppeteer/node_modules/ws/lib/event-target.js:199:18)'
﻿}
﻿[nodemon] app crashed - waiting for file changes before starting...

```
</details>

**Comment by kama0301** [comment]
遇到了相同的问题，后来每次用完都手动/cmd clear 情况有改善，但未杜绝。看看大佬们有啥说法。

**Comment by lansfair** [comment]
遇到了相同问题

**Comment by CCTV-MMM** [comment]
+1 +1

**Comment by a951545797** [comment]
遇到相同情况，我每次都重启。
