### ISSUE TITLE
[Bug]: 使用一段时间会出错,重新扫二维码也无法登录,只能重启docker

### ISSUE THREAD

**Issue by lai80x** [fuergaosi233/wechat-chatgpt#893]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Deployment Platform

- [ ] Railway
- [ ] Fly.io
- [X] Docker & Docker Compose
- [ ] Node.js

### Description of the problem

使用一段时间会出错,重新扫二维码也无法登录,只能重启docker
有时重启也没有用,需要 docker stop, 再docker start

### wechat-chatgpt operation log

<details>
```console
12:50:29 ERR PuppetWeChatBridge onLoad() exception: Error: execute proxyWechaty(init) error: 503, init() without a ready angular env
file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:356
        throw new Error('execute proxyWechaty(init) error: ' + retObj?.code + ', ' + retObj?.message)
              ^
GError: execute proxyWechaty(init) error: 503, init() without a ready angular env
    at Bridge.inject (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:356:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Bridge.onLoad (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:214:7) {
  code: 2,
  details: 'Error: execute proxyWechaty(init) error: 503, init() without a ready angular env\n' +
    '    at Bridge.inject (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:356:15)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Bridge.onLoad (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:214:7)'
}
[nodemon] app crashed - waiting for file changes before starting...
xvfb-run: error: Xvfb failed to start

> wechat-chatgpt@1.0.0 dev
> nodemon --exec node --loader ts-node/esm src/main.ts

[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/*.ts
[nodemon] watching extensions: ts
[nodemon] starting `node --loader ts-node/esm src/main.ts`
(node:54) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
```
</details>

**Comment by LongYi8013609** [comment]
Railway 上也是一样

**Comment by RoboGPT** [comment]
请问一段时间是多久？ 是半天， 一天，还是三天，一个星期？

**Comment by lai80x** [comment]
之前是三天，后来一天，现在是半天。
![微信截图_20230615100114](https://github.com/fuergaosi233/wechat-chatgpt/assets/6836290/d3794ad2-2e67-4a37-a577-4533c14a7f5b)
![微信截图_20230615100714](https://github.com/fuergaosi233/wechat-chatgpt/assets/6836290/9b822ae8-3f9f-4579-8b94-cb8f0cdaa060)
另外请问下 docker logs -f wechat-chatgpt 后会闪出一堆之前的对话记录，这个在哪清理。直接与微信对话 /cmd clear无效
