### ISSUE TITLE
[Bug]: 微信必须支持微信支付吗

### ISSUE THREAD

**Issue by fluidog** [fuergaosi233/wechat-chatgpt#900]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Deployment Platform

- [ ] Railway
- [ ] Fly.io
- [X] Docker & Docker Compose
- [ ] Node.js

### Description of the problem

![image](https://github.com/fuergaosi233/wechat-chatgpt/assets/31918437/f0b33b49-3fdd-4483-a943-74f8257c0a75)

### wechat-chatgpt operation log

<details>
```console
# Paste output here
07:02:49 WARN PuppetWeChatBridge onDialog() page.on(dialog) type:type() {
        return this._type;
    } message:To continue, enable Weixin Pay first.
file:///app/node_modules/gerror/src/gerror/gerror.ts:69
      const e = new Error(payload)
                ^
GError: type() {
        return this._type;
    }(To continue, enable Weixin Pay first.)
    at Function.from (file:///app/node_modules/gerror/src/gerror/gerror.ts:69:17)
    at Bridge.onDialog (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:190:31)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 2,
  details: 'GError: type() {\n' +
    '        return this._type;\n' +
    '    }(To continue, enable Weixin Pay first.)\n' +
    '    at Function.from (file:///app/node_modules/gerror/src/gerror/gerror.ts:69:17)\n' +
    '    at Bridge.onDialog (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:190:31)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
[nodemon] app crashed - waiting for file changes before starting...
```
</details>

**Comment by houkaiyao** [comment]
实名认证没
