### ISSUE TITLE
[Bug]: Docker 无法登录

### ISSUE THREAD

**Issue by WorldHim** [fuergaosi233/wechat-chatgpt#906]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Deployment Platform

- [ ] Railway
- [ ] Fly.io
- [x] Docker & Docker Compose
- [ ] Node.js

### Description of the problem

登录后报错

### wechat-chatgpt operation log

<details>
```console
2023-08-22T10:34:52.526828912Z 10:34:52 WARN PuppetWatchdogAgent start() reset() reason: {"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}
2023-08-22T10:34:52.546954562Z file:///app/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65
2023-08-22T10:34:52.547011018Z       this.puppet.emit('error', new Error(
2023-08-22T10:34:52.547018403Z                                 ^
2023-08-22T10:34:52.551434990Z GError: WatchdogAgent reset: lastFood: "{"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}"
2023-08-22T10:34:52.551471738Z     at Watchdog.reset [90m(file:///app/[39mnode_modules/[4mwechaty-puppet[24m/src/agents/watchdog-agent.ts:65:33[90m)[39m
2023-08-22T10:34:52.551479217Z [90m    at Watchdog.emit (node:events:512:28)[39m
2023-08-22T10:34:52.551484919Z [90m    at Watchdog.emit (node:domain:489:12)[39m
2023-08-22T10:34:52.551490363Z     at Timeout._onTimeout [90m(file:///app/[39mnode_modules/[4mwatchdog[24m/src/watchdog.ts:115:12[90m)[39m
2023-08-22T10:34:52.551495833Z [90m    at listOnTimeout (node:internal/timers:573:17)[39m
2023-08-22T10:34:52.551500938Z [90m    at processTimers (node:internal/timers:514:7)[39m {
2023-08-22T10:34:52.551506298Z   code: [33m2[39m,
2023-08-22T10:34:52.551511830Z   details: [32m'Error: WatchdogAgent reset: lastFood: "{"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}"\n'[39m +
2023-08-22T10:34:52.551518123Z     [32m'    at Watchdog.reset (file:///app/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)\n'[39m +
2023-08-22T10:34:52.551524050Z     [32m'    at Watchdog.emit (node:events:512:28)\n'[39m +
2023-08-22T10:34:52.551529477Z     [32m'    at Watchdog.emit (node:domain:489:12)\n'[39m +
2023-08-22T10:34:52.551535157Z     [32m'    at Timeout._onTimeout (file:///app/node_modules/watchdog/src/watchdog.ts:115:12)\n'[39m +
2023-08-22T10:34:52.551540919Z     [32m'    at listOnTimeout (node:internal/timers:573:17)\n'[39m +
2023-08-22T10:34:52.551546573Z     [32m'    at processTimers (node:internal/timers:514:7)'[39m
2023-08-22T10:34:52.551552012Z }
2023-08-22T10:34:52.586487678Z [31m[nodemon] app crashed - waiting for file changes before starting...[39m
```
</details>
完整日志

[2023_8_22 19_12_27_log.txt](https://github.com/fuergaosi233/wechat-chatgpt/files/12408119/2023_8_22.19_12_27_log.txt)

**Comment by WorldHim** [comment]
> 请确保您的账号可以登陆 [网页版微信](https://wx.qq.com/)。
