### ISSUE TITLE
[bugs] Don't show the QR code after excute `docker logs -f wechat-chatgpt`.

### ISSUE THREAD

**Issue by A11en0** [fuergaosi233/wechat-chatgpt#95]
```
OS: Linux Debian 10
```

```
uncaughtException AssertionError [ERR_ASSERTION]: 400 != 400                             
    at Object.notEqual (/app/node_modules/wechat4u/src/util/global.js:63:14)             
    at /app/node_modules/wechat4u/src/core.js:108:16                                     
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {              
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 400 != 400\n' +                              
    '    at Object.notEqual (/app/node_modules/wechat4u/src/util/global.js:63:14)\n' +   
    '    at /app/node_modules/wechat4u/src/core.js:108:16\n' +                           
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'          
}
```

![image](https://user-images.githubusercontent.com/33925232/206638274-7e9de809-8088-4320-846f-83663aedda17.png)

**Comment by derek1909** [comment]
Same issue, OS: MacOS 13.0.1

**Comment by lslswin** [comment]
有解决方法吗？我也遇到同样的问题

**Comment by A11en0** [comment]
无法解决

**Comment by Aesthetican** [comment]
centos 7.9.2009 同错误

**Comment by fuergaosi233** [comment]
Try to change the  Wechat account?

**Comment by zehuichen123** [comment]
@fuergaosi233 Hi, I met the same problem, and this problem occurs before I scan the QR code, just the time I run this command.

**Comment by ymaGo** [comment]
windows11，docker运行，报同样错误
2022-12-10 21:03:03 
2022-12-10 21:03:03 > wechat-chatgpt@1.0.0 dev
2022-12-10 21:03:03 > nodemon --exec node --watch config.yaml --loader ts-node/esm src/main.ts
2022-12-10 21:03:03 
2022-12-10 21:03:04 [nodemon] 2.0.20
2022-12-10 21:03:04 [nodemon] to restart at any time, enter `rs`
2022-12-10 21:03:04 [nodemon] watching path(s): config.yaml
2022-12-10 21:03:04 [nodemon] watching extensions: ts
2022-12-10 21:03:04 [nodemon] starting `node --loader ts-node/esm src/main.ts`
2022-12-10 21:03:20 uncaughtException GError: getaddrinfo EAI_AGAIN login.wx.qq.com
2022-12-10 21:03:20     at Function.AxiosError.from (/app/node_modules/axios/lib/core/AxiosError.js:89:14)
2022-12-10 21:03:20     at RedirectableRequest.handleRequestError (/app/node_modules/axios/lib/adapters/http.js:518:25)
2022-12-10 21:03:20     at RedirectableRequest.emit (node:events:525:35)
2022-12-10 21:03:20     at RedirectableRequest.emit (node:domain:489:12)
2022-12-10 21:03:20     at ClientRequest.eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:14:24)
2022-12-10 21:03:20     at ClientRequest.emit (node:events:513:28)
2022-12-10 21:03:20     at ClientRequest.emit (node:domain:489:12)
2022-12-10 21:03:20     at TLSSocket.socketErrorListener (node:_http_client:494:9)
2022-12-10 21:03:20     at TLSSocket.emit (node:events:513:28)
2022-12-10 21:03:20     at TLSSocket.emit (node:domain:489:12) {
2022-12-10 21:03:20   code: 2,
2022-12-10 21:03:20   details: 'Error: getaddrinfo EAI_AGAIN login.wx.qq.com\n' +
2022-12-10 21:03:20     '    at Function.AxiosError.from (/app/node_modules/axios/lib/core/AxiosError.js:89:14)\n' +
2022-12-10 21:03:20     '    at RedirectableRequest.handleRequestError (/app/node_modules/axios/lib/adapters/http.js:518:25)\n' +
2022-12-10 21:03:20     '    at RedirectableRequest.emit (node:events:525:35)\n' +
2022-12-10 21:03:20     '    at RedirectableRequest.emit (node:domain:489:12)\n' +
2022-12-10 21:03:20     '    at ClientRequest.eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:14:24)\n' +
2022-12-10 21:03:20     '    at ClientRequest.emit (node:events:513:28)\n' +
2022-12-10 21:03:20     '    at ClientRequest.emit (node:domain:489:12)\n' +
2022-12-10 21:03:20     '    at TLSSocket.socketErrorListener (node:_http_client:494:9)\n' +
2022-12-10 21:03:20     '    at TLSSocket.emit (node:events:513:28)\n' +
2022-12-10 21:03:20     '    at TLSSocket.emit (node:domain:489:12)'
2022-12-10 21:03:20 }
2022-12-10 21:03:04 (node:32) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
2022-12-10 21:03:04 (Use `node --trace-warnings ...` to show where the warning was created)

**Comment by Yy2z** [comment]
同问

**Comment by Yy2z** [comment]
我刚刚把我的token值写错了，重新正确输入就好了；

**Comment by hiboydidi** [comment]
有解决的吗

**Comment by Aesthetican** [comment]
我是微信实名认证后就好了

**Comment by A11en0** [comment]
There's no relation with real-name authentication because it occurs before scanning the QR code.

**Comment by A11en0** [comment]
> 我刚刚把我的token值写错了，重新正确输入就好了；

Using the username and password also suffers from the problem.

**Comment by A11en0** [comment]
> Try to change the Wechat account?

It has nothing to do with the account, we even haven't scanned the QR code.

**Comment by RealTong** [comment]
Scan the link above the QR code.
