### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'chatGpt')  (I find the reason and have sloved)

### ISSUE THREAD

**Issue by currencytong** [fuergaosi233/wechat-chatgpt#97]
I use another wechat accout to send a message,  but there is no response.

![image](https://user-images.githubusercontent.com/72449596/206639946-c1c665bc-8419-45e6-81a8-9db9ff74ac59.png)

**Comment by chaoming56** [comment]
me too

**Comment by pikachu233666** [comment]
me too

**Comment by vicky1221** [comment]
me too

**Comment by laotutou007** [comment]
me too

**Comment by zkeq** [comment]
I have the same problem.
```js
🎯 Triggered ChatGPT: myfirstAI 你好
TypeError: Cannot read properties of undefined (reading 'chatGpt')
    at ChatGPTPoole.getConversation (file:///C:/Users/Wangt/OneDrive/%E6%A1%8C%E9%9D%A2/wechat-chatgpt/src/chatgpt.ts:112:34)
    at ChatGPTPoole.sendMessage (file:///C:/Users/Wangt/OneDrive/%E6%A1%8C%E9%9D%A2/wechat-chatgpt/src/chatgpt.ts:122:35)
    at ChatGPTBot.getGPTMessage (file:///C:/Users/Wangt/OneDrive/%E6%A1%8C%E9%9D%A2/wechat-chatgpt/src/chatgpt.ts:183:35)
    at ChatGPTBot.onPrivateMessage (file:///C:/Users/Wangt/OneDrive/%E6%A1%8C%E9%9D%A2/wechat-chatgpt/src/chatgpt.ts:238:35)
    at ChatGPTBot.onMessage (file:///C:/Users/Wangt/OneDrive/%E6%A1%8C%E9%9D%A2/wechat-chatgpt/src/chatgpt.ts:264:27)
    at WechatyImpl.<anonymous> (file:///C:/Users/Wangt/OneDrive/%E6%A1%8C%E9%9D%A2/wechat-chatgpt/src/main.ts:30:24)
    at WechatyImpl.emit (node:events:527:28)
    at WechatyImpl.emit (node:domain:475:12)
    at WechatyImpl.emit (file:///C:/Users/Wangt/OneDrive/%E6%A1%8C%E9%9D%A2/wechat-chatgpt/node_modules/wechaty/src/wechaty-mixins/gerror-mixin.ts:44:22)
    at PuppetWechat4u.<anonymous> (file:///C:/Users/Wangt/OneDrive/%E6%A1%8C%E9%9D%A2/wechat-chatgpt/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:281:22)
```

**Comment by laotutou007** [comment]
right，I have the same problem too.

`TypeError: Cannot read properties of undefined (reading 'chatGpt')
    at ChatGPTPoole.getConversation (file:///Users/maikesi/Downloads/wechat-chatgpt-main/src/chatgpt.ts:112:34)
    at ChatGPTPoole.sendMessage (file:///Users/maikesi/Downloads/wechat-chatgpt-main/src/chatgpt.ts:122:35)
    at ChatGPTBot.getGPTMessage (file:///Users/maikesi/Downloads/wechat-chatgpt-main/src/chatgpt.ts:183:35)
    at ChatGPTBot.onPrivateMessage (file:///Users/maikesi/Downloads/wechat-chatgpt-main/src/chatgpt.ts:238:35)
    at ChatGPTBot.onMessage (file:///Users/maikesi/Downloads/wechat-chatgpt-main/src/chatgpt.ts:264:27)
    at WechatyImpl.<anonymous> (file:///Users/maikesi/Downloads/wechat-chatgpt-main/src/main.ts:30:24)
    at WechatyImpl.emit (node:events:513:28)
    at WechatyImpl.emit (node:domain:489:12)
    at WechatyImpl.emit (file:///Users/maikesi/Downloads/wechat-chatgpt-main/node_modules/wechaty/src/wechaty-mixins/gerror-mixin.ts:44:22)
    at PuppetWechat4u.<anonymous> (file:///Users/maikesi/Downloads/wechat-chatgpt-main/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:281:22)`

**Comment by chaoming56** [comment]
用session 登陆就可以解决。
是登陆问题

**Comment by Kayce001** [comment]
就是用session登陆的

**Comment by chaoming56** [comment]
> 就是用session登陆的

启动程序的时候，有报错吗？

**Comment by pikachu233666** [comment]
我也是用session登陆报错的，启动时无报错

**Comment by pikachu233666** [comment]
> > 就是用session登陆的
> 
> 启动程序的时候，有报错吗？

我也是用session登陆报错的，启动时无报错

**Comment by youaremywind** [comment]
我也是使用session 登陆报错

**Comment by zkeq** [comment]
This error is triggered when WeChat receives the message, so I don't think it's a problem with the `session` .

这个报错是微信收到消息时触发的，所以我想这不是 `session` 的问题。

**Comment by currencytong** [comment]
I am so sorry, it's my fault !!!
The main reason is I run the docker and  npm run dev at the same time.
Just make a config.yaml and fill your session_token in the root directory, then run the docker command (docker run -d --name wechat-chatgpt -v $(pwd)/config.yaml:/app/config.yaml holegots/wechat-chatgpt:latest). 
Finally,run (docker logs -f wechat-chatgpt) command to login with qrcode.

非常抱歉，我的错误, 我找到了原因。
我在运行docker容器的同时又进行了手动安装的步骤，再次运行了npm run dev
只需要在根目录创建config.yaml文件，将config.yaml.example中内容复制进去，再把session_token填入，用(docker run -d --name wechat-chatgpt -v $(pwd)/config.yaml:/app/config.yaml holegots/wechat-chatgpt:latest)命令启动docker,再运行(docker logs -f wechat-chatgpt )扫码登陆就可以了。

**Comment by currencytong** [comment]
> I am so sorry, it's my fault !!! The main reason is I run the docker and npm run dev at the same time. Just make a config.yaml and fill your session_token in the root directory, then run the docker command (docker run -d --name wechat-chatgpt -v $(pwd)/config.yaml:/app/config.yaml holegots/wechat-chatgpt:latest). Finally,run (docker logs -f wechat-chatgpt) command to login with qrcode.
> 
> 非常抱歉，我的错误, 我找到了原因。 我在运行docker容器的同时又进行了手动安装的步骤，再次运行了npm run dev 只需要在根目录创建config.yaml文件，将config.yaml.example中内容复制进去，再把session_token填入，用(docker run -d --name wechat-chatgpt -v $(pwd)/config.yaml:/app/config.yaml holegots/wechat-chatgpt:latest)命令启动docker,再运行(docker logs -f wechat-chatgpt )扫码登陆就可以了。

I am so sorry, it's my fault !!!
The main reason is I run the docker and npm run dev at the same time.
Just make a config.yaml and fill your session_token in the root directory, then run the docker command (docker run -d --name wechat-chatgpt -v $(pwd)/config.yaml:/app/config.yaml holegots/wechat-chatgpt:latest).
Finally,run (docker logs -f wechat-chatgpt) command to login with qrcode.

非常抱歉，我的错误, 我找到了原因。
我在运行docker容器的同时又进行了手动安装的步骤，再次运行了npm run dev
只需要在根目录创建config.yaml文件，将config.yaml.example中内容复制进去，再把session_token填入，用(docker run -d --name wechat-chatgpt -v $(pwd)/config.yaml:/app/config.yaml holegots/wechat-chatgpt:latest)命令启动docker,再运行(docker logs -f wechat-chatgpt )扫码登陆就可以了。
