### ISSUE TITLE
Request failed with status code 503

### ISSUE THREAD

**Issue by mengziin** [fuergaosi233/wechat-chatgpt#98]
npm run dev ，出现下面的错误，请问怎么解决下呀

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/8908079/206644100-6a2007ab-768d-43f2-8581-f13d6e246e5d.png">

**Comment by Yecgaa1** [comment]
我也遇到了相同的问题，如何处理

**Comment by Yecgaa1** [comment]
```shell

> wechat-chatgpt@1.0.0 dev
> nodemon --exec node --loader ts-node/esm src/main.ts

[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/**/*
[nodemon] watching extensions: ts
[nodemon] starting `node --loader ts-node/esm src/main.ts`
(node:32) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
uncaughtException GError [AxiosError]: Request failed with status code 503
    at settle (/app/node_modules/axios/lib/core/settle.js:19:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:497:11)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 2,
  details: 'AxiosError: Request failed with status code 503\n' +
    '    at settle (/app/node_modules/axios/lib/core/settle.js:19:12)\n' +
    '    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:497:11)\n' +
    '    at IncomingMessage.emit (node:events:525:35)\n' +
    '    at IncomingMessage.emit (node:domain:489:12)\n' +
    '    at endReadableNT (node:internal/streams/readable:1358:12)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:83:21)'
}

```
顺带一提的，我检查网络日志时发现有个请求确实已经发出(我给docker通过~/.docker/config.json指定了http代理）
`2022/12/09 08:54:41.761 [I] [io.go:428] 172.17.0.5:49652 accepted https://login.wx.qq.com/jslogin?appid=wx782c26e4c19acffb&fun=new&lang=zh-CN&redirect_uri=https://wx.qq.com/cgi-bin/mmwebwx-bin/webwxnewloginpage?mod=desktop [direct]`

**Comment by Yecgaa1** [comment]
我发现503错误的出现与我给docker使用了http代理有关，即上面提到的~/.docker/config.json设置的

**Comment by Yecgaa1** [comment]
但是直到今天早上了这个问题似乎仍然存在，且我关闭对docker设置代理该问题就消失了

> > 我发现503错误的出现与我给docker使用了http代理有关，即上面提到的~/.docker/config.json设置的
> 
> 503在国外服务器也会出现，是昨天chatgpt服务器的问题
